### ISSUE TITLE
Add Multilanguage support

### ISSUE THREAD

**Issue by pokoli** [stephenmcd/mezzanine#106]
Mezzanine it's a cool django based cms but IMHO lacks of multilanguage support. 

Why not integrating a django-app for translating like: 

http://code.google.com/p/django-transmeta/

or

http://code.google.com/p/django-modeltranslation/

**Comment by Lumpusz** [comment]
It's been almost a year now. Is there any plans on adding support for multilingual sites based on mezzanine? @stephenmcd Do you have plans to merge any of the solutions implemented by others, or planning something on your own? Please, give us some update, as multilingual support would be vital for many of us! Thanks.

**Comment by stephenmcd** [comment]
Last I recall it was incomplete. 

Would you be interested in reviving it and working out what needs to be done and finishing it off?

**Comment by Lumpusz** [comment]
Well... To be honest I've only started development with mezzanine recently. But sure, why not! Do you have some kind of checklist what works and what is missing? Are you planning to work on it yourself?

**Comment by stephenmcd** [comment]
No on both accounts I'm afraid, which is why I mentioned the need to first work out what needs to be done :-)

I'd suggest reading through the linked PRs in this thread as well as the mailing list thread to start with. I vaguely recall it being complete apart from the admin interface which was showing all fields for all languages at once, and needed some form of JS/tabbed view for showing fields for only one language at a time. Perhaps others who have been involved can provide some more detailed guidance than that.

**Comment by alan-hicks** [comment]
From my limited experience clients tend to fall into two categories, one where content is merely translated, and the other more language friendly one where content is broadly mirrored on language micro-sites.

The fork at https://github.com/alan-hicks/mezzanine does the latter with a working demo at http://mldemo.p-o.co.uk/ and source at https://github.com/alan-hicks/mldemo there is also a more realistic work in progress at http://raitbattery.p-o.co.uk/

**Comment by Lumpusz** [comment]
@stephenmcd I've just found such a widget here https://github.com/stephenmcd/mezzanine/issues/106#issuecomment-30782121. Don't you think that can be used as the missing part?
I've found many custom solutions to this issue (https://github.com/vstoykov/django-magic-translation by @vstoykov, https://github.com/Kniyl/mezzanine by @Kniyl , https://github.com/cccs-web/mezzanine by @pwhipp, @alan-hicks's solution which is mentioned in the previous post), they all look promising, but my concern with them is that they are only forks, extensions and not part of mezzanine itself. Using a fork, or an extension always comes with additional risk, such as incompatibilities, abandoned projects, delayed merges, conflicting with later official support, just to mention a few.
All in all, I would rather start using something which is part of mezzanine itself!
I know you have done some experimenting with @Kniyl's fork, do you think that one, or any of the available solutions might be a good candidate for a merge?

Thanks

**Comment by Kniyl** [comment]
Hi guys, sorry for letting this work sink at some point. I got the last modifications needed into PR #1019 which were USE_MODELTRANSLATION not being accessible in templates and admin not being tabbed.

There was a question at some point, though, asking if we should use translatable slug or not (and possibly rely on i18n_pattern instead). The question is still open but I think it can potentially lead to breakages (especially for the BLOG_SLUG mechanism).

It has been a while, though, and I saw that there were conflicting files in the PR. Should I try to get some time to investigate it or is there someone else willing to do it?

**Comment by jerivas** [comment]
Hi everybody. Mathias just committed some fixes in his fork. I just tried it out (Django 1.6.10, Model translation 0.8) and it is working great both in the Admin and the public site. I propose we move any further discussion to the PR (#1019).

**Comment by Lumpusz** [comment]
Agreed.

**Comment by fedelibre** [comment]
Now that #1019 is merged, I guess that this should be closed

**Comment by stephenmcd** [comment]
Yep, thanks!
