### ISSUE TITLE
Configurable branding for admin interface (ie. admin/base_site.html)

### ISSUE THREAD

**Issue by derkaderka** [stephenmcd/mezzanine#112]
At the moment the branding of the admin interface contains static references to Mezzanine, this should be made a configurable setting along the line sof GRAPPELLI_\* options to rename parts of the admin interface.

  {% block title %}{{ title }} | | Mezzanine{% endblock %}
  {% block branding %}<h1 id="site-name">| Mezzanine</h1>{% endblock %}
  {% block nav-global %}{% endblock %}

At the moment it is impossible to override these blocks without fully copying the entire template into the project tree. Otherwise the parser will enter an infinite recursion loop and raise a stack depth exception trying to extend the base_site template.

**Comment by bensialih** [comment]
Thats very nice that there is a push for marketing mezzanine but the user isnt really the person who will recreate mezzanine elsewhere.
I think it drastically devalues your efforts at promoting mezzanine as a real customizable contender for wordpress when its not customizable. of course making the "branding" a non editable part of mezzanine is out and out ametuerish.

Mezzanine has been a real gift for me & previously I thought the team who developed this as part of the python vanguard, of course now its become amateur hour.

Clients that we build this for expect that our software is bespoke & not a template.
Bypassed all of this with a simple JS change but im really disappointing.

Side note, Ive always believed that the charm of django is that if a developer needs something, it has probably been done before so I have to figure out how to do it without re-inventing the wheel.

Ive spent 3 hours trying to figure out how to make this change.

Conclusion,
Disappointed.
