### ISSUE TITLE
ValueError when surfing to /comments/

### ISSUE THREAD

**Issue by Xeniac-at** [stephenmcd/mezzanine#1159]
it's a minor inconvenience. 
When you try to open _http://your.mezzanine.page/comments/_ in your browser you will get a Error 500.
with _DEBUG = True_ it will be:

>  **ValueError** at /comment/
>  need more than 1 value to unpack
>  **Exception Location:**  /virtenv/lib/python2.7/site-packages/mezzanine/utils/models.py in get_model, line 35

Im pretty sure _/comment/_ is not meant to be accessed directly, but some bots try to do that.
I have error reporting via eMail enabled and recently i get a lot of this errors in my inbox.
I tried to reproduce it, and also Mezzanine Page is affected. see: http://mezzanine.jupo.org/comment/

IMHO accessing /comments/ via get should return an "**HTTP 405**    Method Not Allowed" Error.

btw: thank you for your great work on mezzanine.

**Comment by mikeredbike** [comment]
I was getting the same thing when the crawler was looking for /rating/.  I suggest changing get_model on line 33 of mezzanine/utils/models.py to:
def get_model(app_label, model_name=None):          
    if model_name is None:                          
        if len(app_label.split('.')) != 2:          
            raise LookupError                       
        app_label, model_name = app_label.split('.')
    model = django_get_model(app_label, model_name) 
    if not model:                                   
        raise LookupError                           
    return model
