### ISSUE TITLE
Brocken links to images in RSS/Atom feeds

### ISSUE THREAD

**Issue by noisy** [stephenmcd/mezzanine#1193]
Be default all links to uploaded images are relative. Of course this works on blog, bug this cause a lot of problems with RSS/Atom feeds.

If someone use local RSS reader, then all link are poining to `localhost/static/media/...`. If someone use online reader like http://www.g2reader.com/, then links are poining to that domain:

![](http://i.imgur.com/MuyazjA.png)

![](http://i.imgur.com/irgBk5B.png)

**Comment by stephenmcd** [comment]
I'd argue that's a very poor RSS reader :-) I've built a commercial RSS reader and relative URLs in feeds are *extremely* common. 

Anyway that doesn't mean we can't fix it in Mezzanine too, I've a patch incoming. Thanks for raising this.

**Comment by noisy** [comment]
@stephenmcd how this will now behave if I want to move my blog to another domain? Are proper links generated on each request, or only once?
