### ISSUE TITLE
Settings.use_editable()

### ISSUE THREAD

**Issue by sreedharbukya** [stephenmcd/mezzanine#1211]
Is it compulsory to use settings.use_editable() in my view for  customized admin register_setting

Why do we need to flush the db cache to pick up new settings ?
I think it should automatically pick up the new settings without me mentioning it in my view. 

Regards, 

Sreedhar

**Comment by stephenmcd** [comment]
Please post this to the mailing list, thanks.

**Comment by sreedharbukya** [comment]
Thanks for your reply , Posted to mailing list

regards, 
Sreedhar
