### ISSUE TITLE
Add configuration option to specify new account verification link redirect URL

### ISSUE THREAD

**Issue by hypertexthero** [stephenmcd/mezzanine#1213]
The ability to specify a custom URL to redirect people to after they click on verification links would be useful.

Use-case example: Website where user accounts are added manually by an administrator (signup open, but signup page behind login and staff-required). People receive verification link, but are currently redirected to the homepage, whereas ideally they'd be redirected to the `account/update` with a message to set their password.

**Comment by stephenmcd** [comment]
Should be able to do this already by overriding the email template and adding "next=foo" to the url variable in it.

**Comment by hypertexthero** [comment]
Most excellent — thank you!

For reference I modified `templates/email/signup_verify.txt` like so:

    {% trans "Please use the link below to activate it, then set your password in your profile page." %}
    http://{{ request.get_host }}{{ verify_url }}account/update/

And `templates/email/signup_verify.html` like so:

    <p>{% trans "Please use the link below to activate it, then set your password in your profile page." %}</p>
    <p><a href="http://{{ request.get_host }}{{ verify_url }}account/update/">http://{{ request.get_host }}{{ verify_url }}account/update/</a></p>

Is there a way to modify the notification messages that appear in blue boxes such as "Successfully signed up"?

**Comment by rsadwick** [comment]
This question is better suited for the mailing list but I'll try to point you in the correct direction:

If you need to change a message that appears within messages the quickest way is by modifying it at the template level -  templates/base.html and writing a conditional that looks for that specific string and changes the message

```
{% if message.message == "Item added to wishlist" %}
      {{ "Item added to your Favorites" }}
{% elif message.message == "Item removed from wishlist" %}
      {{ "Item removed from your Favorites" }}
```

**Comment by hypertexthero** [comment]
Okay, thanks! I'll go to the mailing list first next time.
