### ISSUE TITLE
Use of RichText model

### ISSUE THREAD

**Issue by MelvinDRM** [stephenmcd/mezzanine#1214]
Hello,

I'm new to Django and therefore to Mezzanine. I'm creating a model and I want to have a RichText field in one of the attributes of the class (code below):

models.py
```javascript
from django.db import models
from mezzanine.pages.models import Page
from mezzanine.core.models import RichText

class KeyDocument(Page):
	pass

class KeyDoc(models.Model):
	ref_page = models.ForeignKey("KeyDocument")
	title = models.CharField("Title*", max_length=1000)
	author = models.CharField("Author(s)*", max_length=1000)
	year = models.PositiveSmallIntegerField("Year*")
	month = models.CharField("Month", max_length=10, null=True, blank=True)
	info = RichText("Additional Information")
	laguange = models.CharField("Language(s)", max_length=100)
	slug = models.SlugField("Slug", max_length=100, null=True, blank=True)

	class Meta:
		ordering = ['-year', 'title']
```

admin.py
```javascript
from copy import deepcopy
from django.contrib import admin
from mezzanine.pages.admin import PageAdmin
from references.models import KeyDocument, KeyDoc

keydoc_extra_fieldsets = ((None, {"fields": ()}),)

class KeyDocInline(admin.TabularInline):
    model = KeyDoc

class KeyDocsAdmin(PageAdmin):
    inlines = (KeyDocInline,)
    fieldsets = deepcopy(PageAdmin.fieldsets) + keydoc_extra_fieldsets

admin.site.register(KeyDocument, KeyDocsAdmin)

admin.site.register(KeyDoc)
```

The result is that the field of Additional Info (which its variable is *info*) is not showing at all.

Can anyone guide me with this?

Thanks in advance

**Comment by stephenmcd** [comment]
Could you post this to the mailing list instead? Thanks!

**Comment by Pomax** [comment]
for people who find this question through google, it's really saddening to see this information having been locked away on a mailing list instead of having an answer associated here =(

**Comment by MelvinDRM** [comment]
Hey Pomax! What's your question?

**Comment by jerivas** [comment]
Link to the mailing list thread for future reference: https://groups.google.com/forum/#!topic/mezzanine-users/ModET8KAQzE

**Comment by Pomax** [comment]
cheers #jerivas, I've asked my question on the google group (not sure mailing list is the right name?)

@MelvinDRM it's basically "I can't figure out how to put rich text fields into a page model", the docs (http://mezzanine.jupo.org/docs/content-architecture.html) don't seem to cover this, and it feels like the kind of thing people who need to customize mezzanine would want to do a lot =)
