### ISSUE TITLE
`set_slug` and other slug-related automatic changes => make optional?

### ISSUE THREAD

**Issue by lajarre** [stephenmcd/mezzanine#1218]
Hi

I wonder if it wouldn't be a good idea to make optional the concept of changing the URLs of related Pages when changing a particular Page.

For `Page.set_slug` I think of something like:

    def set_slug(self, new_slug):
        """
        Changes this page's slug (and all other pages whose slugs
        start with this page's slug if `settings.AUTO_PAGE_SLUGS`).
        """
        if settings.AUTO_PAGE_SLUGS:
            slug_prefix = "%s/" % self.slug
            for page in Page.objects.filter(slug__startswith=slug_prefix):
                if not page.overridden():
                    page.slug = new_slug + page.slug[len(self.slug):]
                    page.save()
        self.slug = new_slug
        self.save()

Same would go for `set_parent` notably.

For my website I am going to remove this feature by changing the Page class, because it is confusing admin people too much.

Happy to hear feedback and suggest a pull request if makes sense.

**Comment by stephenmcd** [comment]
I think it's too much of an edge case to warrant the overhead of Adding Another Setting, sorry.

Surprised to hear people find it confusing - my experience is the opposite behaviour is very unexpected.

Thanks anyway.

**Comment by lajarre** [comment]
Alright. Indeed my setup is much customised so more side-effects are related to that.

Apart from that, wouldn't it be more coherent to use the following query in `set_slug`: `Page.objects.filter(parent_id=self.id, slug__startswith=slug)`, and then use `set_slug` recursively?

**Comment by stephenmcd** [comment]
That'd require almost double the number of database queries.
