### ISSUE TITLE
settings.use_editable() and comma-separated strings

### ISSUE THREAD

**Issue by lajarre** [stephenmcd/mezzanine#1222]
I understood after getting some bugs that after `settings.use_editable()` is used and the database is set, the returned value of an editable setting can be of class `future.builtins.backports.newbytes.newbytes`.

FYI, my setting is a whitelist of IP addresses in the form `'1.2.3.4, 2.3.2.4, 3.4.23.21'`.

But my tests didn't figure it out by themselves (if was using the editable setting in my `unittest.TestCase.setUpClass` method).

I guess things would be more coherent if `mezzanine.conf.settings.__getattr__` would always return the same construct when it's fetched from the database or not. Notably so it makes code more consistent when run by different runners (django server vs tests).

Makes sense, isn't it?

--

NB: I'm still running 3.1.4

**Comment by stephenmcd** [comment]
The return type will be the same as the default value you define when registering the setting.

I get a str object back with a value retrieved from the database. 

If you think there's an actual issue, please provide steps to reproduce it.

**Comment by lajarre** [comment]
Steps:

- Add to a defaults.py:

```
register_setting(
    name="ALLOWED_IPS",
    description=u"IPs list",
    editable=True,
    default="1.1.1.1, 2.2.2.2, 3.3.3.3",
)
```

- Launch server

- Open `./manage.py shell`

```
from mezzanine.conf import settings

print(settings.ALLOWED_IPS.__class__)

settings.use_editable()
print(settings.ALLOWED_IPS.__class__)  # Gives the abovementioned class: newbytes
```

On top of that, depending on my server, there can be some brackets that get appended and prepended to the string value. It doesn't seem like I am using any customisation of this part of mezzanine, but will check again.

**Comment by stephenmcd** [comment]
I don't get those results.
