### ISSUE TITLE
south: Unknown command: 'migrate' bug

### ISSUE THREAD

**Issue by okrutny** [stephenmcd/mezzanine#1226]
I updated Mezzanine version from 3.0.4 to 3.1.10. After doing this, command: python manage.py migrate returns "Unknown command: 'migrate'". South is installed and in INSTALLED_APPS of course. The only things I did to test that was to create virtualenvs and installed requirements.txt with Mezzanine==3.1.10 to one of them and Mezzanine==3.0.4 to the other one. The virtualenv with older Mezzanine version has no issues when I run python manage.py migrate, while the newest one returns error like in the topic.

output for Mezzanine 3.0.4 and Django 1.6.10:

	(cs-mz-3.0.4)some_user@ubuntu:~/pycharmProjects/some-project/some-project$ pip freeze
	Django==1.6.10
	Mezzanine==3.0.4
	Pillow==2.7.0
	South==1.0.2
	argparse==1.2.1
	bleach==1.4.1
	boto==2.36.0
	distribute==0.6.24
	django-dbbackup==1.80.2
	django-debug-toolbar==1.3.0
	dropbox==2.2.0
	filebrowser-safe==0.3.8
	future==0.9.0
	grappelli-safe==0.3.13
	html5lib==0.95
	oauthlib==0.7.2
	psycopg2==2.6
	pytz==2014.10
	requests==1.2.3
	requests-oauthlib==0.3.3
	six==1.9.0
	sqlparse==0.1.14
	urllib3==1.10.2
	wsgiref==0.1.2
	(cs-mz-3.0.4)some_user@ubuntu:~/pycharmProjects/some-project/some-project$ ./manage.py migrate
	Traceback (most recent call last):
	  File "./manage.py", line 28, in <module>
		execute_from_command_line(sys.argv)
		# Some other error related to not satisfied dependencies

output for Mezzanine 3.1.10 and Django 1.6.10:
	
	(cs-mz-3.1.10)some_user@ubuntu:~/pycharmProjects/some-project/some-project$ pip freeze
	Django==1.6.10
	Mezzanine==3.1.10
	Pillow==2.7.0
	South==1.0.2
	argparse==1.2.1
	beautifulsoup4==4.1.3
	bleach==1.4.1
	boto==2.36.0
	distribute==0.6.24
	django-dbbackup==1.80.2
	django-debug-toolbar==1.3.0
	dropbox==2.2.0
	filebrowser-safe==0.3.8
	future==0.9.0
	grappelli-safe==0.3.13
	html5lib==1.0b3
	oauthlib==0.7.2
	psycopg2==2.6
	pytz==2014.10
	requests==2.5.3
	requests-oauthlib==0.4.2
	six==1.9.0
	sqlparse==0.1.14
	tzlocal==1.0
	urllib3==1.10.2
	wsgiref==0.1.2
	(cs-mz-3.1.10)some_user@ubuntu:~/pycharmProjects/some-project/some-project$ ./manage.py migrate
	Unknown command: 'migrate'
	Type 'manage.py help' for usage.
	(cs-mz-3.1.10)some_user@ubuntu:~/pycharmProjects/some-project/some-project$ 

output for Mezzanine 3.1.9 and Django 1.6.10:
	
	(cs-mz-3.1.9)some_user@ubuntu:~/pycharmProjects/some-project/some-project$ pip freeze
	Django==1.6.10
	Mezzanine==3.1.9
	Pillow==2.7.0
	South==1.0.2
	argparse==1.2.1
	beautifulsoup4==4.1.3
	bleach==1.4.1
	boto==2.36.0
	distribute==0.6.24
	django-dbbackup==1.80.2
	django-debug-toolbar==1.3.0
	dropbox==2.2.0
	filebrowser-safe==0.3.8
	future==0.9.0
	grappelli-safe==0.3.13
	html5lib==1.0b3
	oauthlib==0.7.2
	psycopg2==2.6
	pytz==2014.10
	requests==2.5.3
	requests-oauthlib==0.4.2
	six==1.9.0
	sqlparse==0.1.14
	tzlocal==1.0
	urllib3==1.10.2
	wsgiref==0.1.2
	(cs-mz-3.1.9)some_user@ubuntu:~/pycharmProjects/some-project/some-project$ ./manage.py migrate
	Traceback (most recent call last):
	  File "./manage.py", line 28, in <module>
		execute_from_command_line(sys.argv)
		# Some other error related to not satisfied dependencies

**Comment by stephenmcd** [comment]
Unfortunately that error could basically mean any number of things going wrong. Please reopen the issue if you have anything more conclusive.

**Comment by okrutny** [comment]
I would appreciate that if you give me a hint how I can be more conclusive. Regards.

**Comment by AlexHill** [comment]
Hi @okrutny. Before anyone can fix the problem they need to be able to reproduce it. Start with an empty virtual environment, and add things until you find the thing that's causing the problem, then post the steps you took here.

``migrate`` isn't broken in a vanilla install of Mezzanine, so the problem must be triggered by an interaction with another package or some of your code. Try to work out what that trigger is.
