### ISSUE TITLE
Reverse for 'password_reset' with arguments '()'

### ISSUE THREAD

**Issue by ZobairAlijan** [stephenmcd/mezzanine#1227]
Hi,
I got this issue "Reverse for 'password_reset' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []" without doing anything. I only work on making dynamic pages which I do not deal with password/password reset. I took a break and when I came-back to create another dynamic page in admin section, I end it up getting the above error. I removed my db and re-installed, got same problem. I also uninstalled Mezzanine and re-installed, same issue. any idea? Please see attached file. Thank you
![bug](https://cloud.githubusercontent.com/assets/9525062/6625922/98956472-c8c9-11e4-8d74-bc7d9ff853e2.png)

**Comment by stephenmcd** [comment]
There's not enough information here to help you unfortunately. Can you provide more detail? How did you install everything? What else?

**Comment by stephenmcd** [comment]
Actually I'm confident this isn't a bug - that url resolve failure is usually a symptom of a deeper problem further up. Can I suggest posting this question to the mailing list instead of it you can't work it out? Thanks.

**Comment by ZobairAlijan** [comment]
Thank you so much for the response. You are right, it wasn't a bug, It was something wrong with my url (I misplaced the pattern). I'm new to Mezzanine. Thank you

**Comment by stephenmcd** [comment]
No problem, glad you worked it out.
