### ISSUE TITLE
Missing Translation in German (de) django.po for search "Everything"

### ISSUE THREAD

**Issue by christianwgd** [stephenmcd/mezzanine#1242]
The po-File in mezzanine/core/locale/de lacks the translation for the word "Everything" in search-form.html.

I have added the German word "Alles" in my po-File. 

Christian

**Comment by christianwgd** [comment]
I added some more translations (found/not found messages after search). I could provide those mo/po, if someone is interested.

Christian

**Comment by stephenmcd** [comment]
Could you create a pull request with the new files? Thanks
