### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by nyov** [stephenmcd/mezzanine#1249]
Would you mind polishing the current code for a new pypi release?
The last version tag is from 08.2014 (364900650a15b3d62a9add66f7a14ef29d2ed673) and depends on `django!=1.6.0,<1.7,>=1.4.10`, while current issues here are talking about django 1.8 compatibility. Thanks.

**Comment by nyov** [comment]
On another note, you seem to have a lot of merged branch heads still hanging around. Pruning those would be nice.

**Comment by AlexHill** [comment]
Hi @nyov, there's active discussion of the next release in this mailing list thread: https://groups.google.com/forum/#!topic/mezzanine-users/_QWfFVB3RVc

**Comment by nyov** [comment]
Ah, my apologies for not looking that far afield. I will be waiting patiently. Thanks.
