### ISSUE TITLE
Update project layout to match Django

### ISSUE THREAD

**Issue by AlexHill** [stephenmcd/mezzanine#1250]
In the spirit of "Mezzanine is just Django" I think we should update the project layout to match Django's default, and go through the project template's settings.py to see if any of the Django defaults need updating.

I'm volunteering to do the work; just opening the issue here to get consensus.

**Comment by stephenmcd** [comment]
Thanks Alex - please go right ahead!

**Comment by jerivas** [comment]
+1 on this one! Remember the fabfile, wsgi.py, and the files inside deploy/ (because they make assumptions regarding the project layout). I can help you out with that once you're done with the general refactoring if you like :)

**Comment by AlexHill** [comment]
Great, I'll try to get to this tonight.

**Comment by AlexHill** [comment]
That didn't happen - but I'll put aside some time over the weekend to do this. I think it would be good to get it in before the 1.8 release.

**Comment by stephenmcd** [comment]
No worries, thanks a lot! I'll be travelling back to AU over the next couple of days, so at this stage the release probably wouldn't be until early next week at the absolute earliest anyway, so no rush.

**Comment by AlexHill** [comment]
OK, I'm in the middle of working on this now.

The new project layout requires replacing placeholders in path names: settings.py, urls.py etc live in a ``project_directory/<project_name>/``.

Since version 1.4, Django has [built in project template functionality](https://docs.djangoproject.com/en/1.4/releases/1.4/#custom-project-and-app-templates) which we can work on top of, and in doing so replace most of ``mezzanine_project.py`` with calls to the Django code.

Django's [startproject](https://github.com/django/django/blob/master/django/core/management/commands/startproject.py) source and the superclass [TemplateCommand](https://github.com/django/django/blob/master/django/core/management/templates.py#L25) are worth reading.

 Two problems that I can see with this:

* Django doesn't support overlaying multiple templates as we do when creating Cartridge projects. A couple of ways around this:
 * Use Django to generate project directories for the Mezzanine and Cartridge project templates in turn, then manually merge them.
 * Just ship a complete project template with Cartridge.

* Running mezzanine tests from the template directory won't work without making some changes.

The other alternative is to add code to mezzanine_project.py to support placeholders in paths, instead of using Django's machinery. But I really feel the better option would be to change what we need to in order to standardise and make use of what Django provides.

**Comment by AlexHill** [comment]
For now, I'm just going to update mezzanine_project.py so that we can at least get the basic directory structure updated, and look at making the other changes later.

**Comment by stephenmcd** [comment]
Thanks for the update Alex - I'd the same plan of one day replacing mezzanine-project with Django's new (now old) project template support, but like you said baby steps would be fine too.

Not too attached to Mezzanine's multi-project-template thing either, I think Cartridge is the only thing that ever leveraged that, and like you said things would be less complex if it just had its own entire project template.

**Comment by AlexHill** [comment]
Cool that makes things easier. It actually looks like it will be easier to update to use the Django stuff than change mezzanine_project.py anyway: since so much lives in the project app, all that stuff needs to be templated, and that's all provided for in the default Django project template.

**Comment by stephenmcd** [comment]
Awesome! Another thing we'll need to at least verify still works is the built-in fabfile. Hopefully it just works out of the box, but might need some minor tweaks for the new layout. It's a bit involved if you haven't used it before (setting up a virtual machine etc) so I'll take a look at that - just wanted to make note of it.

**Comment by AlexHill** [comment]
Yep - some of the paths will need to be changed at the very least.

[This is the default Django project template.](https://github.com/django/django/tree/master/django/conf/project_template/) I'm planning to put the fabfile into the project root, and the ``deploy`` directory inside the ``project_name`` directory (which gets be renamed to the actual project name). Does that sound reasonable?

**Comment by stephenmcd** [comment]
I wonder if the deploy directory should go in the project root too? Not sure.

**Comment by stephenmcd** [comment]
Like technically manage.py, fabfile.py and "deploy" dir don't get "deployed".

**Comment by stephenmcd** [comment]
Eg they're tools, not part of the Python package that gets created inside the project root.

**Comment by AlexHill** [comment]
Sounds good to me, I'll go with that.

**Comment by AlexHill** [comment]
See patch in #1265.

**Comment by stephenmcd** [comment]
Closed by #1256

**Comment by yltang52** [comment]
I really look forward to this to happen. Is there any eta?

**Comment by AlexHill** [comment]
As soon as we have time to finalise a release which should be very soon.

That said, the new project layout patch has been merged so if you are comfortable using this repository's master branch, you can use it today.

**Comment by yltang52** [comment]
Great, where should I download the hottest versions?

**Comment by yltang52** [comment]
Sorry, that was a dumb question. I mean how do I install the particular version into the virtual environment?

**Comment by AlexHill** [comment]
Probably the simplest way is to do:

``pip install https://github.com/stephenmcd/mezzanine/archive/master.zip``

I think you can also add an URL to a zip file to your requirements.txt and it will work out.

Alternative you can install directly from git: ``pip install git+https://github.com/stephenmcd/mezzanine.git#egg=Mezzanine``

Bear in mind that the latest version requires at least Django 1.7. Good luck!

**Comment by yltang52** [comment]
Many thanks. I'll give it a try.

**Comment by yltang52** [comment]
I used to deploy Mezzanine on Heroku. In that case, how do I specify the version in the "requirements.txt"?

**Comment by AlexHill** [comment]
I think simply putting ``https://github.com/stephenmcd/mezzanine/archive/master.zip`` in your requirements.txt will work. You won't be able to specify the version – every time you install requirements pip will just download the latest master.

Alternatively you can pin to a specific commit with a requirements line like this:

```
-e git+https://github.com/stephenmcd/mezzanine.git@1dd34e4336c4d66c37d3a5922e9d4f64c6312d98#egg=Mezzanine
```

**Comment by yltang52** [comment]
Tried to deploy the newest version of Mezzanine on Heroku, and it worked!
Thanks a million, Alex.

**Comment by AlexHill** [comment]
My pleasure. Keep an eye out for the official release.

**Comment by yltang52** [comment]
Uhhhhh, tinymce seems not ready yet.

**Comment by yltang52** [comment]
Is there any version already having TinyMCE 4? It's kind of urgent. My customer's site is unable to edit anything in the admin page :-(

**Comment by yltang52** [comment]
Sorry, my bad. I found the TinyMCE editor; it is just one click away.

**Comment by yltang52** [comment]
TinyMCE really isn't there. Any update?

**Comment by Kniyl** [comment]
You probably missed the answer from #1336
