### ISSUE TITLE
Mezzanine Does not support nested_inline?

### ISSUE THREAD

**Issue by ZobairAlijan** [stephenmcd/mezzanine#1254]
Hi Steven,
In django 1.7, django-nested-inline works perfectly and I can create as many collapsible entries as I want but in Mezzanine it doesn't(I even installed the latest Mezzanine that now supports django 1.7-1.8). I ended up getting a blank page(see attached files please) I'm referring to https://github.com/s-block/django-nested-inline. Is there going to be any support in near future for Mezzanine to support django-nested-inline? I use django 1.7.5 right now since django 1.8 is brand new to some apps. Thank you

![django](https://cloud.githubusercontent.com/assets/9525062/7033675/d42e16b6-dd49-11e4-8f51-01699205a29c.png)
![mezzanine](https://cloud.githubusercontent.com/assets/9525062/7033682/e14d5d3e-dd49-11e4-9ab7-9ba1a8998da9.png)

**Comment by stephenmcd** [comment]
Feel free to get this working if you need to, but it's not really a priority sorry.
