### ISSUE TITLE
django-contrib-comments is not ready for Django 1.8

### ISSUE THREAD

**Issue by jerivas** [stephenmcd/mezzanine#1255]
I've done more testing with Django 1.8, and I've hit an error when using Postgres databases (you won't see it with SQLite, and I can't comment on MySQL): The problem arises when `createdb` runs `migrate`.

`django-contrib-comments` seems to be the offender so I went ahead and created a project with it in vanilla Django 1.8, and I get the same error when running `migrate`. So yeah, this is an upstream issue and [I have reported it over there](https://github.com/django/django-contrib-comments/issues/30). I'm opening it here to start discussion on how to proceed, as this might be a release blocker, and raise awareness in case we can contribute an upstream fix (which would be awesome!).

**Comment by jerivas** [comment]
Well, installing the master branch of `django-contrib-comments` fixes the issue, so it's just a matter of them updating the version available through Pypi.

**Comment by stephenmcd** [comment]
Thanks for tracking this down Ed.

**Comment by fedelibre** [comment]
thanks @jerivas, I was stuck on this problem
are you sure that they will update it soon? it seems that [last upload was on March 2013](https://pypi.python.org/pypi/django-contrib-comments)?

**Comment by jerivas** [comment]
The pypi package was updated in March 2013, but the repo has activity as far as November 2014. Guess we'll have to wait and see, but we can ask about it in the upstream issue. I asked the top contributor about it on Twitter; awaiting for an answer :P

**Comment by AlexHill** [comment]
This is an ex-contrib package hosted under the official Django banner, so I'm certain it will get updated. We won't be the only ones who need to use this now that it's been dropped from django.contrib.

**Comment by zemogle** [comment]
It looks like PyPi had a new version on [25 April 2015](https://pypi.python.org/pypi/django-contrib-comments).

**Comment by stephenmcd** [comment]
Reopening pending https://github.com/django/django-contrib-comments/pull/40
