### ISSUE TITLE
overextends tag broken in Django 1.7+1.8

### ISSUE THREAD

**Issue by stephenmcd** [stephenmcd/mezzanine#1258]
Looks like the changes made to ``loader_tags.py`` in a50de50699bb6a24bfb5f118449991aa7608b426 either didn't work or both Django versions have since changed.

As reported here: https://groups.google.com/d/msg/mezzanine-users/_QWfFVB3RVc/ZirizEV9t2YJ

Just pinging @AlexHill as you might have a head's up on this one already. 

I made a quick attempt by changing ``find_template_loader = context.engine.find_template_loader`` to ``find_template_loader = context.engine.find_template_loader`` which appears to work for 1.8, but then other possibly unrelated exceptions came up.

BTW my quick tip for actually running ``overextends`` is to modify the first line of `core/templates/admin/base_site.html` to use it instead of ``extends``

**Comment by AlexHill** [comment]
I can see a typo there for 1.7: on line 62 refers to ``django.template.loaders`` when it looks like it should refer to ``django.template.loader``. Not sure why that line is being executed under 1.8 at all though, since it should find the method on ``context.engine`` - certainly possible that there were changes to 1.8 since I wrote that code. Will have a look.

**Comment by AlexHill** [comment]
Ok looks like ``engine`` is not available on the context now but rather ``context.template``. Looking at your post I'm guessing that's what you meant.

This allows me to use overextends in 1.7 and 1.8: https://github.com/AlexHill/mezzanine/commit/b94ab99fa88a2bcf6850ed91f98a8a06f494febf

Sorry for being so haphazard with that last commit. From memory, I ran into these template changes in DjPj and naively copied the fixes over without actually testing the functionality. I guess a test to at least ensure the templatetag can be used without raising an exception is in order.

**Comment by stephenmcd** [comment]
No problem at all, happens to me all the time.

Could you throw that commit into a PR?

Thanks a lot Alex!

**Comment by stephenmcd** [comment]
Well, I mean I do it myself all the time. :-)

**Comment by AlexHill** [comment]
Done
