### ISSUE TITLE
django-modeltranslation is not ready for Django 1.8

### ISSUE THREAD

**Issue by Kniyl** [stephenmcd/mezzanine#1261]
In the same vein as #1255, I’m opening this issue to warn people about django-modeltranslation not being fully compatible with Django 1.8 yet.

They’re on it (as per deschler/django-modeltranslation#295 and deschler/django-modeltranslation#299) but it is possible that it won't be ready for the release.

**Comment by stephenmcd** [comment]
Thanks for the news - I guess in the worse case we could do a release supporting 1.8, but just build in some hooks to prevent modeltranslation and/or comments from being used.

**Comment by Kniyl** [comment]
Something along the lines of https://gist.github.com/Kniyl/8b7822cfa25eb20458cf ?

**Comment by stephenmcd** [comment]
Sure - we could even throw a nicely worded exception message to clearly let them know what they need to do.

But hopefully we won't need this, let's just hang tight for a bit.

**Comment by orotau** [comment]
looks like they have released the 1.8 compatible version...

**Comment by stephenmcd** [comment]
Awesome, thanks for the update!
