### ISSUE TITLE
using metadata keyword crashes

### ISSUE THREAD

**Issue by allenwooky** [stephenmcd/mezzanine#1263]
In writing a blog post when I expand the metadata section to input keyword and then view on site it produces the following error:

AttributeError at /blog/test-blog-post/
type object 'Decimal' has no attribute 'from_float'
Request Method:	GET
Request URL:	http://net-weave.com:8000/blog/test-blog-post/
Django Version:	1.6.11
Exception Type:	AttributeError
Exception Value:	
type object 'Decimal' has no attribute 'from_float'
Exception Location:	/home/netweave/mezzenv/lib/python2.6/site-packages/future/builtins/backports/newround.py in newround, line 32
Python Executable:	/home/netweave/mezzenv/bin/python
Python Version:	2.6.6
Python Path:	
['/home/netweave/domains/net-weave.com/public_html/sebarcms',
 '/home/netweave/mezzenv/lib64/python26.zip',
 '/home/netweave/mezzenv/lib64/python2.6',
 '/home/netweave/mezzenv/lib64/python2.6/plat-linux2',
 '/home/netweave/mezzenv/lib64/python2.6/lib-tk',
 '/home/netweave/mezzenv/lib64/python2.6/lib-old',
 '/home/netweave/mezzenv/lib64/python2.6/lib-dynload',
 '/usr/lib64/python2.6',
 '/usr/lib/python2.6',
 '/home/netweave/mezzenv/lib/python2.6/site-packages',
 u'/home/netweave/domains/net-weave.com/public_html']
Server time:	Sun, 12 Apr 2015 00:59:02 +0800

**Comment by stephenmcd** [comment]
Can you post the full traceback
