### ISSUE TITLE
WYSIWYG does not strip out line breaks, causing blog post borkage

### ISSUE THREAD

**Issue by DanielLoeb** [stephenmcd/mezzanine#1267]
So I'm working with the WYSIWYG in Mezzanine 3.1.10 writing blog posts. I've noticed that copying text from outside the webbrowser and pasting it into the editor window will cause random vertical whitespace that does _not_ show in the WYSIWYG editor itself, but does show in the published post.

After some experimenting, I've found that the problem seems to be that the WYSIWYG replaces line breaks in copy/pasted text with \<br /\>. Since the editor itself places \<p\> tags to manage paragraphs, these \<br /\> tags will cause vertical whitespace to appear randomly.

Here is an example. I've written the "test" lines in the WYSIWYG editor and pasted in the "toast" lines from kate.

This is the HTML that is saved:
> \<p\>testtesttest\</p\>
> \<p\>\</p\>
> \<p\>testtest\</p\>
>  \<p\>\</p\>
> \<p\>toasttoasttoast\<br /\>\<br /\>toast\<br /\>\<br /\>\</p\>

When rendered, this will cause vertical whitespace in unwanted places somewhere in the blogpost (mostly near images and tables). Removing the \<br /\> tags fixes this.

 IMO a solution would require to strip out all line breaks and replace them either with a paragraph tag or with \&#10;. Recognizing when exactly it should be paragraphs and when it should be \&#10; is probably not quite as trivial as it seems at first.

**Comment by stephenmcd** [comment]
Don't think there's really an issue to address here. As far as I see it's a difference in the stylesheets used in the admin and the default front-end site, which you're expected to customise.

Thanks

**Comment by jerivas** [comment]
Hi Daniel, you may want to check this out: http://stackoverflow.com/questions/17058644/remove-the-extra-p-tag-in-tinymce.
I suggest you take a look at the TinyMCE docs to find configuration options that work for you, as overriding the default Mezzanine implementation is very easy.

**Comment by DanielLoeb** [comment]
Thank you both for your suggestions. I'll dig into the docs and the stylesheets to see which option is the easiest one for me to work with.

Best regards and thanks again,
Daniel
