### ISSUE TITLE
Needs Right-to-Left Alignment Support

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [stephenmcd/mezzanine#1268]
[Demo RTL with some LTR Text in a Blog Post](http://mezzanine.jupo.org/blog/%D9%87%D9%84-%D8%A3%D8%B3%D8%AA%D8%B7%D9%8A%D8%B9-%D8%A7%D9%84%D9%83%D8%AA%D8%A7%D8%A8%D8%A9-%D8%A8%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A/)

Here's a demo blog in Arabic (RTL Language). It's displayed LTR which breaks punctuation and numbers. It also makes text unreadable (due to alignment) when using Arabic with LTR language (like English), which is common since RTL writers tend to refer to some concepts in their original names along with the translated name of the concept, since the language of science is currently English (LTR).

**Comment by orotau** [comment]
Hello sir
My understanding is that this is an issue with the tinymce plugin version
You may wish to look at this thread 
http://www.tinymce.com/forum/viewtopic.php?id=32748
Regards
Graham

On 15/04/15 23:00, BoringUserWhoCantCode wrote:
>
> Demo RTL with some LTR Text in a Blog Post 
> <http://mezzanine.jupo.org/blog/%D9%87%D9%84-%D8%A3%D8%B3%D8%AA%D8%B7%D9%8A%D8%B9-%D8%A7%D9%84%D9%83%D8%AA%D8%A7%D8%A8%D8%A9-%D8%A8%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A/>
>
> Here's a demo blog in Arabic (RTL Language). It's displayed LTR which 
> breaks punctuation and numbers. It also makes text unreadable (due to 
> alignment) when using Arabic with LTR language (like English), which 
> is common since RTL writers tend to refer to some concepts in their 
> original names along with the translated name of the concept as the 
> language of science is currently English.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/stephenmcd/mezzanine/issues/1268>.
>

-- 
T : 021 081 71732

**Comment by stephenmcd** [comment]
What you'd need to do in this case is add the relevant RTL styles to your front-end templates.

**Comment by jerivas** [comment]
Hmm, I think this is related. The [base template](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/templates/base.html#L22-L24) suggest Mezzanine includes an RTL stylesheet, but I cannot find it anywhere in the repo; only [one for the admin site](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/static/mezzanine/css/admin/rtl.css).

**Comment by stephenmcd** [comment]
Hey Ed you're right. I don't know how that got there, I can only guess the intention was that you're expected to add that file yourself should you need it. I guess we could provide one by default for the bootstrap theme.

**Comment by jerivas** [comment]
A quick search rendered this: https://github.com/morteza/bootstrap-rtl/blob/master/dist/css/bootstrap-rtl.css

**Comment by stephenmcd** [comment]
Nice! I'll just drop it in verbatim. 

I've worked on sites that dynamically switch between LTR/RTL before, and from what I understand it shouldn't be switched entirely across the whole web-page. Eg some parts should always read LTR regardless of language, and only main sections of content should switch.

So given that, I don't think it will be an absolutely correct solution, but it will be a good start anyway.

**Comment by stephenmcd** [comment]
What becomes interesting now is the multi-lingual support - that template switch is based on a static setting, when it really should be dynamic given the current language. Not sure what the solution is there.

**Comment by stephenmcd** [comment]
http://cl.ly/afv3

**Comment by jerivas** [comment]
Hehe, you should do that for next April Fools in the demo site ;)

Regarding getting the correct value for `LANGUAGE_BIDI`, the [Django docs](https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#other-tags) say: "If you enable the `django.template.context_processors.i18n` context processor then each `RequestContext` will have access to `LANGUAGES`, `LANGUAGE_CODE`, and `LANGUAGE_BIDI`."

So in theory we should be in the clear, as that context processor is part of the project template.
