### ISSUE TITLE
The default value for `login_required` should be a configuration variable in `settings.py`

### ISSUE THREAD

**Issue by bondgeek** [stephenmcd/mezzanine#1273]
It would seem that if someone wanted to use the field, and wanted to set it to True, a user oversight leaving it unchecked would be a big deal.

**Comment by stephenmcd** [comment]
Thanks for the suggestion!

I don't think it would make much sense - if the bulk of your pages required an authenticated user a better solution would be to use some kind of middleware that does it site-wide.

We also need to scrutinize adding any new settings - if we made the default values for each and every field configurable by a setting, there'd just be far too many.

BTW suggestions like this a better off discussed first on the mailing list, no need to open an issue for it.
