### ISSUE TITLE
Consider optional initialization args for default richtext widget

### ISSUE THREAD

**Issue by dinopetrone** [stephenmcd/mezzanine#1277]
https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/fields.py#L57

Would be helpful to override some features in a third party rich text widget, to do this i would need access to pass initialization options:

`kwargs["widget"] = widget_class(settings.RICHTEXT_WIDGET_OPTIONS)`

Something like that possibely?

**Comment by stephenmcd** [comment]
Don't think it warrants a new setting since you could just implement the options inside your class.

Thanks anyway.
