### ISSUE TITLE
pep8 1.6.2 fails built-in unit tests

### ISSUE THREAD

**Issue by josephtoles** [stephenmcd/mezzanine#1281]
According to setup.py (https://github.com/stephenmcd/mezzanine/blob/master/setup.py), Mezzanine's unit tests require package pep8>=1.4.1. The unit tests function properly when you install pep8==1.4.1. However running unit tests with pep8==1.6.2 causes a unit test failure. Am I using this correctly? It seems like Mezzanine should be configured to comply with pep8==1.6.2, or the requirements should be changed to be more restrictive.

**Comment by josephtoles** [comment]
Unit test error from running pep8==1.6.2

======================================================================
FAIL: test_syntax (mezzanine.core.tests.CoreTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/admin/.virtualenvs/mezzanine/lib/python2.7/site-packages/mezzanine/core/tests.py", line 72, in test_syntax
    self.fail("Syntax warnings!\n\n%s" % "\n".join(warnings))
AssertionError: Syntax warnings!

mezzanine/accounts/forms.py:221: visually indented line with same indent as next logical line
mezzanine/bin/mezzanine_project.py:68: do not assign a lambda expression, use a def
mezzanine/blog/management/commands/import_blogger.py:57: block comment should start with '# '
mezzanine/blog/management/commands/import_blogger.py:61: block comment should start with '# '
mezzanine/blog/management/commands/import_blogger.py:76: block comment should start with '# '
mezzanine/blog/management/commands/import_rss.py:56: visually indented line with same indent as next logical line
mezzanine/blog/templatetags/blog_tags.py:69: do not assign a lambda expression, use a def
mezzanine/conf/__init__.py:200: do not assign a lambda expression, use a def
mezzanine/conf/forms.py:55: do not assign a lambda expression, use a def
mezzanine/core/managers.py:83: too many leading '#' for block comment
mezzanine/core/managers.py:92: too many leading '#' for block comment
mezzanine/core/managers.py:110: do not assign a lambda expression, use a def
mezzanine/core/managers.py:124: too many leading '#' for block comment
mezzanine/core/middleware.py:164: do not assign a lambda expression, use a def
mezzanine/core/middleware.py:214: visually indented line with same indent as next logical line
mezzanine/core/tests.py:295: too many leading '#' for block comment
mezzanine/core/tests.py:305: too many leading '#' for block comment
mezzanine/core/tests.py:318: too many leading '#' for block comment
mezzanine/core/views.py:142: do not assign a lambda expression, use a def
mezzanine/core/views.py:182: do not assign a lambda expression, use a def
mezzanine/core/views.py:184: do not assign a lambda expression, use a def
mezzanine/core/management/commands/collecttemplates.py:34: do not assign a lambda expression, use a def
mezzanine/core/templatetags/mezzanine_tags.py:590: do not assign a lambda expression, use a def
mezzanine/forms/admin.py:108: do not assign a lambda expression, use a def
mezzanine/forms/fields.py:85: do not assign a lambda expression, use a def
mezzanine/forms/forms.py:198: visually indented line with same indent as next logical line
mezzanine/pages/fields.py:23: do not assign a lambda expression, use a def
mezzanine/pages/managers.py:27: visually indented line with same indent as next logical line
mezzanine/pages/models.py:138: do not assign a lambda expression, use a def
mezzanine/pages/tests.py:145: test for membership should be 'not in'
mezzanine/pages/templatetags/pages_tags.py:51: do not assign a lambda expression, use a def
mezzanine/pages/templatetags/pages_tags.py:52: do not assign a lambda expression, use a def
mezzanine/project_template/fabfile.py:129: do not assign a lambda expression, use a def
mezzanine/project_template/fabfile.py:233: do not assign a lambda expression, use a def
mezzanine/project_template/settings.py:116: do not assign a lambda expression, use a def
mezzanine/project_template/settings.py:187: module level import not at top of file
mezzanine/project_template/settings.py:251: block comment should start with '# '
mezzanine/project_template/settings.py:252: block comment should start with '# '
mezzanine/project_template/wsgi.py:9: module level import not at top of file
mezzanine/utils/conf.py:40: do not assign a lambda expression, use a def
mezzanine/utils/conf.py:42: do not assign a lambda expression, use a def
mezzanine/utils/conf.py:44: do not assign a lambda expression, use a def
mezzanine/utils/conf.py:46: do not assign a lambda expression, use a def
mezzanine/utils/docs.py:94: do not assign a lambda expression, use a def
mezzanine/utils/docs.py:154: line break before binary operator
mezzanine/utils/docs.py:154: visually indented line with same indent as next logical line
mezzanine/utils/docs.py:199: visually indented line with same indent as next logical line
mezzanine/utils/email.py:57: do not assign a lambda expression, use a def
mezzanine/utils/models.py:224: do not assign a lambda expression, use a def
mezzanine/utils/tests.py:142: line break before binary operator
mezzanine/utils/tests.py:142: visually indented line with same indent as next logical line

**Comment by stephenmcd** [comment]
Thanks for the report - I presume you're using the current release as I believe these issues are already resolved in the development branch.
