### ISSUE TITLE
Deletion of duplicate comments

### ISSUE THREAD

**Issue by Eladio** [stephenmcd/mezzanine#1286]
The problem appears when you try to add the same replies for different comments. Django's Comment form has a check_for_duplicate_comment function which does not let the same comment to be submittited twice, but it does not check the replied_to parameter attached in Mezzanine's Comment model. I use Django 1.5 and the stable realease of Mezzanine, but it is present in the demo page as well.

**Comment by stephenmcd** [comment]
Thanks for the report. I've a patch incoming that fixes this.
