### ISSUE TITLE
filebrowser_safe: "select files" button doesn't show up in upload dialog

### ISSUE THREAD

**Issue by christianwgd** [stephenmcd/mezzanine#1287]
In the upload dialog the button for selecting files does not show up. 
When i remove the "display: none"-style of the corresponding input element, the standard browser upload input field is displayed. The browser console shows that the uploadify.swf shockwave element is loaded correct. 
![upload](https://cloud.githubusercontent.com/assets/9281647/7551051/6e1996d0-f67a-11e4-948c-5c7ad767f48c.png)

mezzanine master 4/9/2015
Django 1.8.0
python 2.7.8
Browser: Safari 8.0.6 and Firefox 37.0.2
OS: Mac OS 10.10.3 and Debian wheezy

**Comment by jasmjasm** [comment]
I had a similar problem. Apparently it was a permissions problem. Try sudo pip uninstall and install filebrowser_safe.

**Comment by christianwgd** [comment]
thanks for the hint, but that didn't work for me. Uninstalled and reinstalled filebrowser-safe-0.3.8, but the button still isn't displayed.

**Comment by jerivas** [comment]
Make sure your Flash version is up to date. Some browsers won't render
Flash widgets otherwise.

**Comment by christianwgd** [comment]
Flash is up to date. When try with another instance of my app on mezzanine 3.1.10 with django 1.6 the button is displayed (on same client).
Also tried chrome, same issue.

**Comment by christianwgd** [comment]
Tried to install master-branch of filebrowser_safe, no success.

**Comment by christianwgd** [comment]
Ok, found the correct issue at filebrowser_safe, this is duplicate of #42 there.
