### ISSUE TITLE
slow traslate_url

### ISSUE THREAD

**Issue by slav0nic** [stephenmcd/mezzanine#1292]
With default django setting for LANGUAGE (~80 langs) /admin/ page loaded about 10 seconds.

![mezzanine_slow](https://cloud.githubusercontent.com/assets/199555/7636178/2ec24da4-fa6e-11e4-9c8d-1ac29f29c110.png)

**Comment by Kniyl** [comment]
The average of 127ms is not that slow (even though it is). What really kills it is the amount of time the function gets called.

Since it is used only in the ```admin/includes/dropdown_menu.html``` we could be able to rewrite it so that the for loop is done inside the function and not in the template. This will allow us to avoid switching back and forth between the active language and the destination one.

The template could iterate over a list of urls given by the rewriten function instead of the list of languages.

I’ll check tomorow if it improves the rendering time.

**Comment by stephenmcd** [comment]
I've spent many hours before tracking down performance issues, only to discover it's debug toolbar itself that's the problem.

How long does it take with debug-toolbar disabled? I get it in under a second with all languages:

http://cl.ly/ay2p

**Comment by stephenmcd** [comment]
BTW, I don't mean to say we shouldn't optimize it if it's easy enough, just be very wary of debug-toolbar skewing results :-)

**Comment by slav0nic** [comment]
nope, problem not in debug-toolbar, i have same problem on production with DEBUG=False and withoutt toolbar
maybe you timing already cached response ;)

**Comment by stephenmcd** [comment]
Good point! Let's look at it.

**Comment by Kniyl** [comment]
I tryed to come up with something.

@slav0nic can you tell us if it helps speeding things up?

**Comment by stephenmcd** [comment]
I'm not sure where this occurs, but Django itself somehow caches the calculation, so I only see this on first request (without any browser caching occurring).

**Comment by stephenmcd** [comment]
So there's no simple fix to this, and I don't believe it needs fixing.

The time spent is in the calls to Django's `reverse` inside here, twice for each language:

https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/templatetags/mezzanine_tags.py#L668-L694

The only way to remove that would be to hard-code the URL structures somehow, and not use `reverse`. I've actually done that on other projects where performance was critical. But I don't think we need to. In Django 1.8, the calls to `reverse` actually get cached, so we only see this on the first request after the app is started. I looked at Django 1.6 and this wasn't implemented - so if you're using that you won't see this behaviour.

Gonna close this for now.
