### ISSUE TITLE
pip installs django 1.6 with requirements.txt

### ISSUE THREAD

**Issue by InvDeath** [stephenmcd/mezzanine#1294]
When I run pip install -r requirements.txt Django package intalls version 1.6. Is it in mezzanine package dependencies? 
When I run setup.py install - everything ok (django latest). 
Haw can I fix it?

**Comment by stephenmcd** [comment]
Can you post this to the mailing list instead? Thanks

**Comment by InvDeath** [comment]
Sorry, I don't have enough experience with github.
