### ISSUE TITLE
ugettext for forms button_text default value causes migration

### ISSUE THREAD

**Issue by gradel** [stephenmcd/mezzanine#1295]
3766e51b9daef14370aa9d264f9885a5f089512e makes migrations dependent from LANGUAGE_CODE setting. Using another setting than 'en' django registers you made a change to this model.

**Comment by stephenmcd** [comment]
Makes sense - @Kniyl can you remember what this change was for? It's part of the modeltranslation work.

**Comment by jerivas** [comment]
I think I remember. Mathias did that because the button text wasn't 
being translated when rendered in the template.

**Comment by gradel** [comment]
Quick test with ugettext_lazy: button_text is correctly translated in admin as on site.

**Comment by stephenmcd** [comment]
@gradel thanks! How about with modeltranslation configured with multiple languages, does it still work?

**Comment by gradel** [comment]
adding ('fr':, _('French')) to LANGUAGES setting works well, giving 'Envoi' in admin and site. But this is normal django setting. Is modeltranslation configuration elsewhere? Did not care about modeltranslation yet ;).

**Comment by jerivas** [comment]
Make sure you edit the button text in the admin to something different 
than the literal translation of "Submit" or "Send". I think that's where 
the problem showed up. Also, the docs on master have instructions on 
setting up modeltranslation with Mezzanine.

**Comment by Kniyl** [comment]
Actually the problem is the exact opposite. The button text was not translated if modeltranslation was active and the text of the button in a given language is set to whatever gettext should find in the corresponding .po file.

I haven't tested it in a while. I will change it if it is not needed anymore.

**Comment by gradel** [comment]
If I understand it right, that is still the case: with modeltranslation active, leaving the button_text 'Submit'  it does not get translated by gettext anymore. Perhaps this field should not be added to modeltranslation, so if someone wants another button text, he could overwrite it in his project locale.

**Comment by stephenmcd** [comment]
With modeltranslation I don't think it even makes sense to have a database default for the field as we currently have - wouldn't it mean the default is always translated into the UI language, and that would show the same for every instance of the field per content language? (hope that makes sense)

Maybe we should remove the database default, then in the template for the front-end form (where this actually gets used), if no value has been entered, use the default value there, which will be translated as part of the UI (not content).

**Comment by jerivas** [comment]
Yep, in this case handling the default at template level seems better.

**Comment by stephenmcd** [comment]
Cool! I've done it here: 968f80e0946617614d51a1f5414b3ee3e963d0b1 please check it.

Thanks all

**Comment by Kniyl** [comment]
I tested it and ugettext_lazy show send when I set Send, Envoi, Wyślij for en, fr, pl.
Plus, something that I never saw before, when I use ugettext, Wyślij is displayed well, but Envoi is still displayed Send. Probably because my settings.LANGUAGE_CODE is fr.

So removing the default value seems a saner approach than trying to provide a translated alternative.

**Comment by gradel** [comment]
That was going fast, thanks all!
