### ISSUE TITLE
Import error in django_comments

### ISSUE THREAD

**Issue by duduklein** [stephenmcd/mezzanine#1299]
The version in pypi on django-contrib-comments (1.6.1) does not import the Comment model in its __init__.py file.

This generates an error in mezzanine, file: ```mezzanine/generic/models.py```

The line ```from django_comments import Comment``` should be replaced by ```from django_comments.models import Comment ```

**Comment by stephenmcd** [comment]
Done 3 weeks ago in c18cde94eeb1ba5d956226c604b2df6a59dc6992
