### ISSUE TITLE
Twitter data polling stops working with custom oauth/API access and query data after polling with different settings

### ISSUE THREAD

**Issue by xedniv** [stephenmcd/mezzanine#1300]
I seem to have hit a problem with the Twitter data polling. These are the steps I follow to reproduce the issue, on a fresh development database:

* createdb, syncdb, migrate.
* authenticate into admin area
* run manage.py poll_twitter
* proceed to edit oauth and query data (leaving type as 'search')
* save settings in admin
* rerun poll_twitter

What I have observed is that either the tweet data is not populated, or a previous query is reused. This is on a clean, ordinary Ubuntu 14.x stable system running the mezzanine instance inside virtualenv with self-contained dependencies. The mezzanine.twitter app is enabled, needless to say.

The URL is properly built in the API, I verified this:

```
        if not auth_settings:
            from mezzanine.conf import registry
            if self.value == registry["TWITTER_DEFAULT_QUERY"]["default"]:
                # These are some read-only keys and secrets we use
                # for the default query (eg nothing has been configured)
                auth_settings = (
                    "KxZTRD3OBft4PP0iQW0aNQ",
                    "sXpQRSDUVJ2AVPZTfh6MrJjHfOGcdK4wRb1WTGQ",
                    "1368725588-ldWCsd54AJpG2xcB5nyTHyCeIC3RJcNVUAkB1OI",
                    "r9u7qS18t8ad4Hu9XVqmCGxlIpzoCN3e1vx6LOSVgyw3R",
                )
            else:
                raise TwitterQueryException("Twitter OAuth settings missing")
        try:
            print url
            tweets = requests.get(url, auth=OAuth1(*auth_settings)).json()
        except Exception as e:
            raise TwitterQueryException("Error retrieving: %s" % e)
```

**Comment by orotau** [comment]
Hi xedniv
When you say 'What I have observed is that either the tweet data is not 
populated, or a previous query is reused.'
Could u give more details of what you are observing? A screen shot perhaps?
g


On 21/05/15 06:18, xedniv wrote:
>
> I seem to have hit a problem with the Twitter data polling. These are 
> the steps I follow to reproduce the issue, on a fresh development 
> database:
>
>   * createdb, syncdb, migrate.
>   * authenticate into admin area
>   * run manage.py poll_twitter
>   * proceed to edit oauth and query data (leaving type as 'search')
>   * save settings in admin
>   * rerun poll_twitter
>
> What I have observed is that either the tweet data is not populated, 
> or a previous query is reused. This is on a clean, ordinary Ubuntu 
> 14.x stable system running the mezzanine instance inside virtualenv 
> with self-contained dependencies. The mezzanine.twitter app is 
> enabled, needless to say.
>
> The URL is properly built in the API, I verified this:
>
> |         if not auth_settings:
>              from mezzanine.conf import registry
>              if self.value == registry["TWITTER_DEFAULT_QUERY"]["default"]:
>                  # These are some read-only keys and secrets we use
>                  # for the default query (eg nothing has been configured)
>                  auth_settings = (
>                      "KxZTRD3OBft4PP0iQW0aNQ",
>                      "sXpQRSDUVJ2AVPZTfh6MrJjHfOGcdK4wRb1WTGQ",
>                      "1368725588-ldWCsd54AJpG2xcB5nyTHyCeIC3RJcNVUAkB1OI",
>                      "r9u7qS18t8ad4Hu9XVqmCGxlIpzoCN3e1vx6LOSVgyw3R",
>                  )
>              else:
>                  raise TwitterQueryException("Twitter OAuth settings missing")
>          try:
>              print url
>              tweets = requests.get(url, auth=OAuth1(*auth_settings)).json()
>          except Exception as e:
>              raise TwitterQueryException("Error retrieving: %s" % e)
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/stephenmcd/mezzanine/issues/1300>.
>

-- 
T : 021 081 71732

**Comment by xedniv** [comment]
```
observe
əbˈzəːv/
verb
past tense: observed; past participle: observed
1.
notice or perceive (something) and register it as being significant.
```

**Comment by stephenmcd** [comment]
@xedniv please don't do that, @orotau is merely trying to help you

**Comment by xedniv** [comment]
This is also cited in the comment sections in this link:
http://theneum.com/blog/django-mezzanine-twitter-setup/

The workaround is to use the tweets_for template tag. The default tag will not work. The problem is that something is not updating the twitter_query contents (so the backend still contains outdated query settings, while the actual site settings include the correct data).

Stephen, it was not meant in a hostile way.

**Comment by stephenmcd** [comment]
He asked you for more details and you reply with the definition of observe - how else could it be taken?

**Comment by xedniv** [comment]
Well, there are no more details that can be added to the issue. The problem can be observed by directly inspecting the backend database contents and following the steps to reproduce. My somewhat lucky guess is that there should be some sort of synchronization between the current value of the twitter query (as set in the site settings), and the Query objects/data stored by the twitter application. This should be done either automatically or during 'poll_twitter', but for some obscure reason it isn't happening. It still doesn't explain why initially the polling didn't populate the data (tweets). I hope this helps other people coming across the same problem. It makes sense, since tweets_for essentially forces the API to retrieve tweets using a custom query.

**Comment by stephenmcd** [comment]
Then just say so - don't reply with a smartass dictionary definition.

**Comment by xedniv** [comment]
Agreed, although it may have elicited a less ambiguous response if he had noted my original description carefully. Let me know if I can help track it down further.

**Comment by kenbolton** [comment]
@xedniv: Didn't we sort this out on IRC? You want to modify your template and use the appropriate template tags. If you look at [line 4 of mezzanine/twitter/templates/tweets.html](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/twitter/templates/twitter/tweets.html#L4), you will see that the template is iterating over `tweets_default`. Modifying `templates/twitter/tweets.html` in your app and changing it to tweets_for_user, tweets_for_list, or tweets_for_search should sort you out.

Your expressions of frustration are hindering our ability to provide positive support. Please make an effort not to bring them to the IRC channel, the mailing list, or back here.

Closing this issue.

**Comment by orotau** [comment]
Happy to feedback on any issues in terms of the community culture, *if useful*. Otherwise will just let it go
g
