### ISSUE TITLE
Feature Request: Support IDs or custom names for form fields

### ISSUE THREAD

**Issue by xedniv** [stephenmcd/mezzanine#1301]
I discussed this with @kenbolton and it seems it would be very handy to support naming or setting a string ID accessible by the templates in form fields. For instance, in some cases we may want to render a form with a custom template and carefully position each field in a layout.

One example is a contact form where you may want certain fields sharing the same line/row in the layout, while others get their own. If support existed for named fields, we could render certain fields by name, and then process the rest as needed.

Thoughts?

**Comment by stephenmcd** [comment]
Can you post this to the mailing list please?

Thanks!

**Comment by xedniv** [comment]
Sure, but why close the feature request here?
