### ISSUE TITLE
Possible feature add or am i missing something obvious with --no-initial-data

### ISSUE THREAD

**Issue by haganf** [stephenmcd/mezzanine#1302]
Hi,

I'm using docker atm and trying to automate as much as possible for deployment. During the migrate step of a django app using mezzanine, the command 'python manage.py migrate --no-initial-data --noinput' seems to setup some default fixtures for cartridge/mezzanine which i am hoping to prevent.

https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/management/commands/createdb.py
My question is, can --no-initial-data be added to the createdb.py so that 'no' will be assumed instead of 'yes' on setting up data for mezzanine. Or is there some better way i'm missing.  I could use expect at the shell, but i'm hoping for something simpler.

thanks,

-hagan

**Comment by kenbolton** [comment]
Hi @haganf,

Please use the [Mezzanine mailing list](https://groups.google.com/forum/#!forum/mezzanine-users) for questions like this going forward.

If I understand your question correctly, you are looking for the --nodata flag for createdb. Take a look at how the command is automated in the [fabfile](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/project_template/fabfile.py#L522).
