### ISSUE TITLE
Injecting fields for the Page model and overriding its Admin class will remove subclass fieldsets

### ISSUE THREAD

**Issue by xedniv** [stephenmcd/mezzanine#1306]
I have added injected fields to the base Page model. In my admin.py I override them like so:

```
from copy import deepcopy
from django.contrib import admin
from mezzanine.pages.admin import PageAdmin
from mezzanine.pages.models import Page, RichTextPage

page_fieldsets = deepcopy(PageAdmin.fieldsets)
page_fieldsets[0][1]["fields"].append(u"extra_menu_prefix")
page_fieldsets[0][1]["fields"].append(u"menu_description")

class MyPageAdmin(PageAdmin):
    fieldsets = page_fieldsets

admin.site.unregister(Page)
admin.site.unregister(RichTextPage)

admin.site.register(Page, MyPageAdmin)
admin.site.register(RichTextPage, MyPageAdmin)
```

I might be mistaken but the following code in mezzanine.pages.admin in the __init__ method might be blocking the Admin object from being initialized properly for subclasses, since the default fieldset and the one with injected fields will fail the comparison:

```
class PageAdmin(DisplayableAdmin):
...
    def __init__(self, *args, **kwargs):
        super(PageAdmin, self).__init__(*args, **kwargs)
        # Test that the fieldsets don't differ from PageAdmin's.
        if self.model is not Page and self.fieldsets == PageAdmin.fieldsets:
```

I think I can workaround the issue by explicitly re-adding the content field, but this seems counter intuitive and a source of headaches whenever the underlying models in Mezzanine are updated and more fields need to be added.

Needless to say, without that, after injecting the fields in the fieldset, the admin will not display the 'content' field and its textarea.

**Comment by joshcartme** [comment]
Instead of this:

    class MyPageAdmin(PageAdmin):
        fieldsets = page_fieldsets

try this:

    PageAdmin.fieldsets = page_fieldsets

Then just unreregister and reregister with PageAdmin
