### ISSUE TITLE
Make template tags more generic to support alternative template engines.

### ISSUE THREAD

**Issue by destos** [stephenmcd/mezzanine#1312]
I'm currently attempting to use Jinja2 with django-jinja and translating the templates has been quite a pain due to many of the template tags that exist within the different mezzanine apps being tied tightly to Django templates. Not all of them prove difficult to translate. Quite often I also have to circumvent the decorators on simpler tags to get them to work.

I would mainly like to just start a discussion about this change with maintaining backwards compatibility but providing those of us that wish to use a different template engine in Django > 1.8 with some recourse.

**Comment by stephenmcd** [comment]
What does this entail? 

If it's trivial then sure, why not. If it requires a decent amount of change to Mezzanine, I personally don't think it would be worthwhile.

**Comment by destos** [comment]
It probably entails making some of the tag processes more generic ( not tied to Django template nodes and their api ) and then providing an un-decorated version of those tags or blocks for consumption by alternative template engines.

I wouldn't mind spiking a bit on a few of the template tags as an example to get buy in.

**Comment by stephenmcd** [comment]
Sure. Why don't you start with the largest/worst/most tightly integrated ones, so we actually know what we're buying into.

**Comment by stephenmcd** [comment]
`page_menu` comes to mind

**Comment by destos** [comment]
That's the one I just had to deal with to rebuild menus in jinja, making it so.

**Comment by stephenmcd** [comment]
Please don't get too enthused though! I'm personally against this, but let's see what it looks like.

**Comment by jerivas** [comment]
Hey Patrick. Honest question: What benefits do you see in Jinja2 over 
the Django template language? :) Understanding the use cases might help 
make an informed decision.

**Comment by destos** [comment]
@jerivas I'll try to find a few links that explain my reasoning.
http://blog.sendwithus.com/python-templating-performance-showdown-django-vs-jinja/
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783793

Not mentioned in those, but jinja macros will allow for template code re-use without a reliance on block inheritance. Macros also come into use when iterating over similar items and only a small portion needs to change. I can see myself creating some macros for displaying related posts or post lists and re-using those in different areas. 

There was also talk about switching over to jinja as django's default template engine by some of the maintainers a while back. However that never came to be probably because of the trouble that would have caused everyone. But thankfully now we have 1.8 with alternative template engine support.

**Comment by stephenmcd** [comment]
Closing this as it doesn't need an issue open - but please go ahead and put together the PR, which will serve to continue the discussion on feasibility.
