### ISSUE TITLE
1.9 deprication warning

### ISSUE THREAD

**Issue by auvipy** [stephenmcd/mezzanine#1315]
May 26, 2015 - 12:47:51
Django version 1.8.2, using settings 'lentas.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/usr/local/lib/python2.7/dist-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/pages/page_processors.py:7: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

/usr/local/lib/python2.7/dist-packages/django/template/base.py:825: RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.
  current = getattr(current, bit)

/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py:126: RemovedInDjango19Warning: `MergeDict` is deprecated, use `dict.update()` instead.
  self._request = datastructures.MergeDict(self.POST, self.GET)

**Comment by stephenmcd** [comment]
Please, there's no need to open issues for these. They're warnings for an unreleased Django version.

If you're unsure whether something's worth creating an issue for, please post to the mailing list first.
