### ISSUE TITLE
Allow collecttemplates to not overwrite existing files

### ISSUE THREAD

**Issue by stephenmcd** [stephenmcd/mezzanine#1319]
As per http://stackoverflow.com/questions/30496232/django-mezzanine-dont-overwrite-local-files-with-collecttemplates

**Comment by Kniyl** [comment]
Last time I ran collecttemplates, I was asked if I wanted to overwrite templates that appeared twice in the INSTALLED_APPS. Not sure if it works the same with local modifications of a single file, but the django code is worth reusing if it is not the case.

**Comment by stephenmcd** [comment]
Oh my bad - the command has this feature already and I totally forgot. Thanks!
