### ISSUE TITLE
multi lingual sites tutorial 

### ISSUE THREAD

**Issue by tabatabaei** [stephenmcd/mezzanine#1320]
i wan't to make new project for two languge 
i need good tutorial for mezzanine 3.1.10 and django 1.8 and python 3.4 
i can't access this link
http://mezzanine.jupo.org/docs/multi-lingual-sites.html
i found link in mezzanine doc 
how to find good and simple tutorial for multi lingual and desing themplate for mezzanine

**Comment by Kniyl** [comment]
The best thing that exist at the moment is the doc folder in your master clone. The link will point to https://github.com/stephenmcd/mezzanine/blob/master/docs/multi-lingual-sites.rst as soon as the new version will be released.

An other good resource is the documentation of modeltranslation itself: https://readthedocs.org/projects/django-modeltranslation/

**Comment by Kniyl** [comment]
Also, please use the mailing list (https://groups.google.com/forum/#!forum/mezzanine-users) for general questions.
