### ISSUE TITLE
import_rss date and tag problem

### ISSUE THREAD

**Issue by amandegar** [stephenmcd/mezzanine#1329]
I found two problem when i used python manage.py import_rss every day
1) this script use last modified date instead publishdate
2) every time i used this script in fixed number of posts, tags are added again and number of post has use tag were increased.

**Comment by kenbolton** [comment]
Take a look at the second paragraph of the [Considerartions](http://mezzanine.jupo.org/docs/blog-importing.html#considerations) section of the [Blog Importing](http://mezzanine.jupo.org/docs/blog-importing.html) documentation:

> Generally speaking you shouldn’t be able to import your data twice. There is a check in place to either create or update for both comments and posts as they are processed, so even if you run the importer multiple times you should only end up with data imported once. However if you have changed any data this will be overwritten.

Can you describe your use case? Using importers more than once is not supported.

**Comment by amandegar** [comment]
For issue number 1 i fixed the problem by modifying script and it was so easy.

for issue 2: i have two blog which second import from first and usually needs update from 1st one. it is not possible to import once. whenever i write a post on first one i need to update second one.
