### ISSUE TITLE
Third party apps and modeltranslation.

### ISSUE THREAD

**Issue by itztli** [stephenmcd/mezzanine#1332]
Hi all!

I am testing the new modeltranslation feature. However, mezzanine_events not works (in old and new projects). I sent a message to the development team of mezzanine_events but unfortunately I don't see activity in their project. The question is: How can trust that our old applications will work when upgrade to the new version of mezzanine and activate modeltranslation capability? I mean: How can validate that third party apps will work with modeltranslation for mezzanine?

**Comment by stephenmcd** [comment]
There's no need to open an issue here. Feel free to start a mailing list thread.
