### ISSUE TITLE
Switching language not working

### ISSUE THREAD

**Issue by itztli** [stephenmcd/mezzanine#1334]
Sorry if it is not an issue, but the switching language included in base.html not works.

**Comment by Kniyl** [comment]
Can you be more specific? Does it display but don't function properly or dors it not display at all?

What are your settings for USE_MODELTRANSLATION and LANGUAGES?

**Comment by itztli** [comment]
Thanks @Kniyl .

My configuration:

Mezzanine 3.1.10 (from git)
Django 1.8.2
Python 2.7.9
PostgreSQL 9.4.2
Linux 3.19.0-18-generic

Console output (when change between language):
[17/Jun/2015 18:34:53]"GET /about/team/ HTTP/1.1" 200 12041
[17/Jun/2015 18:34:56]"POST /i18n/ HTTP/1.1" 302 0
[17/Jun/2015 18:34:56]"GET /about/team/ HTTP/1.1" 200 12041

My settings:
USE_MODELTRANSLATION = True
LANGUAGE_CODE = "es"
LANGUAGES = (
    ('es', _('Spanish')),
    ('en', _('English')),
)

INSTALLED_APPS = (
    "modeltranslation",
    "django.contrib.admin",
  
The project was created from the scratch using mezzanine-project.

**Comment by Kniyl** [comment]
First, as long as you set USE_MODELTRANSLATION to True, there is no need to add "modeltranslation" to INSTALLED_APPS.

Looking to your requests, django's select language url seems to work. Can you open the source of the page before and after using the language dropdown and check that the <html lang="XX"> tag has consistent values with the actions you are performing.

If this value is changing but not the content, it means that the page you are looking at does not use the {% trans %} template tag nor translation fields properly.

If this value is not changing it is more likely a bug. Just to be sure, then, when you state using Mezzanine 3.1.10 (from git), does it means you are retrieving the 3.1.10 tag from git or are you using the latest version from master?

**Comment by Kniyl** [comment]
Oh, and make sure that the localeMiddleware is activated, this might be the thing preventing {% trans %} from working correctly.

**Comment by itztli** [comment]
The problem was that I am declaring the modeltranslation in both: INSTALLED_APPS and USE_MODELTRANSLATION.
When I remove the module from INSTALLED_APPS the app works.

I was following an old README, I see that are a new one: https://github.com/stephenmcd/mezzanine/blob/master/docs/multi-lingual-sites.rst

Thank you so much!
