### ISSUE TITLE
When changi

### ISSUE THREAD

**Issue by wimfeijen** [stephenmcd/mezzanine#1336]
Hello,

In the admin, the tinymce toolbar does not load when I set the language of the admin to Dutch (using the pull-down in the top right or when logging in and having selected the Dutch language), when editing a rich text page for example (at /nl/admin/pages/richtextpage/add/ ).

I am using a fresh installation of mezzanine master and made the following changes to my settings:

# Supported languages
LANGUAGES = (
    ('en', _('English')),
    ('nl', _('Dutch')),
)

USE_I18N = True
USE_L10N = True

**Comment by stephenmcd** [comment]
You probably need the master branch of grappeli-safe too.

**Comment by wimfeijen** [comment]
Yes! Thanks for your quick response!

**Comment by yltang52** [comment]
I have problem bringing up TinyMCE on mezzanine's admin page.

I installed the development version of mezzanine with "pip install https://github.com/stephenmcd/mezzanine/archive/master.zip" for the sake of being able to run on Heroku. I checked with "pip freeze" and found "grappelli-safe==0.3.13" is already installed. However, the tinyMCE editor does not show up.

Furthermore, the following grappelli-related settings are in the settings.py of the current version of mezzanine, which are not in the development version:

    -----
    PACKAGE_NAME_FILEBROWSER = "filebrowser_safe"
    PACKAGE_NAME_GRAPPELLI = "grappelli_safe"

    # These will be added to ``INSTALLED_APPS``, only if available.
    OPTIONAL_APPS = (
        "debug_toolbar",
        "django_extensions",
        "compressor",
        PACKAGE_NAME_FILEBROWSER,
        PACKAGE_NAME_GRAPPELLI,
    )
   -----

I added the above into settings.py, but still couldn't bring up TinyMCE. Any suggestions?

**Comment by Kniyl** [comment]
>  I checked with "pip freeze" and found "grappelli-safe==0.3.13" is already installed.

grappelli-safe 0.3.13 is not the master branch…

```pip install --upgrade https://github.com/stephenmcd/grappelli-safe/archive/master.zip``` should get you running

**Comment by yltang52** [comment]
It worked. Many thanks, Kniyl.

**Comment by itztli** [comment]
Sorry, but I have the same issue. I fix it installing grappelli-safe as @Kniyl points. However, if I enter in the admin site with the spanish language activated then TinyMCE not works. If I switch to english and enter again to admin page then all works ok.

**Comment by Kniyl** [comment]
@itztli Are you sure it is modeltranslation related? Are you able to load the page properly in spanish when USE_MODELTRANSLATION is set to False?
