### ISSUE TITLE
How to modify django.po on Heroku

### ISSUE THREAD

**Issue by yltang52** [stephenmcd/mezzanine#1338]
I used to run Mezzanine on Heroku. Recently, I need to customize some of the strings in the `django.po`. As Mezzanine is installed from `requirements.txt`, how do I specify/upload my own version of `django.po`?

**Comment by stephenmcd** [comment]
Can you post this to the mailing list instead? Thanks

BTW, it's a general Django question, so you might want to try the Django list which has 20x the number of subscribers.
