### ISSUE TITLE
When SitePermissionMiddleware fails it returns 200 with the log in page instead of redirecting

### ISSUE THREAD

**Issue by frankier** [stephenmcd/mezzanine#1340]
This is a bit unusual and not what Django itself does. It should probably redirect to the login page with a querystring like ?no_site_permission&next=/admin/foo/ instead.

**Comment by stephenmcd** [comment]
I don't think it causes a problem, it's what Django admin used to do.

If you feel strongly about it, go ahead and contribute the fix, I'll merge it.

**Comment by stephenmcd** [comment]
On second thoughts it's probably not even worth addressing - that permission check should only error during login.

If the permission changed while they were within the admin already, redirecting back to where they were makes no sense.
