### ISSUE TITLE
With tinymce4 the filebrowser lacks the "insert button" column

### ISSUE THREAD

**Issue by christianwgd** [stephenmcd/mezzanine#1341]
tinymce3:
![tmce3](https://cloud.githubusercontent.com/assets/9281647/8485592/ee283ac6-20fe-11e5-89d5-be92a323c806.png)

tinymce4:
![tmce4](https://cloud.githubusercontent.com/assets/9281647/8485602/0273c860-20ff-11e5-9c5e-5cb67d13c48a.png)

project environment:
Mezzanine master (July 2, 2015)
Django 1.8.2

**Comment by christianwgd** [comment]
I was unsure if i should open this issue here or in the file browser_safe repo, but it is broken since tinymce4. So I suppose, this repo is the right one...

**Comment by christianwgd** [comment]
ok, i've understood why the select-column does not appear: The custom_file_browser-function has a parameter "pop=5" and in the filelisting.html filebrowser-template only the parameter "pop=2" to "pop=4" are handled. Simply copying one of the 2 to 4 sections to a 5-section doesn't work. 
I'll try to dig deeper into it...

**Comment by alan-hicks** [comment]
Feel free to use anything at http://p-o.co.uk/tech-articles/howto-use-tinymce-with-django-filebrowser-media-manager/ I've had TinyMCE V4 running successfully for well over a year.  The patch http://p-o.co.uk/files/filebrowser-to-tinymcev4.txt should help you get it up and running.

**Comment by christianwgd** [comment]
Thanks for the link, Alan. But i've already tried this and its not suitable for mezzanine with filebrowser_safe (it's working for django_filebrowser, I suppose). What I have to do is indeed working out the appropriate parts of this for mezzanine file browser_safe in its current configuration.

**Comment by christianwgd** [comment]
I tried to adapt Alans suggestions to the new mezzanine Version and now get an Error with in the file "tiny_mce_popup.js" which is not included in the django_filebrowser templates but in filebrowser_safe: [Error] TypeError: undefined is not a function (evaluating 'b.editor.windowManager.createInstance("tinymce.dom.DOMUtils",document)')
	init (tiny_mce_popup.js, line 5)
	global code (tiny_mce_popup.js, line 5)

**Comment by christianwgd** [comment]
Apparently the file "tiny_mce_popup.js" isn't any more part of the TinyMCE configuration, at least since it was moved from grapple-safe to mezzanine but the filebrowser_safe template "filelisting.html" references this file. Further more the "tinymce_setup.js" in mezzanine sets the pop parameter to 5 but the file browser_safe template "filelisting.html" does handle only 1 to 4. Seems like filebrowser_safe wasn't updated. Can anybody who is more familiar with this code give a hint?
Thanks,Christian

**Comment by stephenmcd** [comment]
I looked at this today and mostly have it fixed, please hang tight.

**Comment by stephenmcd** [comment]
Should be resolved by both 1844176e69fd9d847a5fdb71dffddcfafe9fdf00 and https://github.com/stephenmcd/filebrowser-safe/commit/a5e6f1246eddc31c2e79c2b9dd9302ffb21eb584 as also reported in #705
