### ISSUE TITLE
i18n for Link Pages in Menu

### ISSUE THREAD

**Issue by gungorbudak** [stephenmcd/mezzanine#1345]
Hi,

I'm using modeltranslation to have a multilingual Mezzanine web page and I think there is a little issue about rendering menus for link pages when i18n_patterns is set for URLs.

The issue is for rich text pages, the language code is prepended before the slug without a problem in the menu like `http://127.0.0.1:8000/en/my-rich-text-page/` but when I create a link page, the language code doesn't appear in the menu like here: `http://127.0.0.1:8000/my-link-page/`.

Of course, when I click to the link page, it redirects to the active language version but still as the language code isn't there in the menu, some functionalities doesn't work like having a different background if the menu item is active.

I just upgraded my Mezzanine version to the one here on GitHub, so it must be the latest version.

Is this a bug/issue or am I doing something wrong?

**Comment by stephenmcd** [comment]
Link pages are intended for external links, I'm pushing a fix that ensures this.

**Comment by jerivas** [comment]
Hey, can we discuss this a little? I use local Link pages quite a bit to
achieve a clean menu structure. Normally I set a Link page as the parent of
a bunch of children, and point it to the first child.

I guess I could ask users to input the full target URL, but this would
break when moving from staging to production (different domains).

**Comment by philipsouthwell** [comment]
Yes. I also use local link pages as a parent in the menu structure. I do this because I don't think there's a way to have a parent menu item unclickable in Mezzanine?

**Comment by Kniyl** [comment]
It might be possible to achieve the unclickable parent item by adding a field to all Page using EXTRA_MODEL_FIELDS. And rewriting templates to check fort this field ans decide whether or not using a link...

And for the Link issue, what about creating a new subclass of page along the line of Link that would just hold a foreign key to another Page and will, in its page processor, just redirect to the URL of the foreign key ? We could call such model Proxy or Redirect. Coupled with a unique constraint on the slug field of each pages, it can help solve #1240...

**Comment by stephenmcd** [comment]
I think we can revert the change, we'll just need to address the other issues.

**Comment by stephenmcd** [comment]
So I reverted this for now in 710a19a72aa8423762d7d8d42bb8411589367610 since it was a bit rushed, but I think this is still worth discussing. 

I made the change as I think the original intention of the Link model was actually for external links only, and actually validating that would prevent some of the issues showing up - duplicate slugs as per #1342  (although I don't even know how this occurs since slugs are given a unique suffix on save if duplicate), and the localised URL problem reported in this issue here.

Given the original intention of external links, the example of pointing parent pages to their first child seems like a mis-use of it, and maybe there's another solution to that. What happens if the child URL changes, the parent would be broken right? Perhaps we need a new "PlaceholderPage" that has no notion of slug at all - that could be used, then the "parent goes to first child" behaviour could be implemented at the template/javascript level.

That said, maybe there are other use cases where people are relying on the current behaviour, so if there's enough of a case for other things, we might just leave it as is and allow internal links to be used.

**Comment by stephenmcd** [comment]
Posted a mailing list thread asking for input: https://groups.google.com/forum/#!topic/mezzanine-users/6wvt2ltJ3gE

**Comment by jerivas** [comment]
Upon further reading of this bug report: isn't the behaviour described here the desired one? The Link should point to the non-prefixed slug of the target page, and then Django's i18n machinery should do the redirecting to the appropriately prefixed slug. The Link page in the menu will never be highlighted, as you can never truly "visit" that page.

IMO the only thing that needs fixing is the slug-uniqueness constraint. Perhaps the Page methods related to slug retrieval and generation simply need to be updated to ignore Link instances.

**Comment by Kniyl** [comment]
> That said, maybe there are other use cases where people are relying on the current behaviour, so if there's enough of a case for other things, we might just leave it as is and allow internal links to be used.

I make use of Link pages to point to specifically crafted internal URL that redirect to desired pages using the magic of urls.py. I lack time at the moment to try something cleaner like the "Proxy" model I was referring to.

However, I would start testing it with something along the lines of: https://gist.github.com/Kniyl/44acedbb7de112214132 (this also integrates @stephenmcd idea of "parent goes to first child").

**Comment by joshcartme** [comment]
A common use case I've had was pointing links internally at different blog categories to give the appearance of having multiple blogs even though on a technical level they were just categories.

**Comment by stephenmcd** [comment]
Cool, so let's leave the Link format open-ended as it's been and try and resolve the other issues.

Agree with Ed's points - there really shouldn't be any relationship between Link pages and i18n, so we just need to look at cases where duplicate slugs cause a problem. I know there are parts in the code already that exclude the Link model from Page-wide queries, shouldn't be hard to fix if we can identify them.

**Comment by gungorbudak** [comment]
Thanks for the comments, I also use local Link pages a lot. They are very useful. So, it's good that we are keeping them but still my issue isn't solved. The issue was `active` class isn't defined for localized Link page URLs as the URL is different with the appended language code. Could there be a fix to solve this issue so that for Link pages, the language code is ignored for deciding if the menu item is active or not and we have nice darker background?
