### ISSUE TITLE
New Release supporting latest version of Django?

### ISSUE THREAD

**Issue by kevgathuku** [stephenmcd/mezzanine#1348]
Hi,
I have been using Mezzanine on a project for a while and I now have to inevitably update the Django version. My current Django version is 1.6. From the latest version of Mezzanine on Github, I see that Django 1.7 and 1.8 are supported but no release has been made since updating the Django versions.
In order to use the latest Mezzanine, I have to rely on the latest master version, which I am not very comfortable doing. Is it possible to make a release officially supporting Django 1.7 and/or 1.8?

**Comment by stephenmcd** [comment]
No need to open an issue for this, thanks!

**Comment by kevgathuku** [comment]
Hello @stephenmcd ,
Sorry if this is not the correct place to post this. 
What would be the better place to make the request or any similar request in future?

**Comment by stephenmcd** [comment]
The request is redundant - a new release will be made as soon as it's ready.

That aside, you'd want the mailing list, not the issue tracker.

Thanks.

**Comment by gavinwahl** [comment]
@stephenmcd, Where can I find what is making it not ready? How can I make it ready?

**Comment by stephenmcd** [comment]
@gavinwahl it's not always that simple, many things in life take priority - anyway it's out now.

**Comment by henri-hulski** [comment]
:v:
