### ISSUE TITLE
Link dialog sometimes won't open in admin interface 

### ISSUE THREAD

**Issue by athalean** [stephenmcd/mezzanine#1351]
In some situations, trying to open `/displayable_links.js` generates a 500 with the following message:

> TypeError at /displayable_links.js - unorderable types: dict() < dict()

https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/views.py#L197

Replacing this line with e.g. `return HttpResponse(dumps([link[1] for link in sorted(links, key=lambda link: link[1]['title'])]))` fixes the problem.

I'm using Python 3.4, but this line of code looks unintended and shouldn't work on Python 2 either :-)

**Comment by AlexHill** [comment]
Thanks for the report. In order to match the function's comment I've made the sort key `(link[0], link[1]['value'])`.

**Comment by AlexHill** [comment]
BTW it does "work" on Python 2 in the sense that no exception is raised, but I'm guessing the semantics are undefined given that this was removed in Python 3.

**Comment by stephenmcd** [comment]
Fixed in #1352
