### ISSUE TITLE
cache_installed checks for hardcoded strings

### ISSUE THREAD

**Issue by couchcrew-thomas** [stephenmcd/mezzanine#1355]
The [cache_installed](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/utils/cache.py#L58) method checks for hardcoded module strings inside the INSTALLED_APPS setting.

This prevents extending the cache middleware classes which is required for our project.
Could this be fixed so that the method can be overridden or be smart enough to detect if cache is installed more intelligent?

**Comment by AlexHill** [comment]
Sounds reasonable. Fixed in 8614da9
