### ISSUE TITLE
robotx.txt

### ISSUE THREAD

**Issue by robenwang** [stephenmcd/mezzanine#1356]
Is it typo: 

in mezzanine/urls.py, the code is different with the comment. the code will disallows all spides when DEBUG=False. 
---------------------mezzanine/urls.py------
comment:  Return a robots.txt that disallows all spiders when DEBUG is True.
code:
if getattr(settings, "DEBUG", False):
    urlpatterns += patterns("",
        ("^robots.txt$", lambda r: HttpResponse("User-agent: *\nDisallow: /",
                                                content_type="text/plain")),
    )

**Comment by Kniyl** [comment]
`getattr(settings, "DEBUG", False)` is equivalent to `settings.DEBUG if hasattr(settings, "DEBUG") else False`. Hence the test validating only if `settings.DEBUG` is defined with a trueish value.
