### ISSUE TITLE
local_settings.py should be execfile'd instead of imported

### ISSUE THREAD

**Issue by spookylukey** [stephenmcd/mezzanine#1360]
There are various ways to handle the combination of settings.py files. With the current system in the default project, we just have `from .local_settings import *`. The disadvantages of this are:

* inside `local_settings.py`, you don't have access to anything defined in `settings.py`, which you often want. (There are ways, involving `sys.modules`, but they are fairly obscure)
* if you want `local_settings.py` to modify a setting (e.g. append to `MIDDLEWARE_CLASSES` or `INSTALLED_APPS`), you will have difficulties (solved as above, but still hacky).
* the result is that things end up being defined in `local_settings` instead of in `settings` - like, for instance, most of the items in the `FABRIC` dictionary and `ALLOWED_HOSTS`. There then will need to be separately defined in the same way for every developer who works on the project.

There are various solutions, but this one is a simple one that works for me: use `execfile` on `local_settings.py` instead of import. The difference is that `local_settings` is executed in the namespace of `settings`, rather than as a separate module. It has automatic access to everything already defined, so all the above can be fixed easily.

**Comment by stephenmcd** [comment]
Sounds great Luke. Do you want to submit the change?

**Comment by spookylukey** [comment]
Yep, happy to do so.

**Comment by stephenmcd** [comment]
Awesome, thank you!

**Comment by kelvinwong-ca** [comment]
Hello. I have a few comments on this:

1. `settings.py` is specific to a project, if you want to do things your way then you are free to do as you see fit.
2. There is nothing wrong with `from local_settings import *` and most know what it does when you see it (and if you don't like it you can change it)
3. `execfile` was removed in an opinionated fashion in Python 3, see https://bugs.python.org/issue5524

```
Exeter:crap kelvin$ python2.7
Python 2.7.10 (default, May 25 2015, 13:06:17)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> execfile('hello.py')
Hi there!
>>> ^D
Exeter:crap kelvin$ python3.2
Python 3.2.6 (default, Nov 12 2014, 18:13:52)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> execfile('hello.py')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'execfile' is not defined
>>> ^D
Exeter:crap kelvin$ python3.3
Python 3.3.6 (default, May 25 2015, 18:42:02)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> execfile('hello.py')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'execfile' is not defined
>>> ^D
Exeter:crap kelvin$ python3.4
Python 3.4.3 (default, May 25 2015, 18:48:21)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> execfile('hello.py')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'execfile' is not defined
>>> ^D
```

**Comment by spookylukey** [comment]
@kelvinwong-ca - Thanks for the info about Python 3, I wasn't aware of that. We can get around it easily using `exec(open(...` - I presume the redundancy of execfile was the reason it was removed.

People do indeed know what `from .local_settings import *` does, but they may not be aware of  alternatives that could serve them better. The current default makes some things very hard, and means you have things defined in the wrong places, or in ways that are not DRY.

I think one of the great things about Mezzanine is that it comes with a really good default project templates, with things set up so you don't need to fight it to get things going. It would be great if that could be refined even more.

Handling local/production settings is a significant issue, as shown by the many questions about this and the many solutions:

* [django-local-settings](https://pypi.python.org/pypi/django-local-settings)
* [django-split-settings](https://github.com/sobolevn/django-split-settings)
* http://stackoverflow.com/a/14545196/182604
* https://code.djangoproject.com/wiki/SplitSettings
* http://stackoverflow.com/a/15325966/182604

I actually lean towards the last solution on the list, but that would require a much bigger change to the settings file structure (the imports happen in the opposite order in a sense). So I'm suggesting the exec solution because it is a very small change, with a lot of benefits and no real down sides, because it is backwards compatible with the current way of doing it.

**Comment by stephenmcd** [comment]
+1 to Luke's comments - I'm not keen on moving beyond simple settings.py / local_settings.py pair of modules, but currently we need to redefine settings from scratch in local_settings.py if we only want to modify them slightly. Presumably with the opposed change we can do something like `INSTALLED_APPS += ("foo",)` in local_settings.py and it'll work, which is a huge win.

**Comment by spookylukey** [comment]
See PR #1363. I haven't updated the project templates or the documentation to make use of this. I think, for instance, that the FABRIC settings could be split up. However, this makes the docs more complicated, and it could be confusing especially for all the existing installations which don't use the 'exec' solution.

**Comment by stephenmcd** [comment]
Thanks Luke!

**Comment by stephenmcd** [comment]
#1363

**Comment by sjkingo** [comment]
Should we perhaps add a message to the top of `runserver` startup if `DEBUG == True` that the server will not pick up changes to the `local_settings.py` file, as per [this](https://github.com/stephenmcd/mezzanine/pull/1363/files#diff-3d1d821f3203e30cedc42c73f2de061bR4)?

**Comment by stephenmcd** [comment]
Sure, I imagine it'll be annoying not having it reload - since we override runserver already (in mezzanine.core I think), I wonder if we can somehow manually add local_settings.py to the list of watched files.

**Comment by sjkingo** [comment]
I don't believe you can make `runserver` reload on any arbitrary file reload (it only watches files loaded in settings) - @spookylukey is this true? Or can we work around it somewhere? Surely it just uses `inotify`?

**Comment by spookylukey** [comment]
The `django.utils.autoreload` code does use just inotify, but it doesn't look especially easy to wrap the code to add this modification.

However, looking at the code I've come up with this workaround, to be added to the `settings.py` file, in the `if os.path.exists(f)` branch:

    # Create a sys.modules entry for the sake of the autoreloader:
    import sys
    import imp
    _name = ".".join(__name__.split(".")[0:-1] + ["local_settings"])
    _mod = imp.new_module(_name)
    _mod.__file__ = f
    sys.modules[_name] = _mod

This is not as succinct as I might like, but it succeeds in getting the autoreloader to see the `local_settings.py` file and respond to changes in it. I've tested the above code on Python 2.7 and 3.4, it works on both.

I'm probably not going to have time to put a proper patch together, please go ahead and use this if you think it is appropriate.

**Comment by stephenmcd** [comment]
That's great, thanks Luke. I've added it in 7c4b82d914c51076971607316b72e367d762f883

**Comment by noure-beep** [comment]
i have a code
