### ISSUE TITLE
TinyMCE elements don't display when crossing http/https

### ISSUE THREAD

**Issue by molokov** [stephenmcd/mezzanine#1365]
Mailing list thread: https://groups.google.com/forum/#!topic/mezzanine-users/cyeNtYsmQeU

Basically, my site has SSL Enabled (and the SSLRedirectMiddleware uncommented in settings.py) and there are certain elements of TinyMCE that just don't load/work when editing across the http/https boundary.

The two key places I've noticed this are:

On the admin side, Insert/Edit Link doesn't work - it is failing to load http://example.com/displayable_links.js from within admin's https context.

On the main site side, Insert/Edit Image doesn't work with the Media Library browser, due to the fact that its slug is on the admin path (https://example.com/admin/media-library/browse/?pop=5&type=image)

**Comment by itztli** [comment]
I have the same problem. 

I can fix the second question adding in the setup the following line:
SSL_FORCE_URL_PREFIXES = ("admin", "/admin_keywords_submit")

However I can not solve the first one. I believe that displayable_links.js is generated dynamically. Maybe the solution is change the url in order to move the request to admin/displayable_links.js

**Comment by itztli** [comment]
Thats works!

Add in the setttings file:
SSL_ENABLED = True
SSL_FORCE_URL_PREFIXES = ("secure","admin","admin_keywords_submit")

in urls.py add 
from mezzanine.core.views import displayable_links_js 
and add to urlpatterns:
url("^secure/displayable_links.js$",displayable_links_js,name="displayable_links_js"),

in static/mezzanine/js/tinymce_setup.js change:
link_list: '/secure/displayable_links.js',

Restart apache and clear your browser.

**Comment by stephenmcd** [comment]
I've just pushed changes that move all the admin related URLs to be under /admin/ prefix.

As for using live-editing on the main site, I think you have conflicting requirements there - you'll need to ensure your editors use the admin login on the SSL host, choosing site from the interface selector.

**Comment by stephenmcd** [comment]
And thanks @itztli for the pointers.
