### ISSUE TITLE
seeing duplicate inlines for site permissions using default mezzanine setup

### ISSUE THREAD

**Issue by dinopetrone** [stephenmcd/mezzanine#1366]
1. open admin
2. create new user
3. scroll down to add site permissions and see the following screenshot
https://www.evernote.com/l/AfdtYsctJHVOSq5HO7xHIFEBrOcASiYHSqAB/image.png

here is my pip freeze:

````
Django==1.8.3
Fabric==1.8.3
Mezzanine==4.0.0
Pillow==2.9.0
Pygments==1.6
South==0.8.2
amqp==1.4.5
anyjson==0.3.3
argparse==1.2.1
astroid==1.1.1
beautifulsoup4==4.4.0
billiard==3.3.0.20
bleach==1.4.1
boto==2.38.0
celery==3.1.18
chardet==2.3.0
coverage==3.7.1
dj-database-url==0.3.0
django-contrib-comments==1.6.1
django-debug-toolbar==1.3.0
django-extensions==1.5.5
django-grappelli==2.6.1
django-require==1.0.7
django-storages==1.1.8
django-tastypie==0.10.0
django-wysiwyg-redactor==0.4.5.1
djangorestframework==3.1.3
ecdsa==0.11
fancycompleter==0.4
filebrowser-safe==0.4.0
future==0.14.3
grappelli-safe==0.4.0
gunicorn==19.3.0
html5lib==0.999999
kombu==3.0.26
logilab-common==0.61.0
mimeparse==0.1.3
oauthlib==1.0.0
paramiko==1.12.4
pdbpp==0.7
psycopg2==2.6
pycrypto==2.6.1
pylint==1.2.1
pyrepl==0.8.4
python-dateutil==2.2
pytz==2015.4
pyuploadcare==1.2.14
requests==2.7.0
requests-oauthlib==0.5.0
six==1.9.0
sqlparse==0.1.11
tzlocal==1.2
virtualenv==1.11.6
wmctrl==0.1
wsgiref==0.1.2
```

I also went into mezzanine source to check admin settings for inline model and found they are configured correctly at first glance:
https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/admin.py#L295-L298

**Comment by stephenmcd** [comment]
Can confirm this, spent some time investigating but came up with nothing.

**Comment by dinopetrone** [comment]
I tested with django 1.7.9 and 1.7.8 and mezz 3.1.10
this bug exists in all of those cases

**Comment by orotau** [comment]
In a fork that I took at the end of May https://github.com/orotau/mezzanine
the bug does *not* exist.
If I do an F5 on the admin page, 2 inlines appear and then the bottom one disappears leaving everything as it should be.
I am running Django 1.77. I will upgrade to 1.78 and see if that changes anything and will report back.

**Comment by orotau** [comment]
I **can't** reproduce this with Django 1.7x
But as soon as I upgrade to 1.8 it appears
I wonder if it is something to do with
https://docs.djangoproject.com/en/1.8/releases/1.8/#django-contrib-sites

**Comment by ryneeverett** [comment]
I'm experiencing this as well, but in addition the user I create doesn't actually get any site permissions even if I add the site to both inlines. That is, if I don't make them a superuser and they try to log in they get 302'd with "You don't have permission to access the admin for this site."

```py
>>> SitePermission.objects.count()
Out[1]: 0
```

**Comment by stephenmcd** [comment]
> but in addition the user I create doesn't actually get any site permissions even if I add the site to both inlines

I can't reproduce this, works fine for me.

**Comment by ryneeverett** [comment]
@stephenmcd Thanks for the fix. My additional issue is resolved by inputting the machine's `hostname` rather than the domain name, which I find perplexing.

**Comment by stephenmcd** [comment]
Sounds like you have a misconfigured web server in front of the Django app.
