### ISSUE TITLE
4.0.0 is no longer available

### ISSUE THREAD

**Issue by spookylukey** [stephenmcd/mezzanine#1368]
$ pip install Mezzanine==4.0.0
      Could not find a version that satisfies the requirement Mezzanine==4.0.0 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.4, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.9, 0.9.1, 0.10, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.11, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.11.6, 0.11.7, 0.11.8, 0.11.9, 0.11.10, 0.12, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.10, 4.0.1)
      Some externally hosted files were ignored as access to them may be unreliable (use --allow-external Mezzanine to allow).
    No matching distribution found for Mezzanine==4.0.0

Is this intended?

**Comment by stephenmcd** [comment]
I had to remove it with the intention of rebuilding/reuploading but pypi seems to not allow it.Any idea how to? (Closing this either way, yes it was intentional).

**Comment by spookylukey** [comment]
OK, that's fine.

From what I know, you cannot change a released version. And if you delete one, you can't re-upload: https://mail.python.org/pipermail/distutils-sig/2015-January/025683.html
