### ISSUE TITLE
Basic installation issue

### ISSUE THREAD

**Issue by AlbatrossArchive** [stephenmcd/mezzanine#1371]
Hi there,

I'm trying to follow the basic installation guide found here (http://mezzanine.jupo.org/docs/overview.html#installation). 

When I run:

$ python manage.py createdb --noinput

I get the below error:

Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    from mezzanine.utils.conf import real_project_name
ImportError: No module named mezzanine.utils.conf

I've definitely installed Mezzanine (via "pip install mezzanine") but am am getting no further.

This seems like such a basic issue and I much be missing something obvious, so any help identifying what that is would be greatly appreciated!

Cheers,

Rich

**Comment by stephenmcd** [comment]
You should post this to the mailing list

**Comment by derekdickerson** [comment]
I get the same thing

**Comment by djdeo** [comment]
Run it in virtualenv

**Comment by iris9112** [comment]
I had the same error, and I'm running in virtualenv. I upgrade django version, but it not worked :( some idea?

**Comment by kenbolton** [comment]
Use the mailing list if you need help, please. Locking this conversation.
