### ISSUE TITLE
Adding image to text causes newline issues

### ISSUE THREAD

**Issue by shadowym** [stephenmcd/mezzanine#1377]
I am running the latest current production release of Mezzanine.

I have a strange issue when I add images to text.  I am doing all this via TinyMCE.  Everything appears correct in TinyMCE.   Viewing the webpage is when you see the incorrect formatting.

If I view the source in Tinymce it looks like this

```
<p>asdfasdf<br />asdfasdf<br />asdfasdf<br />asdfasdf</p>
<p><img src="/static/media/uploads/django-logo.jpg"</p>
```

I verified it is also saved into the database this way

When I view the website in any browser there are additional line breaks added.  One for each existing linebreak already there.  

So the source in the browser is as follows:

```
<p>
asdfasdf
<br>
asdfasdf
<br>
asdfasdf
<br>
<br>
</p>
<p>
<img src="/static/media/uploads/django-logo.jpg">
</p>
````

See the 2 additional linebreaks added at the end of the first paragraph.  They should not be there.  If I add a 3rd line of text with another linebreak in that first paragraph there would be 3 additional linebreaks added instead of 2 and so on.  If I remove the image in the second paragraph and just use regular text then everything appears normal again in the first paragraph with no additional linebreaks added.

I have tried various formatting tricks but so far haven't found a workaround.  I basically can't add images to my posts until I can fix this.

It doesn't matter where the image is in the text.  It could be several paragraphs down or up from the paragraph(s) with newlines.  As soon as you add it then all the newline formatting in every paragraph before and after will have the additional newlines added.  I tried different images and different image sizes and resizes.  That doesn't seem to matter either.

I disabled my theme and all my apps to verify it doesn't have anything to do with that either.  Content type is Blog Post but I have verified it happens with other content types.

**Comment by shadowym** [comment]
I installed from scratch on VM just running the demo site and development webserver and it still does it.  So this should be 100% reproducible.  Only difference between blog posts and other posts is where all the extra <br> tags get added.  On blog posts it's in the same paragraph as the newlines.  On other posts such as richtext they are all added at the end of the post.

**Comment by stephenmcd** [comment]
Thanks for the report - it's a side effect of the BeautifulSoup library we use to parse HTML before rendering it, in order to swap images out with thumbnails - I've pushed a fix.

**Comment by shadowym** [comment]
This appears to have solved the problem.  Thanks so much!

**Comment by IlianIliev** [comment]
Sorry for raising this one again but it is possible to have this as a hot-fix and add it to that last release. Otherwise I can always go with the master branch but I am not sure if it is stable enough.
Thanks for the great CMS btw )

**Comment by stephenmcd** [comment]
I'd suggest pinning to the latest commit on here - stability is fine.

**Comment by IlianIliev** [comment]
Thanks a lot )
