### ISSUE TITLE
site related models aren't dumped using dumpdata management command

### ISSUE THREAD

**Issue by dinopetrone** [stephenmcd/mezzanine#1378]
I googled around first so i'm hoping that i didn't miss it somewhere else.  When running `./manage.py dumpdata` none of the models that extend SiteRelated are present in the output.  If this is the case, i'm assuming the solve is a custom management command?

**Comment by dinopetrone** [comment]
aaaand i just realized you can pass the --all flag...closed!

**Comment by stephenmcd** [comment]
Cool! 

BTW, try the mailing list next time.

**Comment by dinopetrone** [comment]
will do, sorry about that
