### ISSUE TITLE
Bug positioning modal box with tinymce using inline editing 

### ISSUE THREAD

**Issue by Cajoline** [stephenmcd/mezzanine#1390]
Hi,
I found small problem when using the inline edition front end,
When I click once in the modal box is not centered and if i close it  and click a 2nd time the, the modal box moves to the left (see capture of official demo)

This problem occurs when editing content with **"wysiwyg editor"** not with **input text**

![img-1](https://cloud.githubusercontent.com/assets/3340303/9423601/7845c4fa-48cb-11e5-9183-fb4edb700406.png)
![img-2](https://cloud.githubusercontent.com/assets/3340303/9423602/785cb6f6-48cb-11e5-9682-693461e68065.png)

**Comment by stephenmcd** [comment]
The code for this changed within the last few days - please give that a try.

Hopefully that resolves it since I'm unable to reproduce this with the same browser that you're using.

**Comment by Cajoline** [comment]
Work perfectly with the Github last version
Thank you !
