### ISSUE TITLE
'tuple' object has no attribute 'day'

### ISSUE THREAD

**Issue by fygul** [stephenmcd/mezzanine#1391]
![attributeerror](https://cloud.githubusercontent.com/assets/8337939/9469915/0ee785ee-4b7c-11e5-8f17-bf383dbc4730.png)

**Comment by stephenmcd** [comment]
#1370

**Comment by steckerhalter** [comment]
hi! I'm getting the same error with enabled model translations. Could you tell me why the issue was closed? Is there some hidden message? ;)

**Comment by fygul** [comment]
@steckerhalter 
[#1370](https://github.com/stephenmcd/mezzanine/issues/1370)
[#1359](https://github.com/stephenmcd/mezzanine/issues/1359)
[modeltranslations break ORM datetimes() #324](https://github.com/deschler/django-modeltranslation/issues/324)

**Comment by steckerhalter** [comment]
@fygul thanks
