### ISSUE TITLE
EXTRA_MODEL_FIELDS cant refer to self in ForeignKey

### ISSUE THREAD

**Issue by ZeroXn** [stephenmcd/mezzanine#1395]
i was trying to add a parent category reference to blogcategory, but each time got and error such as
    `blog.blogcategory: 'parent_category' has a relation with model self, which has either not been installed or is abstract.`
i had to modify boot/\_\_init\_\_.py as mention at the link below, to get it to work
https://groups.google.com/forum/#!topic/mezzanine-users/CBqb6srpmqU

Is this a bug? or is there some other way to implement without modifying 'boot/\_\_init\_\_.py' directly?

**Comment by stephenmcd** [comment]
Sounds like you have some working code, please create a PR.

**Comment by ZeroXn** [comment]
ok np, i submtting it as pr #1396
