### ISSUE TITLE
Integration with Django 1.6.11

### ISSUE THREAD

**Issue by dtrinchet** [stephenmcd/mezzanine#1397]
Hi,

For some reason of majeure force I need to integrate Mezzanine into a Django 1.6.11 project, I'm wondering which is the most recent version of Mezzanine that is compatible with this version of Django. I appreciate any help around.

Thanks and kind regards

**Comment by jerivas** [comment]
Hi Dannier.

Mezzanine 3 was the last major version to support Django 1.6. You can
install it with:

pip install "mezzanine<4"

In the future, for general questions like this, please use the mailing
list. Thanks!

**Comment by dtrinchet** [comment]
Thanks @jerivas. I'm very grateful for.
