### ISSUE TITLE
FORMS_USE_HTML5 causes a migration

### ISSUE THREAD

**Issue by jerivas** [stephenmcd/mezzanine#1399]
Setting `FORMS_USE_HTML5 = True` will trigger a migration, because the `editable` attribute for the placeholder field in [models.py](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/forms/models.py#L68) depends on it.

It looks like the purpose behind the conditional `editable` is to easily show/hide the placeholder in the `Field` inline admin. Is that correct, or am I missing something?

**Comment by stephenmcd** [comment]
That's right - we should change it to not use `editable` and find a different way to show/hide the field.

**Comment by jerivas** [comment]
Seems like we can use `ModelAdmin.get_fields()` to check for `USE_HTML5` there. [Docs](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_fields).

**Comment by stephenmcd** [comment]
Or even just set `fieldsets` on `FieldAdmin`? That would be consistent with a lot of other admin classes we have.

**Comment by jerivas** [comment]
Or maybe something like this?

```python
field_fields = [all fields minus placeholder]
if html5:
   field_fields.insert('placeholder')
```
Then just assign that to `FieldInlineAdmin.fields`.

I like the `get_fields()` option because we can dynamically get all fields with a call to `super`, instead of manually defining each of them. Plus, we gotta start using those Django 1.7+ goodies, hahaha.

**Comment by stephenmcd** [comment]
Oh yeah, that's what I meant :-)

**Comment by stephenmcd** [comment]
I meant `fields` not `fieldsets` I mean.

I guess I like that better than overriding the method since that's how we've done it everywhere else, and that's the main API that Django offers.

**Comment by jerivas** [comment]
Got it. Will get a PR ready.

**Comment by foxwoods369** [comment]
Any update on this?

**Comment by jerivas** [comment]
Sorry guys, completely forgot about this. PR submitted.
