### ISSUE TITLE
Provide way to silence warnings

### ISSUE THREAD

**Issue by spookylukey** [stephenmcd/mezzanine#1400]
We have a valid reason to not include  `"mezzanine.core.middleware.SitePermissionMiddleware"` in our `MIDDLEWARE_CLASSES` (we use an alternative implementation), but this produces a warning that we can't silence:

https://github.com/stephenmcd/mezzanine/blob/c7bc3e74d8487c6b23417ac099a46aa5c486c369/mezzanine/utils/sites.py#L75

It would be nice if Mezzanine used Django's checks framework for issues like this:

https://docs.djangoproject.com/en/1.7/topics/checks/

In this way, a developer could silence this warning individually.

I'm happy to write a patch if this idea is accepted. There are probably a few other places this could be done, although for things like deprecation warnings, there is no need - there is a right way to silence the warning, which is to fix your code.

**Comment by stephenmcd** [comment]
Sounds good Luke, go for it.

**Comment by jerivas** [comment]
Looks like #1734 fixes this one. Closing.
