### ISSUE TITLE
django-autocomplete-light and jquery compatibility

### ISSUE THREAD

**Issue by kbytesys** [stephenmcd/mezzanine#1403]
I'm using often autocomplete light in my projects and I'm trying to use it with mezzanine.

First at all, I've noticed that the jquery loading broke the admin panel: you can't execute any action to selected rows, the event simple wasn't fired. No javascript errors or logs.

Just add this line to your admin/base_site.html 

```html
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.js" type="text/javascript"></script>
```

On inlines elements, autocomplete override the "add new" on bottom, but it is broken because of the override made from mezzanine. 

This third-part app works fine in grappelli, could you try to make it usable in mezzanine?

**Comment by stephenmcd** [comment]
Please post this to the mailing list.
