### ISSUE TITLE
PAGES_SLUG settings set to '' results in a wrong URL when page.get_absolute_url is called

### ISSUE THREAD

**Issue by vladir** [stephenmcd/mezzanine#1405]
Hello team,

  I have been trying to integrate `Mezzanine` into my project, and I have found a detail that I would like to improve on the framework. On `mezzanine.urls.py` we have this code:

# Mezzanine's Pages app.
    PAGES_SLUG = ""
    if "mezzanine.pages" in settings.INSTALLED_APPS:
        # No BLOG_SLUG means catch-all patterns belong to the blog,
        # so give pages their own prefix and inject them before the
        # blog urlpatterns.
        if blog_installed and not BLOG_SLUG:
            PAGES_SLUG = getattr(settings, "PAGES_SLUG", "pages").strip("/") + "/"
            blog_patterns_start = urlpatterns.index(blog_patterns[0])
            urlpatterns[blog_patterns_start:len(blog_patterns)] = patterns("",
                ("^%s" % str(PAGES_SLUG), include("mezzanine.pages.urls")),
            )
        else:
            urlpatterns += patterns("",
                ("^", include("mezzanine.pages.urls")),
            )

which results in that if the setting `PAGES_SLUG` is not set at all, the `URL` pattern of the pages will contain `pages/` as a prefix. I consider that a good idea, but what I would like to do is that if I set the `PAGES_SLUG = ''`, so that it does not add any prefix to my pages `URLs`, but in this moment if I do so it will include a '/' as a prefix, that at the end, when calling the `page.get_absolute_url` will return a `URL` like this `/%2F<page_slug>/`. I have thought in a solution for the code above:

    # Mezzanine's Pages app.
    PAGES_SLUG = ""
    if "mezzanine.pages" in settings.INSTALLED_APPS:
        # No BLOG_SLUG means catch-all patterns belong to the blog,
        # so give pages their own prefix and inject them before the
        # blog urlpatterns.
        if blog_installed and not BLOG_SLUG:
            PAGES_SLUG = getattr(settings, "PAGES_SLUG") if hasattr(settings, "PAGES_SLUG") else 'pages'
            PAGES_SLUG = PAGES_SLUG.strip("/") + "/" if PAGES_SLUG else ''
            blog_patterns_start = urlpatterns.index(blog_patterns[0])
            urlpatterns[blog_patterns_start:len(blog_patterns)] = patterns("",
                ("^%s" % str(PAGES_SLUG), include("mezzanine.pages.urls")),
            )
        else:
            urlpatterns += patterns("",
                ("^", include("mezzanine.pages.urls")),
            )

Well it is my suggestion for this, if this makes any sense to you that have been developing a great framework like this, of course ;). It perhaps would help some other developers that would like to have this as well ;). I could also do a Pull Request to include this, but better to hear if some others consider this useful :). Thanks in advance, and looking forward to improve any detail :).

**Comment by maniachhz** [comment]
I am  leanning the Mezzanine code now.

Actually,  if not BLOG_SLUG then add the pages to the slug.  If you can set PAGES_SLUG is ""  , the URL would not resolve the URL ("^%s" % BLOG_SLUG, include("mezzanine.blog.urls")).

**Comment by vladir** [comment]
Hi @maniachhz ,

   Thanks a lot for your response, and clarification. You are right about that, but I'm dealing with a case where I would like to have this:

    BLOG_SLUG = ''
    PAGES_SLUG = ''

It is the case I'm facing right now. Sorry, I should have set this detail on my original message.

Thanks again for your help. I really appreciate that.

**Comment by stephenmcd** [comment]
> I'm dealing with a case where I would like to have this:
> 
> BLOG_SLUG = ''
> PAGES_SLUG = ''

What happens when a page and a blog post have the same slug? If you want this you'll need to define your own view function that handles looking up both.

**Comment by vladir** [comment]
Thanks for your answer @stephenmcd , ok I will follow your suggestion, and I will then close this issue :). Thanks again for your help and your time
