### ISSUE TITLE
Form field with template rendered choices value

### ISSUE THREAD

**Issue by dsanders11** [stephenmcd/mezzanine#1408]
Currently the 'Drop down' and 'Multiple select' fields on forms will render the contents of default value in a template, but not choices.

It would be very useful to have a drop down field that can render the choices value so that the values can be dynamic, such as a dropdown with the choices value `{{ request.user.get_group_permissions|join:", " }}` would show the group permissions for the current user, or `{{ request.user.groups.all|join:", " }}` would list all groups for the user filling out the form.

Implementation is where this gets a little tricky. The Field model has a `get_choices()` method which returns the list of choices. This is also used to populate filters under view entries for a form as a list of check boxes, which is inherently incompatible with making the choice values dynamic.

Two possible implementations:
* Add a 'dynamic' boolean field to the Field model which would trigger the dynamic behavior for that choices field, and provide a filter under entries similar to a text field
* Add two new fields as dynamic variants of the choices fields which would subclass the Field model as a proxy model and change the behavior of `get_choices()`

Thoughts?

**Comment by stephenmcd** [comment]
Nice idea, but I think this would overcomplicate how the forms builder works, it's far too complicated already.
