### ISSUE TITLE
Using translate_url on 404 page

### ISSUE THREAD

**Issue by IlianIliev** [stephenmcd/mezzanine#1417]
If you try to call translate_url in your 404 template this results in 500 error.
The problem comes from this line https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/templatetags/mezzanine_tags.py#L678

Unfortunately I am not sure which ones is the best solutions but here are some options:
1) fail silently and return empty string
2) fail silently and return language url pointing to the root of the website e.g. /en/
3) accept a default URL to be translated in such cases e.g. {% translate_url 'de' '/de/my-page' %}
4) something else?

**Comment by stephenmcd** [comment]
It should return the URL to redirect to for the language selector right? If that's the case, homepage makes sense, no point in redirecting back to a translated 404.

**Comment by IlianIliev** [comment]
It should return the URL for a different language version of the current page.
E.g. if you are on page '/en/about-us/' it should return something like '/de/about-us/'

**Comment by stephenmcd** [comment]
> It should return the URL for a different language version of the current page.

Um, but we're talking about 404s - the page doesn't exist. Please re-read my first comment.

**Comment by IlianIliev** [comment]
Surry, but I got a bit confused so I will try to explain my self better:
Using {% `translate_url` <lang> %} we normally get URLs like '/<lang>/about-us/'
However if the user tries to access `/non-existing-url/` then {% `translate_url` <lang> %} will raise an exception - which for me is a bug because the 404 page turns into 500.
So I think a better behaviour will be something like:
1) fails silently and returns empty string e.g. ''
2) fails silently and return pointer to the URL root e.g. '/en/'
3) accept an extra argument that is used as a fallback URL e.g.
{% translate_url 'de' '/de/my-page' %} which returns '/de/my-page' only if the current URL does not exists.

**Comment by stephenmcd** [comment]
Can't reproduce this - 404 should resolve fine to the catch-all page urlpattern, which is what happens for me.
