### ISSUE TITLE
Disable translations fallback

### ISSUE THREAD

**Issue by IlianIliev** [stephenmcd/mezzanine#1418]
Currently if you setup the CMS to use multiple languages and then try to open a page that is missing translation for the current language there is automatic fallback to the default language.
E.g. page `/en/about/` `/de/about/` will show the same "en" content if there is not "de" translation.
I believe that this should be either configurable or should raise Http404 by default due to the missing translation.

**Comment by stephenmcd** [comment]
What you're talking about then is having different navigation structures per language, which is something you would implement by using multiple sites (with a site per language) rather than one site with multiple languages.

**Comment by stephenmcd** [comment]
BTW the mailing list is better suited for this kind of discussion.
