### ISSUE TITLE
Wrong robots.txt

### ISSUE THREAD

**Issue by bastichelaar** [stephenmcd/mezzanine#142]
Your robots.txt doesnt allow search engines to index the site...

**Comment by nragandap** [comment]
I've set modified for both settings.py and local_settings.py inside the main app directory but google search still cant index our site.  Is there anything else that needs to be configured aside from that two files?

**Comment by philipsouthwell** [comment]
From memory I think if DEBUG = True then it's not indexed. DEBUG = False
fixes it.  Maybe that's your problem?

**Comment by nragandap** [comment]
Hi Philip,  I already did that.  Debug was set to False.  Do I need to delete the robots.txt ?  its current value is 
"User-agent: *
Disallow:

I'm new with django and mezzanine so sorry for the very basic question

**Comment by stephenmcd** [comment]
Can you post this to the mailing list instead? Thanks.
