### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by xnx** [stephenmcd/mezzanine#1420]
The link in http://mezzanine.jupo.org/docs/frequently-asked-questions.html#homepage to the urls.py module, https://github.com/stephenmcd/mezzanine/tree/master/mezzanine/project_template/urls.py 404s. Perhaps it ought to be https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/project_template/project_name/urls.py

**Comment by stephenmcd** [comment]
4e750f559b9a42d881e8bef4f2092cf1550018ed
