### ISSUE TITLE
Blog archive doesn't load posts when the month slug is specified

### ISSUE THREAD

**Issue by Lovecannon** [stephenmcd/mezzanine#1425]
Hello Im using the latest version of Mezzanine installed through pip and I noticed when you use the blog archive feature it will load the posts when you specify the year (e.x. /blog/archive/2015) but if you specify the month (e.x. /blog/archive/2015/10) it won't load the posts. 

Does anybody what is going on? 

On a side note, I'm using Python 3.4 on Ubuntu 14.04 - and DEBUG is currently set to True.

**Comment by stephenmcd** [comment]
Works fine for me - but please, post this to the mailing list.
