### ISSUE TITLE
Redirection is not working for comment and rating when user is not authenticated and authentication is required to do that.

### ISSUE THREAD

**Issue by sonus21** [stephenmcd/mezzanine#1440]
In comment and rating view we have ```@require_POST``` which leads to a problem when user is not authenticated. Both views call a function ```initial_validation(request, prefix):```  which stores POST data in ```session``` and redirect for authentication once user has login then client request for ```/rating``` or ```/comment``` based on next parameter. As request is not POST so ```rating``` and ```comment``` view decline to serve request.

Fixed for this:
remove  ```@require_POST```  decorator from ```comment``` and ```rating``` view.

**Comment by stephenmcd** [comment]
Thanks!
