### ISSUE TITLE
Can't add image to Page, Uncaught TypeError: Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by seanmavley** [stephenmcd/mezzanine#1445]
Mezzanine 4.0.1
Django 1.8.5

Trying to add images to Page, but keep getting error a property is null. Likely an issue with the filebrowser package, however, I don't seem to know how to disable the filebrowser package.

![screenshot from 2015-10-28 23-11-07](https://cloud.githubusercontent.com/assets/5289083/10805993/ffd2cb38-7dc9-11e5-95e0-c25167f4e243.png)

**Comment by jerivas** [comment]
Hi Nkansah.

It looks like you're using a custom Page type, so this isn't really a Mezzanine bug. Please use the mailing list instead to ask for help with your particular project.

**Comment by seanmavley** [comment]
I'm sorry, but this isn't an issue about custom page types or not. Its about a mezzanine native package probably malfunctioning

![screenshot from 2015-10-28 23-26-58](https://cloud.githubusercontent.com/assets/5289083/10806202/6f6d4652-7dcb-11e5-9186-c2cbdd80200f.png)

**Comment by stephenmcd** [comment]
I just tried the feature you're talking about, and it works perfectly fine for me.

What @jerivas was saying is that you've written some custom code, and that's causing some issue - you can get help with that on the mailing list.

That conversation might end up highlighting an actual bug, but we're not there yet.

**Comment by seanmavley** [comment]
Okay, thanks

**Comment by romecode** [comment]
this happens when a new object is being created:
in the hosted mez. demo.
Go to Products->Add Product watch the console
this will come up typically in the same place of the template; right after the save actions

<script type="text/javascript">document.getElementById("").focus();</script>

**Comment by stephenmcd** [comment]
Was fixed in https://github.com/stephenmcd/grappelli-safe/commit/a65ef5743df48d77e2af8336b5cfae9b26fd222e

**Comment by seanmavley** [comment]
@stephenmcd Looking at the time the fix was applied, then it suggest there was actually a problem with grapelli, and not my custom page type or whatnot?

Good to know it is fixed now.

**Comment by stephenmcd** [comment]
Yep it was a problem with Grappelli.
