### ISSUE TITLE
Hide empty panels

### ISSUE THREAD

**Issue by macalicious** [stephenmcd/mezzanine#1452]
E.g. if I don't use the `mezzanine.twitter` app, and remove it from the `INSTALLED_APPS` list, the `cold-md-3 right` `div` is just showing an empty box. A workaround is to wrap `{% ifinstalled mezzanine.twitter %}` before the `<div class="panel panel-default">` in `core/templates/base.html` and  `{% endifinstalled %}` after the second div-Tag.

However, this seems little drastic and if another application wants to use the right panel, it wouldn't work anymore. So is there another fix for this?

**Comment by stephenmcd** [comment]
CSS I guess?

You're expected to the modify the templates.
