### ISSUE TITLE
TEMPLATE_LOADERS needs re-ordering to support app templates

### ISSUE THREAD

**Issue by go8ose** [stephenmcd/mezzanine#1453]
The documentation says you only need to put the new app in your INSTALLED_APPS above mezzanine apps. I think you also need to change TEMPLATE_LOADERS order.

I found that unless I changed the default TEMPLATE_LOADERS ordering (so django.template.loaders.app_directories.Loader preceeds django.template.loaders.filesystem.Loader) then specifying a new app to change the theme of the site didn't work.

**Comment by stephenmcd** [comment]
Don't think this has anything to do with Mezzanine.

**Comment by jerivas** [comment]
Hi Geoff. I've been theming Mezzanine for a while and adding your app to
INSTALLED_APPS before all Mezzanine stuff works fine from v1 to v4. This is
how Mezzatheme (the premium theme marketplace) works too, so there's that.

2015-10-31 21:38 GMT-06:00 Stephen McDonald <notifications@github.com>:

**Comment by go8ose** [comment]
Thanks @jerivas for the explanation. I'll go back and check what I did that made me think this might be a mezzanine bug.
