### ISSUE TITLE
Updatecachemiddleware setting wrong csrf token

### ISSUE THREAD

**Issue by bhaskar8088** [stephenmcd/mezzanine#1454]
Hi Guys,

I am not sure how much I am correct on this but I am facing a problem and on investigation, found that on stopping memcached or commenting out updatecachemiddleware, I am not facing issue.

In the allauth login page, csrf is set to different value in cookie and to a different value in <input element>.

I think value in cookie is set to correct one but value in input element(output of {% csrf_token %}) is being cached in wrong way.

Please let me know if its due to wrong configuration from my side.

**Comment by bhaskar8088** [comment]
I just checked and there is no issue with django admin login page. Seems I did something wrong.

**Comment by bhaskar8088** [comment]
Using nevercache tag solved the issue :)

{% load mezzanine_tags %}

{% nevercache %}
{% csrf_token %}
{% endnevercache %}

**Comment by stephenmcd** [comment]
Thanks for posting the solution. 

Next time please try the mailing list first.

**Comment by bhaskar8088** [comment]
Sure.
