### ISSUE TITLE
WYSIWYG editor missing and other fields bugged in the admin interface

### ISSUE THREAD

**Issue by dollydagr** [stephenmcd/mezzanine#1455]
Hi there,

I am experiencing an issue with multiple parts of the admin interface. 
Within the Pages and Blog posts sections to be more specific.

See how the "Add Blog post" interface is looking like, specifically the Content field (that should have been a WYSIWYG editor), Other posts and Meta data fields (that should have been clickable and expandable):
![mezzanine_wysiwyg_editor_missing](https://cloud.githubusercontent.com/assets/5702387/10959567/1f2783ba-8348-11e5-8c2a-f865470f79f9.jpg)

In the Pages section, selecting a page type from the dropdown (e.g. add Form) does nothing. 

This all happened after I upgraded Mezzanine to 4.0.1 (plus a bunch of others packages just to be able to install Pillow without errors!) on a Debian Jessie server. Other package info:
- Python - 2.7.10+
- Django - 1.8.6
- Web app running inside a virtualenv (created with virtualenvwrapper)

Any clue where the issue could come from?
Any help would be so very much appreciated!

Thanks in advance!
Dollydagr

**Comment by stephenmcd** [comment]
Hi, it sounds like you've a problem hosting static JavaScript files, but please post this to the mailing list instead.
