### ISSUE TITLE
SSL enabled doesn't secure admin

### ISSUE THREAD

**Issue by henri-hulski** [stephenmcd/mezzanine#1456]
At least when using multible languages, setting `SSL_ENABLED` to `true` doesn't force the admin to use https.
The reason is because the default value for `SSL_FORCE_URL_PREFIXES` is:
```python
("/admin", "/account")
```
but the admin in multilanguage sites uses the slug `/de/admin` or similar.

**Comment by itztli** [comment]
I have the same problem.
I added the prefix 'es/' and 'en' for each entrance in SSL_FORCE_URL_PREFIXES, but I think that should be automatic.
