### ISSUE TITLE
UnicodeEncodeError in Gallery

### ISSUE THREAD

**Issue by joshglenn** [stephenmcd/mezzanine#1458]
So I just installed a mezzanie project for the first time. The server is running Ubuntu 14.04 and serving files with Apache. I'm getting this error when I try to go to the gallery. Also, the same error occurs if I browse to one of my pages that have unicode text in the url field. Any idea where to start with diagnosing this?

```
UnicodeEncodeError at /admin/galleries/gallery/8/
'ascii' codec can't encode characters in position 61-62: ordinal not in range(128)
```

```
Unicode error hint

The string that could not be encoded/decoded was: ery/A╠üvila,
```

**Comment by joshglenn** [comment]
FYI. I'm running mezzanie with Python 3.4. Is it possible there is a compatibility issue there?

**Comment by jerivas** [comment]
Most likely a locale issue in Apache. Make sure you have setup your locale correctly in your Apache config.

I don't think this is a bug unless you can reproduce it in the development server. Could you check that?

**Comment by jerivas** [comment]
This is what I mean with setting your locale correctly in Apache: https://docs.djangoproject.com/en/1.8/howto/deployment/wsgi/modwsgi/#if-you-get-a-unicodeencodeerror

**Comment by joshglenn** [comment]
In the ```envvars``` file, apache's locale settings were already set like that.

And no, I am not able to reproduce it. It works fine on the testing server. Any idea where to go from here?

My apache webserver are behind a nginx reverse proxy (i.e. - request come to nginx then get reverse proxy'd to the apache webserver (both running on the same box). Could nginx be affecting this you think?

**Comment by joshglenn** [comment]
I added the ```LANGUAGE=en_US:en``` to the locale settings then rebooted the server. It's working now. Don't know if it was the setting or the reboot that did the trick. Anyway, this wasn't a problem with mezzanine, but rather a server configuration issue. Thanks.
