### ISSUE TITLE
Importing tags from wordpress

### ISSUE THREAD

**Issue by mayoroftuesday** [stephenmcd/mezzanine#1459]
I had an issue importing tags from wordpress. The export file from wordpress marks tags as
    <category domain="post_tag" nicename="ask-a-doctor"><![CDATA[ask a doctor]]></category>
but your import is looking for terms["tag"]. Change it to terms["post_tag"] and it works fine.

This is in import_wordpress.py, line 108.

**Comment by stephenmcd** [comment]
Can you crete a PR with the fix? 

Thanks!
