### ISSUE TITLE
Blog feed descriptions are wrapped in b''

### ISSUE THREAD

**Issue by freb** [stephenmcd/mezzanine#1461]
I noticed on my own blog and confirmed at one the [mezzanine demo site](http://mezzanine.jupo.org/blog/feeds/rss/) that the content of `<description>` tag is wrapped in `b''`. For example you will see:

    <description>b'this my description'</description>

I tracked that back to `absolute_urls` and `thumbnails` RICHTEXT_FILTERS. It appears to be happening when the `str` function from `future.builtins` is applied to the html parsed with BeautifulSoup: <https://github.com/stephenmcd/mezzanine/blob/280642c8d0e7e41b90398c974a15533f6df20049/mezzanine/utils/html.py#L42>

I'm not familiar enough with Python3 yet to know the best way to remove the wrapping on printout or know exactly what type of string encoding the html variable is in.

**Comment by sjkingo** [comment]
Typically one just does:

```
>>> str(b'this was bytes', 'utf-8')
'this was bytes'
```

But I'm not sure if hardcoding the encoding to utf-8 is a good idea...

**Comment by stephenmcd** [comment]
Thanks guys for the feedback, just pushed a fix.
