### ISSUE TITLE
Django 1.9 compatability

### ISSUE THREAD

**Issue by pahaz** [stephenmcd/mezzanine#1464]
Hi, do you have any plans for support new django version?

**Comment by jerivas** [comment]
Work on new Django versions starts when they are released as stable. I'm going to leave this issue open for now to track progress in the future, but no work is being done AFAIK.

**Comment by stephenmcd** [comment]
Having said that, the RCs are usually close to what the final will look like, so no harm in testing now and getting the usual round of fixes in sooner than later.

**Comment by auvipy** [comment]
+python 3.5 support as it is supported in django 1.8 and 1.9

**Comment by sjkingo** [comment]
@auvipy Please see [here (mezzanine)](https://github.com/stephenmcd/mezzanine/pull/1476) and [here (cartridge)](https://github.com/stephenmcd/cartridge/pull/274) for Python 3.5 support.

It already works out of the box with the latest master of each.

**Comment by hx0day** [comment]
https://www.djangoproject.com/weblog/2015/dec/01/django-19-released/

**Comment by auvipy** [comment]
issue is fixed then :dancer:

**Comment by auvipy** [comment]
1.9.1 released

**Comment by stephenmcd** [comment]
75f97e1cbd0073950b205262615508118ef90d5f
