### ISSUE TITLE
FileField renders as type='text' in template

### ISSUE THREAD

**Issue by seanmavley** [stephenmcd/mezzanine#1465]
In admin, the FileField brings up popup nicely to choose image for a field. 

In my template, say form.html, FileField is rendered as input element but with type='text', making uploading not possible.

Any way to get same behavior as in admin but then in my own templates? Or at least, fall back to mere input type='file'?

**Comment by stephenmcd** [comment]
Please wait for an answer on the mailing list where you've already asked this.

**Comment by seanmavley** [comment]
Likely, there's been a fix applied. If not, any update on the above? The mailing list question I raised happened to offer no solution.

https://groups.google.com/d/msg/mezzanine-users/2TT4SVUCYc8/zSbRi974AQAJ
