### ISSUE TITLE
http return 302 redirect when i click button to upload file from ADMIN

### ISSUE THREAD

**Issue by woshicainiao** [stephenmcd/mezzanine#1482]
Python 2.7. Mezzazine version 4.01.
os. windows7
#model
    image = FileField(verbose_name=_("Upload Image"),upload_to=upload_to("demoapp.Article.image", ‘uploads/%Y%m/%d’),format="Image", max_length=255, null=True, blank=True)

#html
    javascript:FileBrowser.show('id_image', '/admin/media-library/browse/?pop=1&dir=uploads\201512\07&type=Image');

windows CMD:
"GET /admin/media-library/browse/?pop=1&dir=uploads%C2%81512%07&type=Image HTTP/1.1" 302 0
 "GET /admin/media-library/browse/?type=Image&pop=1 HTTP/1.1" 200 27872

**Comment by stephenmcd** [comment]
Dynamic upload directories aren't supported with the filebrowser field - you might like to use the regular Django file field which does.

**Comment by woshicainiao** [comment]
Thank you very much.
