### ISSUE TITLE
Improvement: ADMIN_SITE_TITLE setting

### ISSUE THREAD

**Issue by dharmagetic** [stephenmcd/mezzanine#1486]
I wanted to change the site title in the admin panel in the top left corner. Page http://mezzanine.jupo.org/docs/configuration.html this is not set, there is SITE_TITLE, but she is responsible for page title. I was able to do it only manually by copying the template Grapelli and changing the text. This approach is not very flexible. Can anything be done ?

**Comment by henri-hulski** [comment]
:+1

**Comment by henri-hulski** [comment]
:+1:

**Comment by stephenmcd** [comment]
This has been discussed previously.
