### ISSUE TITLE
Editable modal facing compatibility issues

### ISSUE THREAD

**Issue by derek-adair** [stephenmcd/mezzanine#1497]
I'm using the jquery [slidebars](http://plugins.adchsm.me/slidebars/) plugin and it is conflicting with the editable modal css.  The modal appears *behind* the expose overlay.  I haven't nailed the exact conflicts yet but there is an issue with [line 63 (sets site container z index to 1) and lines 208-211 (css transformation).](https://github.com/adchsm/Slidebars/blob/master/dist/0.10.3/slidebars.css)

Removing both of these lines causes the form to appear *in front* of the overlay again, but it is out of position.  Unsure what the best solution would be as i've not had time to dig into this one.  Either making the CSS more durable or it seems like moving the rendered HTML for the modal *outside* of the site container may be a good idea.

It should be pretty easily replicable by installing the slidebars plugin, but i can provide screens and code snippets if that helps.

Cheers!

**Comment by stephenmcd** [comment]
I don't think this is a Mezzanine issue so can you post the question to the mailing list instead? Thanks.

**Comment by derek-adair** [comment]
IMO a core function shouldn't break when including 3rd party scripts/styles... I can dig deeper to confirm this is whats going on, it *could* be how I have structured the html in combination with the plugin, but even still thats not very user friendly.

**Comment by stephenmcd** [comment]
The main point to realise is that there are literally an *unlimited* number of variations of HTML/CSS/JS that could conflict with the live-editing overlays somehow, it's impossible for it to be bullet-proof.

So we could either play cat and mouse and tweak it each time a situation like this comes up, or instead point out to users that they can get things working in their own project by applying their own specific fixes to it that will deal with their own scenario.

**Comment by derek-adair** [comment]
That's completely fair, however, I see some (presumably) simple CSS scoping fixes that would make it more durable.  Simply wrapping the .editable-form in a div#editable-container and appending it to the body instead of *before* the original text would help.  This would greatly minimize the risk of other styles / scripts bleeding in.  

Although, i'm unsure of the side-effects/regressions this may cause as i've not really looked that closely with how the editable form works.

Would you be open to a PR with me making this component more durable?

**Comment by stephenmcd** [comment]
If it's *demonstrably* a general improvement and not just a one-off fix for some plugin, then please go ahead, that would be great.

Thanks a lot!

**Comment by derek-adair** [comment]
Yup, i'll isolate a couple test cases and make sure all the bases are covered.
