### ISSUE TITLE
Mezzanine 4.0.1 installs Django1.9c1 by default

### ISSUE THREAD

**Issue by wimfeijen** [stephenmcd/mezzanine#1498]
Django==1.9c1 release candidate 1 is installed when using Mezzanine 4.0.1. 

django>=1.7,<1.9 defaults to 
Django==1.9c1 

Not sure whether Django's marks are right here, but we can solve this problem by specifying an exact Django release here.

**Comment by stephenmcd** [comment]
Not sure what you've done, but this works as expected and installs Django 1.8.7.

Could be a pip bug, PyPI issue, some other dependency, or user error - but it's not a Mezzanine issue, you'll need to work it out.

**Comment by wimfeijen** [comment]
Thanks for looking into it!

I've no idea as well, glad that it seems to be working.

On 21 December 2015 at 12:35, Stephen McDonald <notifications@github.com>
wrote:

> Not sure what you've done, but this works as expected and installs Django
> 1.8.7.
>
> Could be a pip bug, PyPI issue, some other dependency, or user error - but
> it's not a Mezzanine issue, you'll need to work it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stephenmcd/mezzanine/issues/1498#issuecomment-166278400>
> .
>



-- 
Wim Feijen
Eigenaar

Tussen kerst en oud en nieuw zijn wij gesloten.

Go2People Websites
Nieuwe Herengracht 49
1011 RN Amsterdam

T:  020 737 0378 / 06 1111 3316
W: http://go2people-websites.nl
