### ISSUE TITLE
Urls of links are hidden when those urls appear in my urls.py

### ISSUE THREAD

**Issue by wimfeijen** [stephenmcd/mezzanine#1499]
Hi, 

Today I was surprised to find that when editing an existing Link, that the url field disappeared. After some experiments, I found that it occurs only if that specific url appears in my urls.py. 

I'm not sure wether this behavior was intended. It surprised me and if it was indeed intended, I'd like a setting to toggle it. In my use case I just want to change a link.

**Comment by stephenmcd** [comment]
> I'm not sure wether this behavior was intended.

Then can you post these questions to the mailing list first instead of opening issues? 

Thanks
