### ISSUE TITLE
Page.meta_title returns .titles not .title if no ._meta_title

### ISSUE THREAD

**Issue by orutherfurd** [stephenmcd/mezzanine#1502]
We're trying to use Meta data Title to override Page Title, but it's not behaving as documented in the admin ("Optional title to be used in the HTML title tag. If left blank, the main title field will be used.").  What I'm seeing is that "page.meta_title" returns page._meta_title or str(self) which is returning Page.titles -- a " / " delimited string of titles (e.g. "Parent Title / Child Title").

**Comment by stephenmcd** [comment]
This isn't a bug, if you have a question can you post it to the mailing list instead? Thanks
