### ISSUE TITLE
thumbnail function doesn't work

### ISSUE THREAD

**Issue by woshicainiao** [stephenmcd/mezzanine#1503]
import os
	from os.path import getsize
	from django.conf import settings
	from django.test import TestCase

	from mezzanine.core.templatetags.mezzanine_tags import thumbnail

	class TestImageThumbnails(TestCase):

		def setUp(self):
			pass

		def test_thumbnail_generation(self):
			image_url = 'test.jpg'
			thumb_path = os.path.join(settings.MEDIA_ROOT, 'test_space/')
			image_file = os.path.join(settings.MEDIA_ROOT, 'test_space/test.jpg')
			with open(image_file, 'r') as f:
				image = f.read()
			new_thumbnail = thumbnail(image_url, 100, 100)
			self.assertEqual(new_thumbnail, 'test-100x100.jpg')
			self.assertNotEqual(0, getsize(os.path.join(thumb_path, newthumbnail)))

test
=======
[root@iZ23q3f5qlxZ app]# python manage.py test book.tests.TestImageThumbnails.test_thumbnail_generation
Creating test database for alias 'default'...
F
 ======================================================================
FAIL: test_thumbnail_generation (book.tests.TestImageThumbnails)
 ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/mezzanine-demo/app/book/tests.py", line 22, in test_thumbnail_generation
    self.assertEqual(new_thumbnail, 'test-100x100.jpg')
AssertionError: 'test.jpg' != 'test-100x100.jpg'

 ----------------------------------------------------------------------
Ran 1 test in 0.744s

FAILED (failures=1)
Destroying test database for alias 'default'...

sys
===
python2.7 
centos5.10 
django1.8.4 
mezzanie4.0.1

easy_install.pth
======================================================================
import sys; sys.__plen = len(sys.path)
./setuptools-0.6c11-py2.7.egg
./Django-1.8.4-py2.7.egg
./MySQL_python-1.2.3-py2.7-linux-x86_64.egg
./lxml-3.1.2-py2.7-linux-x86_64.egg
./django_allauth-0.23.0-py2.7.egg
./django_debug_toolbar-1.3.2-py2.7.egg
./sqlparse-0.1.17_dev-py2.7.egg
./tornado-4.2.1-py2.7-linux-x86_64.egg
./certifi-2015.09.06.2-py2.7.egg
./backports.ssl_match_hostname-3.4.0.2-py2.7.egg
./SQLAlchemy-1.0.8-py2.7-linux-x86_64.egg
./South-1.0.2-py2.7.egg
./django_summernote-0.6.16-py2.7.egg
./six-1.10.0-py2.7.egg
./Willow-0.2.1-py2.7.egg
./Unidecode-0.04.18-py2.7.egg
./html5lib-0.999-py2.7.egg
./beautifulsoup4-4.4.1-py2.7.egg
./pip-7.1.2-py2.7.egg
./djangorestframework-3.2.4-py2.7.egg
./django_treebeard-3.0-py2.7.egg
./django_modelcluster-1.0-py2.7.egg
./django_compressor-1.5-py2.7.egg
./pytz-2015.6-py2.7.egg
./django_appconf-1.0.1-py2.7.egg
./django_tinymce-2.0.5-py2.7.egg
./tzlocal-1.2-py2.7.egg
./django_celery-3.1.17-py2.7.egg
./celery-3.1.19-py2.7.egg
./kombu-3.0.32-py2.7.egg
./billiard-3.3.0.22-py2.7-linux-x86_64.egg
./amqp-1.4.8-py2.7.egg
./anyjson-0.3.3-py2.7.egg
./future-0.15.2-py2.7.egg
./django_model_utils-2.4-py2.7.egg
./django_contrib_comments-1.6.2-py2.7.egg
./bleach-1.4.2-py2.7.egg
./chardet-2.3.0-py2.7.egg
./requests_oauthlib-0.6.0-py2.7.egg
./requests-2.9.0-py2.7.egg
./oauthlib-1.0.3-py2.7.egg
./mots_vides-2015.5.11-py2.7.egg
./django_mptt-0.7.4-py2.7.egg
./django_ckeditor-5.0.2-py2.7.egg
./django_tagging-0.4-py2.7.egg
./django_braces-1.8.1-py2.7.egg
./Pillow-2.9.0-py2.7-linux-x86_64.egg
./python_memcached-1.57-py2.7.egg
import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)

**Comment by stephenmcd** [comment]
There exists thumbnail tests already and they're currently passing, so the issue you have is likely related to your own code and environment. If you'd like help troubleshooting that, please post your question to the mailing list.
