### ISSUE TITLE
Possible security risk due to autocomplete enabled at login form

### ISSUE THREAD

**Issue by mikevmk** [stephenmcd/mezzanine#1508]
There is some possible security risk with keeping autocomplete="on" (the default behavior) for sensible fields like password at /admin login form. Maybe disable it by default at mezzanine/core/templates/admin/login.html?

[login.html.diff.txt](https://github.com/stephenmcd/mezzanine/files/82747/login.html.diff.txt)

**Comment by stephenmcd** [comment]
Don't think there's anything to do here.
