### ISSUE TITLE
Trouble with trans template tag

### ISSUE THREAD

**Issue by zruu** [stephenmcd/mezzanine#1511]
I experiencing some trouble using the trans tag in my templates. See StackOverflow quesition here: http://stackoverflow.com/questions/34710043/how-to-declare-variables-inside-django-templates

What could be the cause of this?

**Comment by jerivas** [comment]
The link you shared is missing a dot after stackoverflow.

Also, I don't think this is a Mezzanine bug, so please use the mailing list
for general questions like this. Thanks!
