### ISSUE TITLE
AttributeError at /admin/media-library/upload_file/

### ISSUE THREAD

**Issue by jeweber** [stephenmcd/mezzanine#1518]
Problem with file upload and filebrowser-safe 0.4.2. filebrowser-safe 0.4.1 works fine.

AttributeError at /admin/media-library/upload_file/
'InMemoryUploadedFile' object has no attribute 'rfind'

Environment:

Request Method: POST
Request URL: http://xx.xx.xx/admin/media-library/upload_file/

Django Version: 1.9.1
Python Version: 2.7.9
Installed Applications:
(u'mezzanine.boot',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.redirects',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.pages',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.galleries',
 u'mezzanine.twitter',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django_comments')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware')

Traceback:

File "/srv/xxx/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/srv/xxx/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/srv/xxx/local/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/srv/xxx/local/lib/python2.7/site-packages/filebrowser_safe/decorators.py" in decorator
  25.         return function(request, *args, **kwargs)

File "/srv/xxx/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/srv/xxx/local/lib/python2.7/site-packages/filebrowser_safe/views.py" in _upload_file
  326.             if not get_file_type(filedata):

File "/srv/xxx/local/lib/python2.7/site-packages/filebrowser_safe/functions.py" in get_file_type
  206.     file_extension = os.path.splitext(filename)[1].lower()

File "/srv/xxx/lib/python2.7/posixpath.py" in splitext
  105.     return genericpath._splitext(p, sep, altsep, extsep)

File "/srv/xxx/lib/python2.7/genericpath.py" in _splitext
  91.     sepIndex = p.rfind(sep)

Exception Type: AttributeError at /admin/media-library/upload_file/
Exception Value: 'InMemoryUploadedFile' object has no attribute 'rfind'

**Comment by stephenmcd** [comment]
See https://github.com/stephenmcd/filebrowser-safe/issues/57
