### ISSUE TITLE
Multiple upload doesn't work in Chromium

### ISSUE THREAD

**Issue by michalfita** [stephenmcd/mezzanine#1521]
I have Mezzanine 4.0.1 installed and when I used it from Chromium 49.0.2598.0 (64-bit) I'm unable to upload several pictures at a time. This works on Firefox for the same site on my computer in the office.

**Comment by stephenmcd** [comment]
You probably don't have flash installed in Chrome.

Please use the mailing list if you have any other queries like this.

**Comment by michalfita** [comment]
It's not a query, it's bug report. If this is Flash based, then it's junk these days. Modern browsers support multiple uploads in HTML5 without a need to use Flash.

Let's treat this issue as feature request for adding a Flash-less support of adding multiple files. I'm not going to use Flash anymore as this slows down browsers are is serious security threat.

Thanks.

**Comment by derek-adair** [comment]
+1 for using html5 upload. 

about a year ago I did some extensive research on various open source projects that solve ajax/multiple uploads seamlessly and [plupload](http://www.plupload.com/) is where its at.  However, i'm pretty sure mezzanine project relies on the grappelli admin extension to upload, so this issue may be filed into the wrong project!

**Comment by michalfita** [comment]
Yep, pluload looks nice.

Mezzanine doesn't use original grapelli, but it's fork grapelli_safe. The
upload is in fact handled by filebrowser_safe, which is fork of
django-filebrowser. I don't think Stephen would want to return of
django-filebrowser ever.

Regards / Pozdrawiam,
Michał Fita

2016-02-02 16:49 GMT+00:00 Derek <notifications@github.com>:

**Comment by derek-adair** [comment]
I'll play around with plupload in mezzanine some time and see if its an easy drop-in replacement.

**Comment by michalfita** [comment]
I don't think it make much sense, as Stephen yesterday merged a fix in
filebrowser_sage project to handle HTML5 multiple uploads.

Regards / Pozdrawiam,
Michał Fita

2016-02-03 15:59 GMT+00:00 Derek <notifications@github.com>:

**Comment by derek-adair** [comment]
oh, i missed that!
