### ISSUE TITLE
Default settings are susceptible to weak DH/logjam attack on SSL

### ISSUE THREAD

**Issue by douglaskastle** [stephenmcd/mezzanine#1528]
When I run the default website against the ssl analysis website:

https://www.ssllabs.com/ssltest/analyze.html

I get this warning:

```
This server supports weak Diffie-Hellman (DH) key exchange parameters
```

This is as a result of weak keys being used for the DH key exchange and is what is responsible for the Logjam attack:

https://weakdh.org/
https://en.wikipedia.org/wiki/Logjam_(computer_security)

As this is preliminary find I feel this is too early to create a check in with a pull requests as I am not too sure the best place to put this fix.  

The details of the fix to a server are captured here:

https://www.howtoforge.com/tutorial/how-to-protect-your-debian-and-ubuntu-server-against-the-logjam-attack/

For me I added this extra line to the nginx.conf.template file:

```
%(ssl_disabled)s ssl_dhparam /etc/ssl/private/dhparams.pem;
```

And added this extra task to the fabfile, and called the task out independently of install or deploy.  Maybe this piece of code can be merged into the location where the keys for the server are generated. The final upload_template_and_reload can probably be removed, it was just required as a function the task, dh, being on its own.

```
@task
@log_call
def dh():
    ssl_private = "/etc/ssl/private"
    if not exists(ssl_private):
        sudo("mkdir -p %s" % ssl_private)
        sudo("chmod 710 %s" % ssl_private)
    dh_file = ssl_private + "/dhparams.pem"
    if not exists(dh_file, use_sudo=True):
        sudo("openssl dhparam -out %s 2048" % dh_file)
        sudo("chmod 600 %s" % dh_file)

    for name in get_templates():
        upload_template_and_reload(name)
```

**Comment by stephenmcd** [comment]
I think it's ok to go ahead with the PR - the location of the code for generating the key sounds good too. Please ensure there are some comments in the code explaining what's going on, even if it's just a sentence with a link to this issue.

Thanks a lot for your help.

**Comment by douglaskastle** [comment]
OK I have created a PR.  However I am a little concerned this is only of use for new projects and the lessons learned are not being percolated into existing projects.  This where my reticence to just add it straight to the fabfile. 

I think I will type up some of my findings and recommendations on the google group should any existing users find they need to fix these security related issues.

**Comment by jerivas** [comment]
Closing as we no longer support Fabric deployments
