### ISSUE TITLE
This page is disordered

### ISSUE THREAD

**Issue by andrew66** [stephenmcd/mezzanine#1543]
![mezzanine_search](https://cloud.githubusercontent.com/assets/5152134/13271887/0bc2b820-dad3-11e5-8002-5c9634a9b137.png)

**Comment by pedromorgan** [comment]
Newbie here going through bugs??

What is "dissordered" ?

**Comment by stephenmcd** [comment]
It's a very lacking repot - my guess is it's the search box overlapping the documentation.

**Comment by stephenmcd** [comment]
Can't reproduce this in Firefox or Chrome.
