### ISSUE TITLE
Fabfile settings should be updated to replace 'syncdb' with 'makemigrations. 

### ISSUE THREAD

**Issue by tkovalsky** [stephenmcd/mezzanine#1546]

**Comment by stephenmcd** [comment]
1) `syncdb` is already removed from the fabfile in development
2) `makemigratons` is a development task, not a deployment task (presumably you're thinking of `migrate`, which is in the fabfile)

If you're unclear, please try the mailing list before opening an issue.

**Comment by tkovalsky** [comment]
I thought Syncdb is a deprecated feature of django in 1.9

**Comment by stephenmcd** [comment]
> I thought Syncdb is a deprecated feature of django in 1.9

That's right.

**Comment by tkovalsky** [comment]
thanks - was hoping you could help give me a quick tip - would the dev
workflow be to make updates local, then deploy to my server using fab
deploy?

have a good weekend.

Best regards,

Todd Kovalsky
917-601-4103
