### ISSUE TITLE
Free themes website is down

### ISSUE THREAD

**Issue by KeithCu** [stephenmcd/mezzanine#1552]
From the main page:
http://mezzanine.jupo.org/
Click on the free themes (http://thecodinghouse.in/themes/) and see the 404.

**Comment by KeithCu** [comment]
Here also has invalid link: http://mezzanine.jupo.org/docs/overview.html

**Comment by stephenmcd** [comment]
#1551

**Comment by KeithCu** [comment]
I looked at the diff for #1551 at it seems like a different issue. Are you sure you meant to close this?

**Comment by stephenmcd** [comment]
It was #1550
