### ISSUE TITLE
Why is the admin panel sidebar a .dropdown-menu?

### ISSUE THREAD

**Issue by GeoTob** [stephenmcd/mezzanine#1554]
Just wondering why the admin panel sidebar is defined as a `.dropdown-menu` in `templates/admin/include/dropdown_menu.html`? It seems semantically wrong and breaks compatibility with other apps that try to use and style dropdown menus ?

I suspect that I may be missing an obvious reason for using dropdown-menu? If not, I'm happy to submit a patch later this week.

**Comment by jerivas** [comment]
I think this is because several versions back, the admin menu was a 
dropdown menu (not a sidebar as you see today). I guess that only the 
styles got re-written without actually changing the class names.

Let's see what others have to say.

**Comment by stephenmcd** [comment]
I don't have the answer off hand, but this should be posted to the mailing list instead, thanks.

**Comment by stephenmcd** [comment]
I misread your issue as a question not a bug, and yes please submit a patch, thanks.

**Comment by GeoTob** [comment]
i must admit it wasn't clearly worded @stephenmcd . Will submit something later this week.
