### ISSUE TITLE
Feature Request - Upgrade Documentation

### ISSUE THREAD

**Issue by vwbusguy** [stephenmcd/mezzanine#1561]
As of now, for upgrades, I've been using pip, doing database migrations, collecting static (I've made all my js/css customizations in separate files), and then manually merging any project files (settings, manage, urls, etc.) or template updates (mainly bootstrap markup compliance).

The information on upgrading is primarily found on blog posts outside of the core documentation, such as http://bitofpixels.com/blog/upgrading-to-mezzanine-4/ .  It would be helpful to have this included in the release notes or, if general, in the FAQ.

It would be an even better option to have much of this automated via a manage.py call, but even so, it would be good to have it included in the documentation.

**Comment by stephenmcd** [comment]
Don't really have the capacity to do this in a consistent way.

**Comment by vwbusguy** [comment]
Don't have the capacity for any upgrade documentation?

**Comment by stephenmcd** [comment]
Would you like to get involved and be responsible for doing this in a consistent way for each release?

**Comment by ryneeverett** [comment]
I've never really accepted the premise that an "upgrade guide" is necessary. A file keeping track of breaking changes as they happen seems like less effort and less haphazard. I think that's typically the `CHANGELOG`'s role, but skimming the auto-generated `CHANGELOG` and figuring out what might have been a breaking change after the fact is not very realistic.

**Comment by derek-adair** [comment]
Damn that is a crucial tutorial that should be made more prevalent.  I think what @vwbusguy is proposing is to simply include articles like the one he linked in the official documentation.  There really is no reason not to, very useful.
