### ISSUE TITLE
Support "Django Sites" in Mezzanine

### ISSUE THREAD

**Issue by Nekmo** [stephenmcd/mezzanine#1563]
Hi, I need to have multiple sites with different content. I sought support for multiple sites in Mezzanine and I only found to change themes.

I need to specify which sites the content is displayed.

Thank you very much.

**Comment by stephenmcd** [comment]
This is all built in, spend some more time looking.

**Comment by Nekmo** [comment]
I looked at the file models.py from mezzanine.core app and have not found anything.

I want to have several websites:
- spain.market.domain
- portugal.market.domain

I want to create a page visible only to Spain and is displayed on the menu. Then I want to create a different page, and make it available only in Portugal.

I have looked at the documentation and source code and do not see anything. I could modify default models (blog, etc.) to add support for sites, but I would have to modify insurance more.

**Comment by stephenmcd** [comment]
That's bizarre, because the first piece of code in the file you mentioned is exactly the code you're asking about.

Like I said, it's all built in already, but if you don't believe me, try the mailing list, maybe someone else can convince you.

**Comment by Nekmo** [comment]
Ok, sorry for my fault. I did not see documented and thought "SiteRelated" was something else.

**Comment by stephenmcd** [comment]
It's documented here: http://mezzanine.jupo.org/docs/multi-tenancy.html
