### ISSUE TITLE
TinyMCE cant select image

### ISSUE THREAD

**Issue by georgkrause** [stephenmcd/mezzanine#1567]
![bildschirmfoto vom 2016-03-18 10-56-09](https://cloud.githubusercontent.com/assets/939889/13874417/13aa406c-ecf8-11e5-985c-3ac4d811bb1e.png)

**Comment by stephenmcd** [comment]
There's not enough info here to reproduce this.

**Comment by georgkrause** [comment]
okay, sorry. i created a model which extends the displayable and added a richtextfield in order to edit it in the admin with the tinyMCE:

`class construction(Displayable):
text = RichTextField("Text")`

then i try to add a picture to this site, uploaded it with the media tool and now i try to add it to tinymce. as you can see on the picture the table is kind of damaged. my mezzanine version is 4.1.0

**Comment by stephenmcd** [comment]
Cool, but that really isn't anything out of the ordinary. You're going to have to dig into the filebrowser code to work out what's gone wrong for you.

**Comment by georgkrause** [comment]
okay, got the problem: my adblocker block the element fb_icon, maybe because of the relation to facebook. a other name may be a good idea, but for now this is fixed. weird :o

**Comment by stephenmcd** [comment]
Nice find!
