### ISSUE TITLE
UserProfile cannot have Multiple Foreign keys to User

### ISSUE THREAD

**Issue by mmansour** [stephenmcd/mezzanine#1568]
To replicate: 

Create UserProfile as per mezz docs

```
class UserProfile(models.Model):
    user = models.OneToOneField('auth.User', blank=True, null=True, related_name='userprofile')
    owner = models.ForeignKey('auth.User', blank=True, null=True, related_name='subordinates')
```

Run 'makemigrations'. You'll get the following error: 

> '*appname*.UserProfile' has more than one ForeignKey to 'auth.User'.

The issue seems to be stemming from the mezzanine.accounts.admin profile inlines: 

If I add : 

`fk_name = 'user'`

to the body of the ProfileLineClass the issue is fixed. 

```
try:
    class ProfileInline(admin.StackedInline):
        model = get_profile_model()
        can_delete = False
        fk_name = 'user'   # ADDED HERE
        template = "admin/profile_inline.html"
        extra = 0
    UserProfileAdmin.inlines += (ProfileInline,)
except ProfileNotConfigured:
    pass
```

If this is a bug (and an acceptable fix) I am happy to fix and submit a pr. However, this would require a convention that everyone name their OneToOneField 'user' in their User Profile model. 

The need to have multiple foreign keys to the user model from userprofile does not seem like that much of an edge case. The above approach seems like a reasonable one to create users that can be owners/admins of other users, yet not staff. However, if this is not a bug and there is a better approach then the one I am taking to achieve this I am open to it. Please let me know!

Cheers

**Comment by jerivas** [comment]
I think a slightly better approach would be to allow developers to specify the field they want to use as FK for the profile in cases where ambiguity may arise. Example:

```python
class UserProfile(models.Model):
    # All the fields...
    fk_name = 'user' # Choose which field to use as FK
```
Then in the `ProfileInline`, we just override `__init__()` to pick this attribute from the model and set it on the admin class.

```python
def __init__(self, parent_model, admin_site):
    self.fk_name = getattr(self.model, 'fk_name', None)
    super(ProfileInline, self).__init__(parent_model, admin_site)
```

**Comment by mmansour** [comment]
I think your idea is better, too. If you guys want me to implement let me know and I'll grab the project, tweak and shoot over a PR. 

Cheers

**Comment by jerivas** [comment]
So after reading the comments on the mailing list I think the underlying issue here is that Mezzanine will automatically create an InlineAdmin for the profile model, and the developer has no control over it. Instead of providing hooks for some or all options, we should simply create a new setting to store the dotted path to an InlineAdmin class where one can do whatever is best for the case.

`AUTH_PROFILE_INLINE_ADMIN = "myapp.admin.ProfileInlineAdmin"`

The current implementation could be used as the default value for the setting, so it should be 100% backwards compatible (it could live in `mezzanine.accounts.admin`). Custom admin classes could also inherit from it to easily override it.

**Comment by stephenmcd** [comment]
There's a `mezzanine.accounts.get_profile_field_name` function, what about the previous idea but using it? Eg `self.fk_name = mezzanine.accounts.get_profile_field_name()`

**Comment by mmansour** [comment]
Sounds good. I'll give the `self.fk_name = mezzanine.accounts.get_profile_field_name()` approach a shot and shoot over a PR this week.

**Comment by mmansour** [comment]
While starting to dig in to this realized I like settings path approach suggested by jerivas a little more. It gives more freedom to modify however we wish.  Any objections to going that route?

**Comment by stephenmcd** [comment]
I don't think this is a common enough use-case to warrant a setting if we can resolve it without one.

> It gives more freedom to modify however we wish.

What does that mean?

**Comment by mmansour** [comment]
> It gives more freedom to modify however we wish.

By that I mean an optional dotted path to our own custom ProfileInlineAdmin gives us the option to easily build the inline however we see fit for our project.  But yes, I do agree this is not that common.

**Comment by stephenmcd** [comment]
Sorry I misunderstood the setting. Actually being able to override the whole form probably does open up a lot more configurability, so it goes beyond this one use-case. Let's go with the setting!

**Comment by stephenmcd** [comment]
#1572
