### ISSUE TITLE
Sharing on facebook fails if blog post has non-ascii characters

### ISSUE THREAD

**Issue by vranki** [stephenmcd/mezzanine#1570]
Steps to reproduce:

* Go to: http://tampere.hacklab.fi/radioamat%C3%B6%C3%B6rikurssi-ohi/
* Click on share on Facebook
* Notice that the link being shared has invalid characters and is 404. 

Looks like some URL character encoding is not done properly.

**Comment by stephenmcd** [comment]
I used the same title/URL here and it works fine:

http://mezzanine.jupo.org/blog/radioamat%C3%B6%C3%B6rikurssi-ohi/

Please reopen if you work out the bug.

**Comment by vranki** [comment]
Seems to work on mezzanine.jupo.org. Any ideas why it fails on our server?
