### ISSUE TITLE
Docs for 4.1.0 not easily available.

### ISSUE THREAD

**Issue by spookylukey** [stephenmcd/mezzanine#1571]
The main site http://mezzanine.jupo.org/ shows download links for 4.1.0, but the docs  http://mezzanine.jupo.org/docs/ are for version 4.0.1, and doesn't show the change log for 4.1.0 -  http://mezzanine.jupo.org/docs/colophon.html#change-log

More generally, docs for specific versions should be available.

**Comment by auvipy** [comment]
@jerivas @stephenmcd

**Comment by stephenmcd** [comment]
Docs are updated now.

**Comment by auvipy** [comment]
docs are showing but can't see the change log for 4.1

**Comment by stephenmcd** [comment]
It's there http://mezzanine.jupo.org/docs/colophon.html#version-4-1-0-jan-17-2016
