### ISSUE TITLE
Cannot add new stacked inlines

### ISSUE THREAD

**Issue by jerivas** [stephenmcd/mezzanine#1575]
So I was giving the master branch a shot and noticed that we're now using Django's own Javascript to dynamically insert/remove inlines (yay!). It seems to be working fine, except that instances of `StackedDynamicInlineAdmin` don't get the "Add another" link.

I'm using Django 1.9.4 and Mezzanine master (with grappelli-safe master too).

I actually encountered this after developing a fix for a weird issue where stacked inlines were not being ordered by drag-n-drop. I hope to contribute that once we can sort this out.

**Comment by Cajoline** [comment]
I have the same problem after fixing ordering stacked inlines too

**Comment by AlexHill** [comment]
Hey @jerivas or @Cajoline are you able to make a repo with a sample project demonstrating the issue? `StackedDynamicInlineAdmin` isn't used directly in Mezzanine anywhere.

Also, there are remnants of Mezzanine's dynamic inline system that we should tidy up as part of fixing this. For example, `BaseDynamicInlineAdmin` and `dynamic_inline.js` don't do anything related to dynamic inlines – they're purely related to ordering now.

**Comment by jerivas** [comment]
Alright, just created this demo [repo].
Some additional issues I see (might be worth tracking them separately):

- Ordering of stacked inlines is broken. Most likely just a missing selector in JS #62 (see comment on April 1, 2016)
- The order "handle" is showing in the inline body as well as in the title (it appears as a field after the "bio" field in the demo)

[repo]: https://github.com/jerivas/mezz-inlines

**Comment by AlexHill** [comment]
Thanks Ed. I'm taking a look now.

**Comment by AlexHill** [comment]
Couple of first steps: https://github.com/stephenmcd/grappelli-safe/compare/dynamic_stacked

Those changes get the "add another" link and expanding/collapsing working. Haven't taken a look at any other issues yet.

**Comment by Cajoline** [comment]
@AlexHill 
Thank you,
I try this fix but for me not work, in the newest object created it's not possible to edit it i have an validation error (empty field)

**Comment by jerivas** [comment]
@Cajoline Most likely an error in the sample `FamilyMember` model. Just added a migration to support empty `date_of_birth`. Try pulling and running `migrate`.

**Comment by jerivas** [comment]
@AlexHill Adding/removing inlines seems to be working fine. I have fixes for the two issues I described previously, and I have created a [fork of my own] to compare.

The only outstanding thing left is that new stacked inlines added via "Add another" show a "Remove" text instead of the little "X" on the corner. I'm not sure how Django is copying the DOM to create new inlines, but it's producing different markup at least in the `<h3>` region of each inline.

Finally, I added another migration to the sample app so that stacked inlines use a RichTextField (at least for me that's a common case). That produces a TinyMCE error in the `submit` handler defined in `dynamic_inline.js`. For now I'm just catching the exception and logging it to the console, and it seems to be working fine. Previously the exception prevented the new `_order` values from being computed.

[fork of my own]: https://github.com/stephenmcd/mezzanine/compare/master...jerivas:stacked_inlines

**Comment by jerivas** [comment]
Hmmm, looks like there's another problem with stacked inlines + rich text. I can not interact with the TinyMCE instances created via "Add another". This looks like a different issue, though, I'll see what I can find and follow up in another issue.

**Comment by Cajoline** [comment]
@jerivas I have the same problem it's impossible to interacting with the new rich text, when i click "add another"

**Comment by jerivas** [comment]
Just tested with Mezzanine 4.2.0 / Grappelli 0.4.4 and the fixes by @AlexHill still hold, with the only drawback being that the "Remove" link appears as text instead of the "X" icon on added stacked inlines.

I've contributed my changes as PR #1655.

**Comment by stephenmcd** [comment]
fac64af09c901225e4921ce58ff0a88636b1abcb
