### ISSUE TITLE
admin/media-library/browse/ never loads?

### ISSUE THREAD

**Issue by EyesBear** [stephenmcd/mezzanine#1576]
Everything was working fine, suddenly the media-library page just never loads for me. Every other page is working fine, and even the urls to the images are working. 

Does anyone know what might went wrong?

**Comment by stephenmcd** [comment]
Can you try the mailing list?

**Comment by shangzhikeji** [comment]
I met the same problems. How to fix it?

**Comment by shangzhikeji** [comment]
I solve it by reinstall  filebrowser_safe because filebrowser_safe lost.
