### ISSUE TITLE
JQUERY_FILENAME not caching static file generated

### ISSUE THREAD

**Issue by Cajoline** [stephenmcd/mezzanine#1578]
Hi,
I try to change the JQUERY_FILENAME settings with another version of jquery and i try to use 
the caching static file, when i try to collectstatic doesn't work for this file, the new file with hached name is not generate, but all another files are generated well

My mezzanine version 4.0.1

Thx

**Comment by stephenmcd** [comment]
Those things aren't really related to each other, so maybe you're expecting something to happen that won't, but can you post this to the mailing list instead? Thanks.

**Comment by Cajoline** [comment]
ok thx, i'll post in malling list
