### ISSUE TITLE
Ordering 'ManyToMany' field?

### ISSUE THREAD

**Issue by EyesBear** [stephenmcd/mezzanine#1581]
In my article model I have an 'author' manytomany field, is there a way to display the authors according to the orders in the backend?

For example, if I add authorA first and authorB second from the admin page, is there a way to reflect this order in the frontend?

Currently they are ordered by id.

**Comment by jerivas** [comment]
Hi Jiang. We are using the issue tracker for bug reports only. Please post general questions to the mailing list: https://groups.google.com/forum/#!forum/mezzanine-users. Thanks!
