### ISSUE TITLE
page_branch store to many pages

### ISSUE THREAD

**Issue by encolpe** [stephenmcd/mezzanine#1582]
Trying to put a logo in the middle of the top menu I saw that page_branch store also pages that are only in other menus making impossible  to compute  the list middle on rendering.

As page_branch is computed one time for each menu in the page why do we need these extra pages with an in_menu boolean? 

It seems an overcomplicated solution just for display links in navigation or menus.

**Comment by stephenmcd** [comment]
Fair point, but it's been this way for years, so people might be relying on the behaviour now, so I don't think we should change it.

Of course achieving what you want isn't impossible, you'll just need to Write Some Code.
