### ISSUE TITLE
"Column 'site_id' cannot be null" when saving a SiteRelated model with unusual id

### ISSUE THREAD

**Issue by quarxpl** [stephenmcd/mezzanine#1583]
I'm working with this model:

```
class Currency(SiteRelated):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # more fields (name, placement) without any impact on the error
```

It is handled by the corresponding admin class:

```
class CurrencyAdmin(admin.ModelAdmin):
    list_display = ['name', 'placement']
    list_display_links = ['name', 'placement']

admin.site.register(Currency, CurrencyAdmin)
```

Adding a new record comes with the following error message:

> Exception Type:     IntegrityError
> Exception Value:    (1048, "Column 'site_id' cannot be null")

The error occurs because of the condition in the save method of mezzanine.core.models.SiteRelated

```
if update_site or (self.id is None and self.site_id is None):
            self.site_id = current_site_id()
```

Removing part of the condition "resolves" the problem:
```
if update_site or (self.site_id is None):
            self.site_id = current_site_id()
```

I guess my unusual id (UUIDField) is the culprit, however isn't it supposed to work as is?

**Comment by stephenmcd** [comment]
Looks like a Django bug with UUIDField

You might be able to workaround by overriding the method that code's in.
