### ISSUE TITLE
Improperly configured DB error after changing settings

### ISSUE THREAD

**Issue by beckastar** [stephenmcd/mezzanine#1586]
I get the following error when I try to run the db shell:

django.core.exceptions.ImproperlyConfigured: Requested setting DATABASES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

I've already changed my DATABASES setting in settings.py to  "ENGINE": "django.db.backends.sqlite3",

What else is missing?

**Comment by jerivas** [comment]
Hi Becka.

Please use the [mailing list] for general help requests. Thanks!

[mailing list]: https://groups.google.com/forum/#!forum/mezzanine-users
