### ISSUE TITLE
 UnicodeDecodeError for user-agent (still)

### ISSUE THREAD

**Issue by jenniferlianne** [stephenmcd/mezzanine#1589]
I also experienced the problem described in #1485 in the field.  Code to reproduce it is below.  I get that someone is trying to hack the site, but still, it shouldn't 500 error.  Running mezzanine 4.0.1.

```
from django.test import TestCase, Client

class TestBadAgent(TestCase):

    def test_bad_agent(self):
        bad_str = u"\xe2\x28\xa1"
        c = Client(HTTP_USER_AGENT=bad_str)
        c.get('/')

    def test_bad_agent_issue_in_field(self):
        bad_str = b'\xff'
        c = Client(HTTP_USER_AGENT=bad_str)
        c.get('/')

```
Edited to add a unit test to show the exact path hit in the field... in the second test case, the unicode decode error is handled, but then raises an exception again when checking against known devices...

**Comment by molokov** [comment]
I'm also getting some error based on Javascript/SQL injection attacks in the HTTP_USER_AGENT field, e.g:

HTTP_USER_AGENT = '}__test|O:21:"JDatabaseDriverMysqli":3:{s:2:"fc";O:17:"JSimplepieFactory":0:{}s:21:"\\0\\0\\0disconnectHandlers";a:1:{i:0;a:2:{i:0;O:9:"SimplePie":5:{s:8:"sanitize";O:20:"JDatabaseDriverMysql":0:{}s:8:"feed_url";s:3230:"eval(base64_decode(<<REMOVED>>));JFactory::getConfig();exit";s:19:"cache_name_function";s:6:"assert";s:5:"cache";b:1;s:11:"cache_class";O:20:"JDatabaseDriverMysql":0:{}}i:1;s:4:"init";}}s:13:"\\0\\0\\0connection";b:1;}\xf0\xfd\xfd\xfd'

I expect the smarter move would be to block such requests using the webserver (e.g. nginx) with something like this:

```
location / {
    if ($http_user_agent ~* JDatabaseDriverMysql) {
        return 403;
    }
}
```
See also http://stackoverflow.com/questions/19337662/blocking-all-bots-except-a-few-with-nginx for an example blocking specific bots - you could add a string that appears in these attacks to the patterns checked for. 

I am planning to add such checks to my nginx.conf template before doing a redeploy.

**Comment by stephenmcd** [comment]
Glad to fix this in Mezzanine if someone can provide a test case that reproduces it.

**Comment by jerivas** [comment]
The test case by @jenniferlianne raises the exception consistently. I also get several occurrences of the user agent shown by @molokov in my error logs every day (notice `\xf0\xfd\xfd\xfd`, which is choking Mezzanine).

I would say we have two issues here, one is the occurrence of non-ascii chars in UA strings (which might or might not be malicious in intentions), and then the [documented attacks] towards Joomla sites with the "JDatabaseDriver" UA (which are definitely malicious, but harmless towards Django/Mezzanine).

I'm +1 on getting rid of the exception and making the UA handling more robust. Blocking at nginx level is a good idea but a separate issue IMO.

[documented attacks]: https://blog.sucuri.net/2015/12/remote-command-execution-vulnerability-in-joomla.html

**Comment by stephenmcd** [comment]
> The test case by @jenniferlianne raises the exception consistently.

I'm sorry I completely missed that!

**Comment by stephenmcd** [comment]
Just pushed the fix, thanks @jenniferlianne for the test case.
