### ISSUE TITLE
collecttemplates.py is using the old Django settings.TEMPLATE_DIRS variable pre 1.8 

### ISSUE THREAD

**Issue by agwego** [stephenmcd/mezzanine#1590]
In 1.8 and on the TEMPLATE_DIRS is now roled into the TEMPLATES data structure. 
The patch would be:
42c42,46
<         to_dir = settings.TEMPLATES_DIRS[0]
---
>         to_dir = None
>         if settings.TEMPLATE_DIRS :
>             to_dir = settings.TEMPLATES_DIRS[0]
>         else :
>             to_dir = settings.TEMPLATES[0]['DIRS'][0]

* Mezzanine 4.1.0
* Django 1.9.5
* Python 2.7.10
* MySQL 5.6.16
* Linux 3.8.13-98.1.2.el7uek.x86_64

**Comment by stephenmcd** [comment]
#1512

**Comment by donnydavis** [comment]
This works but still throws an error 
/usr/lib/python2.7/site-packages/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)

**Comment by ryneeverett** [comment]
@donnydavis That's a warning, not an error.
