### ISSUE TITLE
Documentation issue for urls.py

### ISSUE THREAD

**Issue by FractalBobz** [stephenmcd/mezzanine#1591]
In the faq section under
http://mezzanine.jupo.org/docs/frequently-asked-questions.html#why-isn-t-the-homepage-a-page-object-i-can-edit-via-the-admin
The documentation points to [https://github.com/stephenmcd/mezzanine/tree/master/mezzanine/project_template/urls.py](url)
which gives a 404
I assume this should now be [https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/project_template/project_name/urls.py](url)
But it may need rewriting since there's been changes.

Thanks.

**Comment by ryneeverett** [comment]
It's fixed in master. See #1571.
