### ISSUE TITLE
Doesn't run due to django_comments on py3k

### ISSUE THREAD

**Issue by tutuca** [stephenmcd/mezzanine#1593]
I'm getting this error when upgrading my instance to the latest release.

      File "/home/matias/.venvs/machisitio/lib/python3.5/site-packages/mezzanine/generic/models.py", line 10, in <module>
        from django_comments.models import Comment
      File "/home/matias/.venvs/machisitio/lib/python3.5/site-packages/django_comments/models.py", line 12, in <module>
        class Comment(CommentAbstractModel):
      File "/home/matias/.venvs/machisitio/lib/python3.5/site-packages/django/db/models/base.py", line 102, in __new__
        "INSTALLED_APPS." % (module, name)
    RuntimeError: Model class django_comments.models.Comment doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

I don't remember that dependency being that blocker. I don't even use the comments except from disqus. Trying to blindly update *django_comments* I get that it doesn't even installs.

Any pointer?

**Comment by AlexHill** [comment]
Are you upgrading from a very old version?

django.contrib.comments has been deprecated since Django 1.7, and replaced
by django-contrib-comments, an external package. Mezzanine was updated
around that time to accommodate the change. You'll need 'django_comments'
in your INSTALLED_APPS for it to work.

Cheers,
Alex

**Comment by AlexHill** [comment]
BTW `mezzanine.generic.models.ThreadedComment` extends the `Comment` model, which is why you'll be getting this error even though you aren't using the built-in comments.

**Comment by tutuca** [comment]
That did the trick, thanks!
Yes, it's a very old version. It was running on django 1.4.

Thanks for the quick response.
