### ISSUE TITLE
Missing CSRF token in comments template

### ISSUE THREAD

**Issue by PoorCoco** [stephenmcd/mezzanine#1597]
mezzanine/generic/templates/generic/includes/comment_form.html

Line 3 should be:
&lt;form method="post" id="contactform" action="{{ comment_url }}#comment"&gt;{% csrf_token %}

From Mezzanine 4.1.0

**Comment by stephenmcd** [comment]
That template doesn't even exist.

The one that renders the form uses ``fields_for`` tag, whose corresponding template provides ``csrf_token``.
