### ISSUE TITLE
Deprecate SSLRedirectMiddleware

### ISSUE THREAD

**Issue by dsanders11** [stephenmcd/mezzanine#1600]
Since Django 1.8 added [`SecurityMiddleware`](https://docs.djangoproject.com/en/1.9/ref/middleware/#module-django.middleware.security), I don't believe there's any functionality provided by `SSLRedirectMiddleware` that isn't provided there? It looks like maybe `SSL_FORCED_PREFIXES_ONLY` isn't covered, but IMO it's not worth keeping an extra middleware around for just that functionality.

**Comment by jerivas** [comment]
I share David's opinion. With free solutions like Let's Encrypt and the general recommendation of "HTTPS everywhere", it's best to put an entire site behind HTTPS at the server level.

**Comment by AlexHill** [comment]
+1 from me. Good idea David.

**Comment by stephenmcd** [comment]
Consensus! Let's do it.
