### ISSUE TITLE
openshift

### ISSUE THREAD

**Issue by pedromorgan** [stephenmcd/mezzanine#1602]
Hi folks..
Creating a blog (newbie dev http://blog.anahata-retreat.org.nz/)
Part of  "next genen" of  http://next.anahata-retreat.org.nz/
for http://anahata-retreat.org.nz/ and away from tikiwiki

and hidden agenda is to migrate a site totally to mezzanine

So a quick questions are

- can we use `.md` markdown as a format, ie in an editor
- am deploying to openshift, is there an official one, so we can keep it up to date moving forward
- Can we intersphinx a bit in creating docs and links to "installed apps and classes" ?

**Comment by stephenmcd** [comment]
Mailing list is the best place for this.
