### ISSUE TITLE
EXTRA_MODEL_FIELD breaking migrations in Django 1.8

### ISSUE THREAD

**Issue by AlexHill** [stephenmcd/mezzanine#1606]
In #1513 @jerivas posted a [traceback](https://github.com/stephenmcd/mezzanine/issues/1513#issuecomment-172884886) showing a similar but separate issue to the one of models being imported early. When running migrations using EXTRA_MODEL_FIELDS, Django 1.8 will crash with an error like this:
`django.db.utils.OperationalError: duplicate column name: extra_field`

I've created a test project at https://github.com/AlexHill/extra_field_test.

To replicate:
1. Create a Python environment with Mezzanine master and Django 1.8
2. `git clone https://github.com/AlexHill/extra_field_test.git`
3. `cd extra_field_test`
4. `python manage.py createdb`

It's caused by the `class_prepared` signal being fired twice at some point, which results in `SomeModel._meta.add_field()` being called twice for each extra field injected into `SomeModel`.

**Comment by diogobaeder** [comment]
Hi,

Migrations are still broken in Mezzanine with Django 1.10, in that scenary. If I create a first migration, fine, it works, adding the additional fields, but then on the next run to create migrations, even without any change, it creates a second migration deleting everything from the previous migration. Really weird.

Please let me know if you need an example of that. I can setup a quick one here if needed.

Thanks!

**Comment by nielsonsantana** [comment]
In this link, there a solution.
https://stackoverflow.com/questions/32456212/adding-a-custom-field-to-django-mezzanine-blog-post

After add a field to `EXTRA_MODEL_FIELDS`
```
EXTRA_MODEL_FIELDS = (
  (
    "mezzanine.blog.models.BlogPost.caption",
    "django.db.models.CharField",
    ("Caption",),
    {"default": 'Some String', 'max_length': 150},
  ),
)
```

Is required use `MIGRATION_MODULES` to store the migrations as this example.

```
MIGRATION_MODULES = {
    "blog": "migrations_external_lib.mezzanine.blog.migrations",
}
```

**Comment by jerivas** [comment]
`MIGRATION_MODULES` is now mentioned in Mezzanine's documentation http://mezzanine.jupo.org/docs/model-customization.html#field-injection-caveats
