### ISSUE TITLE
editable_loader tag should not used in compress block.

### ISSUE THREAD

**Issue by qiuyuzhou** [stephenmcd/mezzanine#1607]
In the bottom of default base.html template:

```
{% compress js %}
{% block footer_js %}
  <script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script>
  <script src="{% static "js/bootstrap.js" %}"></script>
  <script src="{% static "js/bootstrap-extras.js" %}"></script>
  {% include "includes/footer_scripts.html" %} # Here
{% endblock %}
{% endcompress %}
```
{% include "includes/footer_scripts.html" %} in the compress block, there is a {% editable_loader %} tag in the included template file which would load the js file of tinymce. Then the tinymce.min.js been compressed in cached js file at a cache path,  can't dynamic load plugin js files in normal static path.

So when I move   {% include "includes/footer_scripts.html" %}  to out of the compress block, it goes ok.

```
{% compress js %}
{% block footer_js %}
  <script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script>
  <script src="{% static "js/bootstrap.js" %}"></script>
  <script src="{% static "js/bootstrap-extras.js" %}"></script>
{% endblock %}
{% endcompress %}
 {% include "includes/footer_scripts.html" %} 
```

Sorry for my poor english.

**Comment by stephenmcd** [comment]
Seems like you're looking at a different version of the default base template, have a look at the original here:

https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/templates/base.html#L151-L153

**Comment by qiuyuzhou** [comment]
It's my mistake. I'm sorry to bother you.

**Comment by stephenmcd** [comment]
No problem! And your English is fine :-)
