### ISSUE TITLE
Error on page/blog update if Debug=False

### ISSUE THREAD

**Issue by adamtay82** [stephenmcd/mezzanine#1611]
Not quite sure what I'm doing wrong here, but I have just deployed a Mezzanine instance on Elastic Beanstalk and all is working fine when DEBUG = True.

When DEBUG = False however, I am bounced to the 500 error page whenever I am in the admin section of the site and "Save" something (a page, or blog for example). Other than that, the rest of the site works perfectly - it's reading everything from the database, serving up compressed JS/CSS etc.

The error logs don't give me much to go on (they just show a 500 error). 

Can anyone help suggest what might be going on?  

Thanks all.

**Comment by stephenmcd** [comment]
Can you try the mailing list instead? Thanks
