### ISSUE TITLE
error when upload zip files to gallery

### ISSUE THREAD

**Issue by augustochaos** [stephenmcd/mezzanine#1613]
Hello
I'm having some problems to upload a zipfiles to gallery. When I was trying to do it I saw the error message:

`AttributeError at /pt-br/admin/galleries/gallery/23/
'str' object has no attribute 'name'
Request Method:	POST
Request URL:	http://localhost:8000/pt-br/admin/galleries/gallery/23/?parent=11
Django Version:	1.8.12
Exception Type:	AttributeError
Exception Value:	
'str' object has no attribute 'name'
Exception Location:	/home/augusto/Documentos/proteja/lib/python3.4/site-packages/mezzanine/galleries/models.py in save, line 138
Python Executable:	/home/augusto/Documentos/proteja/bin/python
Python Version:	3.4.3`

In mezzanine/galleries/models.py, line 138:

`    def save(self, *args, **kwargs):
        """
        If no description is given when created, create one from the
        file name.
        """
        if not self.id and not self.description:
            name = force_text(self.file.name) # this is a line with error
            name = name.rsplit("/", 1)[-1].rsplit(".", 1)[0]
            name = name.replace("'", "")
            name = "".join([c if c not in punctuation else " " for c in name])
            # str.title() doesn't deal with unicode very well.
            # http://bugs.python.org/issue6412
            name = "".join([s.upper() if i == 0 or name[i - 1] == " " else s
                            for i, s in enumerate(name)])
            self.description = name
        super(GalleryImage, self).save(*args, **kwargs)`

To solve this error, I change:

name = force_text(self.file.name)

to 

name = force_text(self.file)

And now, it works!

Another solution that work is, in a model of my app, I insert this lines:

`from copy import deepcopy
from mezzanine.galleries.models import GalleryImage
from django.utils.encoding import force_text
from string import punctuation

original_gallery_image_save = deepcopy(GalleryImage.save)
def file_name_gallery_image_save(self, *args, **kwargs):
    """
    If no description is given when created, create one from the
    file name.
    """
    if not self.id and not self.description:
        name = force_text(self.file)
        name = name.rsplit("/", 1)[-1].rsplit(".", 1)[0]
        name = name.replace("'", "")
        name = "".join([c if c not in punctuation else " " for c in name])
        # str.title() doesn't deal with unicode very well.
        # http://bugs.python.org/issue6412
        name = "".join([s.upper() if i == 0 or name[i - 1] == " " else s
                        for i, s in enumerate(name)])
        self.description = name
    super(GalleryImage, self).save(*args, **kwargs)

GalleryImage.save = file_name_gallery_image_save
`

This is version of Mezzanine:

Mezzanine 4.0.1
Django 1.8.12
Python 3.4.3
PostgreSQL 9.5.3
Linux 4.2.0-36-generic

I hope I have been clear, my English is bad!

**Comment by ryneeverett** [comment]
The change you suggest was implemented in b3d6ab9657d795dc6d947b015b36843a0b8dc7df and released in 4.1.0.
