### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by stephenmcd** [stephenmcd/mezzanine#1619]
- [x] `django.shortcuts.render_to_response` no longer supports `context_instance` arg (affects filebrowser)
- [x] `LOGOUT_URL` setting no longer defined
- [x] `SearchableManager.contribute_to_class` no longer achieves workaround for abstract models being disallowed access to managers
- [x] `OptParser` is no longer used by Django for management commands (refs to `Command.option_list` fail)
- [x] `NoArgsCommand` is removed from Django
- [x] Django's `i18n_patterns()` can return a tuple in 1.10 (see django/django#6968)
- [x] redirect loop in mezzanine.pages.tests.PagesTests.test_login_required

**Comment by geraldog** [comment]
Hi, I'm not sure if the last one is the "Displayable is abstract" error when searching "Everything" but I had one like that and kludged it with:

        results = BlogPost.objects.search(query, for_user=request.user) + Page.objects.search(query, for_user=request.user) + RichTextPage.objects.search(query, for_user=request.user) + Link.objects.search(query, for_user=request.user) + Form.objects.search(query, for_user=request.user) + Gallery.objects.search(query, for_user=request.user)

inside def search(request, template="search_results.html", extra_context=None):

Problem: repeated results. If repeated results can be filtered then it should be OK to work something around with this + SEARCH_MODEL_CHOICES

**Comment by stephenmcd** [comment]
@geraldog the issue was the third one listed for `SearchableManager.contribute_to_class`, it's since been fixed.

The code you posted will always return duplicates, 2 of every page, since all the page classes (`RichTextPage` etc) subclass `Page`.

**Comment by AlexHill** [comment]
@stephenmcd unless you're already working on it, I'm happy to have a crack at the optparse issue

**Comment by stephenmcd** [comment]
I haven't looked at it at all, that would be great Alex.

**Comment by AlexHill** [comment]
Alright I'll get on it, starting here: https://docs.python.org/3.5/library/argparse.html#upgrading-optparse-code

**Comment by AlexHill** [comment]
Addressed in #1636

**Comment by stephenmcd** [comment]
That's all the issues addressed - I'll close this for now, we can re-open if we find any issues that aren't immediately fixable.

**Comment by AlexHill** [comment]
Nice. I've just added the `stable/1.10.x` branch to the Travis config as well and all looks good.

**Comment by solarissmoke** [comment]
It seems that Mezzanine still expects a `MIDDLEWARE_CLASSES` setting in Django 1.10. If you migrate to the new `MIDDLEWARE` setting then the startup checks raise an `ImproperlyConfigured` exception because it is looking for `MIDDLEWARE_CLASSES`.

Happy to provide a PR - just wanted to check that someone hasn't already addressed this somewhere.

**Comment by jerivas** [comment]
I don't recall anyone else bringing it up, so I think the change is welcome.

Just keep in mind that Mezzanine officially supports the two latest 
versions of Django, so any changes would need to support 1.9 as well. I 
guess when 1.11 is out this would be easier as we'll only have to 
support the new-style middleware.

**Comment by solarissmoke** [comment]
PR: #1660. Grateful for feedback.
