### ISSUE TITLE
Decouple mezzanine and django.middleware.locale.LocaleMiddleware

### ISSUE THREAD

**Issue by ConstantAZ** [stephenmcd/mezzanine#1621]
I'm using another locale middleware (`solid_i18n.middleware.SolidLocaleMiddleware`), which conflicts with `django.middleware.locale.LocaleMiddleware`. Removing django middleware from MIDDLEWARE_CLASSES accomplishes nothing, since Mezzanine bluntly adds it back in `mezzanine.utils.conf.set_dynamic_settings`

Possible solutions:
1. Check if some middleware in MIDDLEWARE_CLASSES ends with 'LocaleMiddleware' before inserting default django middleware (same is done for cache middlewares)
2. Remove dynamic settings manipulations and raise `ImproperlyConfigured` instead. Tuples are there for a reason.

**Comment by AlexHill** [comment]
`SolidLocaleMiddleware` inherits from Django's `LocaleMiddleware` so we may be able to sort this out with an `isinstance` check.

**Comment by ConstantAZ** [comment]
I feel that more generic solution for this type of problems would benefit Mezzanine more in the long run, but it's up to developers to decide, of course.

**Comment by vaimdev** [comment]
I encounter this issue also , I manually comment it in the set_dynamic_setttings.

I use solid_i18n also , it works well when DEBUG=True. However, when change DEBUG=False, everything start not working , anybody face same problem ?

**Comment by stephenmcd** [comment]
I went for the quick hacky solution which will resolve the problem for the reported case of solid_i18n - thanks all for the input.
