### ISSUE TITLE
blog post detail page showd 404 after I changed the homepage

### ISSUE THREAD

**Issue by hillerliao** [stephenmcd/mezzanine#1622]
Following the comments in urls.py,  I pointed the homepage to the blog post listing page.
I did work. http://lixue.info/
However,  the blog post detail page showd 404. But everything is ok in testing environment.

http://lixue.info/%2Fpost-detail-page-showd-404/  return the following result:

'''
Not Found

The requested URL //1/ was not found on this server.

Apache/2.4.7 (Ubuntu) Server at www.liaoixue.com Port 80
'''

**Comment by stephenmcd** [comment]
Could you post this to the mailing list instead? Thanks
