### ISSUE TITLE
404 on /accounts/update/ 

### ISSUE THREAD

**Issue by zruu** [stephenmcd/mezzanine#1630]
For some reason I do not know why, when I write this context processor I can't go to /accounts/update/ anymore. It displays a 404.

    def user_subdomain(request):
        from django.shortcuts import get_object_or_404
        username = request.META['HTTP_HOST'].split('.')[0]
        user = get_object_or_404(User, username=username)
        return {
            'user': user,
        }

Everything else works just fine, and I can get to the login page etc.

**Comment by stephenmcd** [comment]
Can you post this to the mailing list?
