### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by loevda** [stephenmcd/mezzanine#1632]
Hi,

I got a lot of bad gateway on my sites build with mezzanine. They are hosted on a virtual server.
I have added more ram but still got the issue.

Previously I was using Apache to deploy sites but lately I have been using Mezzanine deploy scripts.
Does anyone knows about the minimum resources needed to run nginx/gunicorm per site?

Thanks a lot

**Comment by stephenmcd** [comment]
You need to post this to the mailing list.
