### ISSUE TITLE
Updated keywords_string is overwritten during admin save Cartridge.Shop.Model.Product; may affect other models

### ISSUE THREAD

**Issue by romecode** [stephenmcd/mezzanine#1633]
Even though Product.keywords.all() will return assigned keywords, Product.keywords_string does not return the csv of keywords.

The problem lies here:
save_model is run first in the admin and the old version of Product instance is saved as self._product=obj
related_items_changed runs after for the KeywordField
then save_formset runs and saves the previous obj in self._product over the new

keywords_string are overwritten

fetching the Product in save_formset does indeed fix the issue, however, I am not sure if this is the best way to go about it
self._product=Product.objects.get(pk=self._product.pk)

opened same issue in Cartridge, not sure if this is a Mezzanine issue or Cartridge
[Cartridge - Issue 301](https://github.com/stephenmcd/cartridge/issues/301)

**Comment by stephenmcd** [comment]
Sounds like Cartridge, but either way, no need to open two issues.
