### ISSUE TITLE
TinyMCE link broken after applying suggested fix - Might be related to generation of URLs

### ISSUE THREAD

**Issue by ghilbrae** [stephenmcd/mezzanine#1634]
Hi,

I have been having trouble with the link in TinyMCE. I've read several issues related with this problem and applied the fix suggested on issue #1516 and implemented on commit 94d5729.

I've tried a fresh installation applying the fix and it works on a pristine project but not in mine. The problem persists but it yields different errors.

I'm developing a custom app that is installed along with Mezzanine and django-machina. In my models a few inherit from Displayable and use 

```
objects = SearchableManager()
search_fields = ("title", "description", "keywords")
```

so content based on these models is searchable (I've followed the documentation on http://mezzanine.jupo.org/docs/search-engine.html)

In this instance the error I get is:

> Internal Server Error: /displayable_links.js
> Traceback (most recent call last):
>   File "/home/angela/Projects/virtualenvs/wuiwatch-mezzanine/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/home/angela/Projects/virtualenvs/wuiwatch-mezzanine/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
>     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
>   File "/home/angela/Projects/virtualenvs/wuiwatch-mezzanine/lib/python3.4/site-packages/mezzanine/core/views.py", line 192, in displayable_links_js
>     for url, obj in Displayable.objects.url_map(for_user=request.user).items():
>   File "/home/angela/Projects/virtualenvs/wuiwatch-mezzanine/lib/python3.4/site-packages/mezzanine/core/managers.py", line 375, in url_map
>     for item in (model.objects.published(for_user=for_user)
> AttributeError: 'SearchableManager' object has no attribute 'published'

If I don't use the search and omit the `objects = SearchableManager()` from all my classes then the problem appears when it first reads the class `django_comments.models.CommentFlag`

> Internal Server Error: /displayable_links.js
> Traceback (most recent call last):
>   File "/home/angela/Projects/virtualenvs/wuiwatch-mezzanine/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/home/angela/Projects/virtualenvs/wuiwatch-mezzanine/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
>     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
>   File "/home/angela/Projects/virtualenvs/wuiwatch-mezzanine/lib/python3.4/site-packages/mezzanine/core/views.py", line 200, in displayable_links_js
>     sorted_links = sorted(links, key=lambda link: (link[0], link[1]['value']))
> 
> TypeError: unorderable types: NoneType() < str()

From what I've seen the problem appears when the next for tries to generate the urls for all the content. As soon as it finds a model that gives some problem it crashes.

```
for model in apps.get_models():
    if issubclass(model, self.model):
        for item in (model.objects.published(for_user=for_user)
                              .filter(**kwargs)
                              .exclude(slug__startswith="http://")
                              .exclude(slug__startswith="https://")):
                items[item.get_absolute_url()] = item
```

I've commented this block so the users can at least add their own links comfortably and nothing else seems to be broken for now.

I don't know if there's something else I might be missing.

Best!

**Comment by stephenmcd** [comment]
You mentioned the issue only arises with your custom project. Can you create a minimal project that reproduces the problem and make it available somewhere?

**Comment by zruu** [comment]
I also have issue with the link. It do not load when having `/language-code/` in front of it. I get a 404.

**Comment by tadeoos** [comment]
I have a similar issue as well without any customization:
```python
file mezzanine/core/managers.py", line 403, in url_map
    for item in (model.objects.published(for_user=for_user)
AttributeError: 'SearchableManager' object has no attribute 'published'
```
when clicking on "add link" button in the editor. 
I want to be able to embed videos in blog posts, so the fix on this one would be much appreciated :)

**Comment by tiktuk** [comment]
I get a similar error:

<code>
AttributeError at /en/admin/displayable_links.js
'NewMultilingualManager' object has no attribute 'published'
Request Method:	GET
Request URL:	http://<domain>:8008/en/admin/displayable_links.js
Django Version:	1.11.16
Exception Type:	AttributeError
Exception Value:	
'NewMultilingualManager' object has no attribute 'published'
Exception Location:	/home/project/.local/share/virtualenvs/project365-cfcdyUAY/lib/python3.6/site-packages/mezzanine/core/managers.py in url_map, line 410
Python Executable:	/home/project/.local/share/virtualenvs/project365-cfcdyUAY/bin/python
Python Version:	3.6.6
Python Path:	
['/home/project/project365',
 '/home/project/.local/share/virtualenvs/project365-cfcdyUAY/lib/python36.zip',
 '/home/project/.local/share/virtualenvs/project365-cfcdyUAY/lib/python3.6',
 '/home/project/.local/share/virtualenvs/project365-cfcdyUAY/lib/python3.6/lib-dynload',
 '/usr/lib/python3.6',
 '/home/project/.local/share/virtualenvs/project365-cfcdyUAY/lib/python3.6/site-packages',
 '/home/project/.local/share/virtualenvs/project365-cfcdyUAY/src/mezzanine-blocks',
 '/home/project/.local/share/virtualenvs/project365-cfcdyUAY/src/natural']
Server time:	Wed, 5 Dec 2018 12:54:21 +0100
</code>

**Comment by blackboxoperations** [comment]
I remember this one. Here's the patch. 

```
diff --git a/mezzanine/core/managers.py b/mezzanine/core/managers.py
index 968ce09..6a04d12 100644
--- a/mezzanine/core/managers.py
+++ b/mezzanine/core/managers.py
@@ -1,6 +1,7 @@
 from __future__ import unicode_literals
 
 import django
+import traceback
 from future.builtins import int, zip
 
 from functools import reduce
@@ -409,9 +410,11 @@ class DisplayableManager(CurrentSiteManager, PublishedManager,
         items = {home.get_absolute_url(): home}
         for model in apps.get_models():
             if issubclass(model, self.model):
-                for item in (model.objects.published(for_user=for_user)
-                                  .filter(**kwargs)
-                                  .exclude(slug__startswith="http://")
-                                  .exclude(slug__startswith="https://")):
-                    items[item.get_absolute_url()] = item
+                if hasattr(model.objects, 'published'):
+                    for item in (model.objects.published(for_user=for_user)
+                                      .filter(**kwargs)
+                                      .exclude(slug__startswith="http://")
+                                      .exclude(slug__startswith="https://")):
+                        items[item.get_absolute_url()] = item
+
         return items
```

I'll push in a working instance of Mezzanine for Django 2.1+ when I'm back home in a week. Should allow you to chew through most of the backlog @stephenmcd. 

Thanks for making a CMS for Python that isn't pure shit. No one else seems to have pulled it off.

**Comment by tiktuk** [comment]
Could you pull @blackboxoperations's fix, @stephenmcd ? It works ☺️ . And thanks, @blackboxoperations !

**Comment by jerivas** [comment]
Looks like this already made it into master! 🎉https://github.com/stephenmcd/mezzanine/commit/9768b46f8377796d5d51d74db54589c9d3669a47#diff-4433e498943240025629a586b0f5ca2f96ef479c42406aad95c2febd28e900a0
