### ISSUE TITLE
Exceptions in get_ascendants

### ISSUE THREAD

**Issue by flo-dhalluin** [stephenmcd/mezzanine#1637]
for some reason, I am not sure how to reproduce though (happens only with the prod database..) 
I get the following exception when get ascendents of a page in a template : 

... 

`  File "/opt/mymedecine/venv/lib/python3.4/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/opt/mymedecine/venv/lib/python3.4/site-packages/django/template/base.py", line 913, in _resolve_lookup
    current = current()
  File "/opt/mymedecine/venv/lib/python3.4/site-packages/mezzanine/pages/models.py", line 121, in get_ascendants
    self._ascendants = pages[0]._ascendants
`

**Comment by ryneeverett** [comment]
The traceback is missing the actual exception.

**Comment by AlexHill** [comment]
Does this happen with any page or just some? Only pages with parents? Only pages with custom slugs?

This must be happening due to some particular arrangement of your page tree and slugs, so we'll really need more detail to work out what's going on here.

Your fix might be all that's needed, but until we know what's causing the problem we can't know that for sure.

**Comment by flo-dhalluin** [comment]
Ok, I finally got some time to investigate this one. pheww 

I was calling the method, on a page that's **not on the current site** . 
I have something like : 

```
class ItemViews(models.Model):
    # ... 
    item = models.ForeignKey(Page) # this is not filtered by current site.
```

And in my code ( and the production instance is of course multi site), I somehow retrieve all ItemViews for current user, and try to call get_ascendants on them, which triggers the exception, if the related page is not on the current site. I fixed the initial issue by having a proper custom manager for my ItemsView model that filters only items whose attached Page is on the current site, but I believe my proposed PR is still valid, we are calling [0] on a list we know may be empty ...

**Comment by AlexHill** [comment]
@flo-dhalluin this is now fixed in master. Thanks for reporting the bug and for taking the time to investigate.
