### ISSUE TITLE
Blog category hangs 

### ISSUE THREAD

**Issue by BojanKogoj** [stephenmcd/mezzanine#1639]
Sometimes without any reason it hangs and won't load
![screen shot 2016-07-28 at 16 39 24](https://cloud.githubusercontent.com/assets/634075/17216688/f3e467a6-54e1-11e6-93b2-3e7bfa70488f.png)

That is the only thing I get from it, no errors or anything else, browser has a spinning circle as if it is loading
If I try to wget I get this:
```vagrant@vagrant-ubuntu-trusty-64:~$ wget localhost:8000/blog/category/food/
--2016-07-28 14:43:36--  http://localhost:8000/blog/category/food/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8000... connected.
HTTP request sent, awaiting response...```

I already asked on [StackOverflow](http://stackoverflow.com/questions/38565786/mezzanine-blog-category-freezing) with no luck

Anyone has an idea why this is happening? Comes and goes with no apparent reason.

**Comment by jerivas** [comment]
Hi Bojan.

Please use the mailing list for support requests like this. It will be seen by much more people.

https://groups.google.com/forum/#!forum/mezzanine-users
