### ISSUE TITLE
The standalone TEMPLATE_* settings were deprecated in Django 1.8

### ISSUE THREAD

**Issue by keith24** [stephenmcd/mezzanine#1641]
When I run `runserver` on a new cartridge project (standalone mezzanine too, I think), I get this warning: 

```sh
WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS.
```

It's easily fixed by removing the `TEMPLATE_CONTEXT_PROCESSORS = (...)` lines from `settings.py`.  The context processors are already copied in the `TEMPLATES` dictionary.  

Is there any reason for keeping the old setting?  Backward compatibility?

**Comment by stephenmcd** [comment]
If you check the github repos you'll find those have been removed.

Please use the mailing list if you have any more questions like this.
