### ISSUE TITLE
Upload files with filebrowser_safe

### ISSUE THREAD

**Issue by frague59** [stephenmcd/mezzanine#1643]
Hi, 

filebrowser_safe seems a ugly to use, aka it uses (a very old version of) uploadify.swf to upload images.

Is it possible to change this to use a proper HTML5 widget (without flash) ?

```
<models.py>

class NewsTopic(Ownable, Displayable):
    content = RichTextField(verbose_name=_('Content'))
    illustration = FileBrowseField(verbose_name=_('Illustration'),
                                                  extensions=ILLUSTRATION_FILE_EXTENSIONS,
                                                  directory='images/',
                                                  max_length=255,
                                                  null=True, blank=True)
    ....

```
My problem is that when I try to upload an image, I select the target folder, then click on the (not translated) "SELECT FILES" button. I've my OS "select file" window. I do select my files in this window, then click on OK. This closes the OS window, I'm back to the browser window. I can't see any file list, and nothing happens when I click on the "upload" button.

I'm currently using Mezzanine + filebrowser_safe an a new "in-development" application, running on my personal (developer) computer, using `./manage.py runserver`.

I'm using : 

- Server side:
 - Mezzanine==4.1.0
 - filebrowser-safe==0.4.3
 - grappelli-safe==0.4.2

- Client side:
 - firefox 47.0.1 / debian "stretch" x86_64 
 - flash : tryed version 11.2 from flashplugin-nonfree and 22.0 from pepperflash, same result
 - jquery : 1.4.2 (quite old, too)

Thanks for your help !

**Comment by jerivas** [comment]
`filebrowser-safe` has already been upgraded to a HTML5 uploader. You can use it directly from the master branch or wait for the next release on PyPi.

Here's the issue where the upgrade was tracked: https://github.com/stephenmcd/filebrowser-safe/pull/54
