### ISSUE TITLE
TinyMCE Spell Checker Plugin

### ISSUE THREAD

**Issue by maateen** [stephenmcd/mezzanine#1647]
This plugin enables TinyMCE's spellcheck functionality. It also adds a toolbar button and the menu item `Spellcheck` under the `Tools` menu dropdown. Can you please add it?
Link: [https://www.tinymce.com/docs/plugins/spellchecker/](https://www.tinymce.com/docs/plugins/spellchecker/)

Thanks

**Comment by stephenmcd** [comment]
It's beyond the scope of Mezzanine since it requires server-side support.

You can configure TinyMCE yourself for your own project, take a look at the documentation.
