### ISSUE TITLE
Gallery .jpg files don't populate on createdb, link to thumbnail wrong

### ISSUE THREAD

**Issue by ssteinerx** [stephenmcd/mezzanine#1651]
Django 1.10, Mezzanine 4.2.0

Running an initial `createdb` creates the Gallery demo page, but the actual .jpg files aren't getting out of the zip files and the reference to the image thumbnail HTML doesn't reference the correct directory.

```
python3 manage.py createdb --noinput
```

The thumbnails appear to be there e.g. `./static/media/uploads/gallery/.thumbnails/Warsaw, Poland.jpg` exists, but the thumbnail doesn't show in the gallery, and the link itself 404's.

Attempting to edit the post to in the back-end also produces an error and the link can't be modified.

It looks like there is supposed to be a set of full-size files in the 'gallery' and the thumbnails are to be used in the gallery page backend.

Here's a snippet of the HTML:

```
<div class="col-xs-4 col-sm-3">
    <a class="thumbnail" rel="#image-1" title="Amsterdam  Holland" href="/static/media/uploads/gallery/Amsterdam%2C%20Holland.jpg">
        <img class="img-responsive" src="/static/media/uploads/gallery/Amsterdam, Holland.jpg">
    </a>
</div>
```

BaseGallery's save() method is supposed to extract the files from the zip file, but they're not there.  

The .thumbnails directory is there, but the HTML incorrectly specifies the path to the thumbnail file in the:

```
<a class="thumbnail"...
```

hunk of HTML (it references the full-sized file instead).  Even if the full sized file were there, shoehorning it into the preview image size is the wrong way to do it so that seems like a different bug.

**Comment by stephenmcd** [comment]
You don't have Pillow correctly installed.
