### ISSUE TITLE
Save Button In Blog Post and Everything That Involves Tinymce Not Working

### ISSUE THREAD

**Issue by llakes4real** [stephenmcd/mezzanine#1666]
Please, what can I do to correct this problem? I applied various fixes to Mezzanine, then i couldn't save blog posts and anything that involves the Tinymce widget any longer. Thank you.

**Comment by jerivas** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/mezzanine-users) for help requests. You'll also want to include your Python, Django, and Mezzanine version information when posting your question there.
