### ISSUE TITLE
Language switcher in the admin site is not displayed

### ISSUE THREAD

**Issue by mrtnkiss** [stephenmcd/mezzanine#1669]
The language-switcher dropdown menu is not displayed in the admin site. The language switcher is present at the login form.

I have a working project and I created a dummy project using default settings in order to reproduce it and found that both setups have the same results.

Versions:

- Python 2.7.11 64-bit, Windows 7
- Django 1.8.3, Mezzanine 4.0.0, django-modeltranslation 0.11
- Django 1.10.1, Mezzanine 4.2.0, django-modeltranslation branch master-dj110-integration which has Django 1.10 support

Using following settings:
```
USE_L10N = True
USE_I18N = True
USE_MODELTRANSLATION = True
LANGUAGES = (
    ('hu', _('Magyar')),
    ('en', _('English')),
    ('de', _('Deutsch'))
)
```

After digging around, I think I found the problem.

In the template core/admin/includes/dropdown_menu.html the **„LANGUAGES”** template variable is not populated, is empty, therefore failing the 

`{% if settings.USE_L10N and LANGUAGES|length > 1 %}`

test on line 25 (line numbers are for 4.2.0) , therefore the language switcher is not displayed. This template is loaded via the admin_dropdown_menu  template tag (core/template_tags/mezzanine_tags.py line 667). The template_vars variable inside this function is not populated with the LANGUAGES from settings.

My workaround is to add LANGUAGES to TEMPLATE_ACCESSIBLE_SETTINGS (it is not there by default), and then either 

- replace LANGUAGES with settings.LANGUAGES in the dropdown_menu.html template or
- populate template_vars explicitly in the template tag with a line added after line 686: `template_vars["LANGUAGES"] = context["settings"][”LANGUAGES”]`

**Comment by stephenmcd** [comment]
Thanks for all the detail!

It regressed in 71873e1ef11b7817d94595aaa8c96a513f4b26c4 - I have the correct fix incoming.

Your workaround is perfect for anyone who can't update.
