### ISSUE TITLE
Could not parse the remainder: ',off' from 'on,off'

### ISSUE THREAD

**Issue by onerro** [stephenmcd/mezzanine#1670]
`Error during template rendering

In template /usr/local/lib/python2.7/dist-packages/mezzanine/forms/templates/admin/forms/entries.html, error at line 33
Could not parse the remainder: ',off' from 'on,off'
23	<div id="content-main">
24	    <form method="post">
25	    {% csrf_token %}
26	    <table>
27	        <tr>
28	            <th>{% trans "Field" %}</th>
29	            <th>{% trans "Include" %}</th>
30	            <th class="last" colspan="2">{% trans "Filter by" %}</th>
31	        </tr>
32	        {% for include_field, filter_field, filter_option_fields in entries_form %}
33	        <tr class="{% cycle on,off as row %}">
34	            <td class="field">{{ include_field.label_tag }}</td>
35	            <td class="include">{{ include_field }}</td>
36	            <td class="filter last">{{ filter_field }}</td>
37	            <td class="options last">
38	                <div class="options-div">
39	                    {% for option_field in filter_option_fields %}
40	                    {{ option_field.label_tag }} {{ option_field }}
41	                    {% endfor %}
42	                </div>
43	            </td>`

**Comment by stephenmcd** [comment]
533d04f07b1f791de09590a845428f9af5be5806

**Comment by onerro** [comment]
aftet changed it, a new problem come.

VariableDoesNotExist at /admin/forms/form/3/entries/
Failed lookup for key [settings] in u"[{'False': False, 'None': None, 'True': True}, {u'title': <django.utils.functional.__proxy__ object at 0xb2936250>, u'entries_form': <EntriesForm bound=False, valid=Unknown, fields=(field_1_export;field_1_filter;field_1_contains;field_2_export;field_2_filter;field_2_contains;field_3_export;field_3_filter;field_3_contains;field_4_export;field_4_filter;field_4_contains;field_0_export;field_0_filter;field_0_from;field_0_to)>, u'submitted': False, u'original': <Form: Contact>, u'opts': <Options for Form>, u'can_delete_entries': True}]"
Error during template rendering
In template /usr/local/lib/python2.7/dist-packages/mezzanine/forms/templates/admin/forms/entries.html, error at line 0'

**Comment by stephenmcd** [comment]
That ones already fixed too - why don't you grab the source from here and verify before reporting anything else.
