### ISSUE TITLE
document upload broken in filebrowser_safe package

### ISSUE THREAD

**Issue by juliensalinas** [stephenmcd/mezzanine#1673]
Hello, I am running Mezzanine v4.2.0 and it seems I found a problem in the filebrowser_safe package which prevents the document uploads from the admin interface.

In this file, line 43:
`filebrowser_safe/templates/filebrowser/upload.html`

I needed to replace: `data-allowed-extensions="{% allowed_extensions_list %}"` 
with: `data-allowed-extensions="{{ allowed_extensions_list }}"`

**Comment by stephenmcd** [comment]
5e30a021f89f27100f137f6aab692303b4a6b2bd
