### ISSUE TITLE
Incorrectly saving content_model when moving a subclassed Page instance in Pages Change List

### ISSUE THREAD

**Issue by pirave** [stephenmcd/mezzanine#1676]
The new `set_content_models()` that is being called in a `Page`'s `save()` method is causing all subclassed `Page`s to have `content_model` set to `None`. (link to [commit](https://github.com/stephenmcd/mezzanine/commit/bede76b6f96227350cb0bf0058f555daeb4cc2ad))

Steps to recreate:
A) create a new mezzanine project and add all the initial demo pages
B) login as admin and go to the pages change list
C) Move any page (e.g. Legals) under another page (e.g. Gallery)
D) Open the Legals page.

The page is no longer a RichTextPage, but a regular Page.

**Comment by papasax** [comment]
I saw that... Do you have any fix?

**Comment by ryneeverett** [comment]
Reproduced.
