### ISSUE TITLE
Changing Title of Slugged model and update slug

### ISSUE THREAD

**Issue by zruu** [stephenmcd/mezzanine#1678]
When using the model Slugged and edit for example a Blog Category. The slug is still the same. Should we not update the slug to a new unique slug when changing the Category Title?

**Comment by ryneeverett** [comment]
I don't think I agree. Changing the title is trivial but changing the slug means we have to 301 redirect indefinitely. Also, the slug isn't necessarily automatically generated; we wouldn't want to overwrite it if the user wrote it manually.

**Comment by jerivas** [comment]
It's better to avoid changing slugs on already published content to prevent
broken links. However, if you want that behavior you can wire up a signal
that fires on save to recompute the slug every time.

**Comment by jerivas** [comment]
Sorry for repeating what Ryne said, I didn't see his message until I had
sent mine.
