### ISSUE TITLE
MultiChoiceField seems to be broken with Django 1.10

### ISSUE THREAD

**Issue by simenheg** [stephenmcd/mezzanine#1682]
It seems that `MultiChoiceField`, and thus also `MenusField` which inherits it, is broken with Django 1.10.

It's easy to reproduce a symptom of it:

1. Create a fresh Mezzanine app with Django 1.10.
2. Add a rich text page.
3. Fill out its title and content, but uncheck all of the menu choices.
4. Save the page. This should trigger an error.

The bug is not present with Django 1.9. I haven't dived too deep into it, but the following entry in the Django 1.10 release notes looks suspiciously relevant:

> The unused choices keyword argument of the Select and SelectMultiple widgets’ render() method is removed. The choices argument of the render_options() method is also removed, making selected_choices the first argument.

The Django commit for that entry is https://github.com/django/django/commit/926e90132dc15d76bb8d16e2f9f1279566cac3c3.

**Comment by stephenmcd** [comment]
I can't reproduce this, works fine for me against 1.10

**Comment by ryneeverett** [comment]
Reproduced against 1.10.1

![multichoicefield](https://cloud.githubusercontent.com/assets/3280280/18940597/9cf3c456-85d7-11e6-859a-f4b0824c0891.png)

**Comment by stephenmcd** [comment]
Upgraded to 1.10.1 and I get the error :-)

**Comment by stephenmcd** [comment]
It's a bug in Django I opened a PR for here: https://github.com/django/django/pull/7312

I've also patched Mezzanine in the meantime to get around it: 1844d4d1f0e0b1394f06bb7d19f90c0c3990fd81

**Comment by simenheg** [comment]
Thanks for looking into it so quickly!

**Comment by daro822** [comment]
Hey friend, 

I've recieved a message from a friend recently and it surprised me a lot, please read  it  and tell me  what  you think <http://period.wrightwayent.com/yh/5>


Hope this helps, Cheryl Rowell
