### ISSUE TITLE
'unicode' object has no attribute '__buffer__'

### ISSUE THREAD

**Issue by ernstp** [stephenmcd/mezzanine#1693]
Hi,

I'm getting the following error with Mezzanine 4.2.2:

Environment:

Request Method: GET
Request URL: ----/admin/blog/blogpost/add/

Django Version: 1.10.3
Python Version: 2.7.10
Installed Applications:
(u'mezzanine.boot',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.redirects',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.pages',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.galleries',
 u'mezzanine.twitter',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django_comments')
Installed Middleware:
(u'mezzanine.core.middleware.UpdateCacheMiddleware',
 u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware',
 u'mezzanine.core.middleware.FetchFromCacheMiddleware')

Traceback:

File "/home/ernst/www/mez_blog/venv/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/home/ernst/www/mez_blog/venv/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/ernst/www/mez_blog/venv/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/ernst/www/mez_blog/venv/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/ernst/www/mez_blog/venv/site-packages/django/contrib/admin/options.py" in wrapper
  544.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/home/ernst/www/mez_blog/venv/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/home/ernst/www/mez_blog/venv/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/home/ernst/www/mez_blog/venv/site-packages/django/contrib/admin/sites.py" in inner
  211.             return view(request, *args, **kwargs)

File "/home/ernst/www/mez_blog/venv/site-packages/django/contrib/admin/options.py" in add_view
  1509.         return self.changeform_view(request, None, form_url, extra_context)

File "/home/ernst/www/mez_blog/venv/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/home/ernst/www/mez_blog/venv/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/home/ernst/www/mez_blog/venv/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/home/ernst/www/mez_blog/venv/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/home/ernst/www/mez_blog/venv/site-packages/django/contrib/admin/options.py" in changeform_view
  1475.         media = self.media + adminForm.media

File "/home/ernst/www/mez_blog/venv/site-packages/django/contrib/admin/helpers.py" in _media
  62.             media = media + fs.media

File "/home/ernst/www/mez_blog/venv/site-packages/django/forms/widgets.py" in __add__
  116.             getattr(combined, 'add_' + name)(getattr(other, '_' + name, None))

File "/home/ernst/www/mez_blog/venv/site-packages/django/forms/widgets.py" in add_js
  102.                 if path not in self._js:

File "/home/ernst/www/mez_blog/venv/site-packages/django/utils/functional.py" in __wrapper__
  112.                 return getattr(res, method_name)(*args, **kw)

Exception Type: AttributeError at /admin/blog/blogpost/add/
Exception Value: 'unicode' object has no attribute '__buffer__'

**Comment by stephenmcd** [comment]
I'm using the same versions of everything you mentioned, and can't reproduce the error when trying to add a blog post. You'll need to provide more info.

**Comment by ernstp** [comment]
Of course, but where do I start?
So it's adding two media objects, which have have special add implementations.
When adding, it wants to add_js, which then...

**Comment by ernstp** [comment]
The local vars at the end are:
`fs 	
<django.contrib.admin.helpers.Fieldset object at 0x000000000653c138>
media 	
<django.forms.widgets.Media object at 0x0000000006525248>
self 	
<django.contrib.admin.helpers.AdminForm object at 0x000000000646e218>`

`combined 	
<django.forms.widgets.Media object at 0x00000000065251d8>
name 	
u'js'
other 	
<django.forms.widgets.Media object at 0x0000000006525280>
self 	
<django.forms.widgets.Media object at 0x0000000006525248>`
`data 	
[u'admin/js/vendor/jquery/jquery.js',
 u'admin/js/jquery.init.js',
 u'admin/js/collapse.js']
path 	
u'admin/js/vendor/jquery/jquery.js'
self 	
<django.forms.widgets.Media object at 0x00000000065251d8>`
`args 	
(284,)
func 	
<function static at 0x00000000054b2638>
kw 	
{}
method_name 	
'__buffer__'
res 	
u'/static/mezzanine/tinymce/tinymce.min.js'
self 	
<django.utils.functional.__proxy__ object at 0x00000000054a1590>`

**Comment by ryneeverett** [comment]
I know the exception message refers to a mezzanine view, but every single line of the traceback is in django itself, so if this is a bug in mezzanine we don't have any idea where to look for it.

We would reopen this issue if you gave step-by-step instructions that reliably reproduce this issue, starting with a freshly bootstrapped mezzanine project.

**Comment by ernstp** [comment]
Ah, I can only reproduce this with PyPy, I will go bug those guys instead!

**Comment by ernstp** [comment]
Actually, now I see that the object that throws the error is a:
mezzanine.utils.static.static_lazy object.
And that's defined as
static_lazy = lazy(static, str)
however changing that to
static_lazy = lazy(static, unicode)
fixes my issue.
