### ISSUE TITLE
Mutli-Tenancy considers port as part of domain name

### ISSUE THREAD

**Issue by neverho0d** [stephenmcd/mezzanine#1696]
I found that domain name used to get Site instance includes port number as a result, when port is used in a request (http://some.domain.com:8000/), the line 44 in mezzanine/utils/sites.py:

`domain = request.get_host().lower()
`

gives "some.domain.com:8000" as a result, so your code will use default site instead of "some.domain.com" if your Mezzanine serves several sites.
Next will fix the issue:

```
domain = request.get_host().lower()
domain = domain.split(':')[0] if ':' in domain else domain
```

Alternative way is to explicitly consider the port part as a part of a domain name and add this notice to Mezzanine docs.

**Comment by stephenmcd** [comment]
You could argue either way being correct, but since it's been this way for some time, people may be depending on it, so it's probably not worth changing the behaviour at this point.
