### ISSUE TITLE
Basic installation - broken admin css

### ISSUE THREAD

**Issue by hub2** [stephenmcd/mezzanine#1704]
After installation mezzanine according to instructions posted on this page: https://www.digitalocean.com/community/tutorials/how-to-install-and-get-started-with-django-based-mezzanine-cms-on-ubuntu

Running the application and visiting /admin gives such screen:
![mezzanine-broken](https://cloud.githubusercontent.com/assets/5579578/20474999/c2e39b48-afc9-11e6-9e49-b23151488bc4.png)

I guess it's not desired output (is default css broken?). 
There are no errors mentioning css in the developer console. 
Additional Info:
python3 --version
Python 3.4.3

mezzanine-project --version
1.10.2

pip3 freeze
Django==1.10.2
Markdown==2.6.7
Mezzanine==4.2.2
Pygments==2.1.3
beautifulsoup4==4.5.1
bleach==1.4.3
chardet==2.3.0
django-contrib-comments==1.7.3
django-markdown==0.8.4
filebrowser-safe==0.4.6
future==0.15.2
html5lib==0.9999999
mezzanine-pagedown==1.0
oauthlib==2.0.0
pytz==2016.7
requests==2.11.1
requests-oauthlib==0.7.0
six==1.10.0
tzlocal==1.3

EDIT: Removing 
'<link rel="stylesheet" href="/static/mezzanine/css/admin/global.css">' fixes login screen, but I guess that's not desired fix.

**Comment by stephenmcd** [comment]
That's likely an issue with that tutorial rather than mezzanine itself. Try DO's support or the mezzanine mailing list.

**Comment by hub2** [comment]
`pip3 install grappelli-safe` fixed the issue.
