### ISSUE TITLE
Per site permissions unavailable for extended user models

### ISSUE THREAD

**Issue by Roastmaster** [stephenmcd/mezzanine#1706]
Upon visiting the permissions page for some user whose model extends the base django user model, the site permissions multiselect field is instead replaced with the form for that model.  If the user model extends multiple models, a form for all models will be shown.  

This is remedied by disabling SitePermissionMiddleware in settings.py altogether but per-site permissions are a very useful feature.

**Comment by stephenmcd** [comment]
I can't reproduce this issue considering you've neglected to provide any code that can reproduce it, but here's some code that hopefully represents what you've described, and works fine:

```
from django.contrib.auth.models import AbstractUser
from django.db import models

class Foo(models.Model):
    class Meta:
        abstract = True
    bar = models.CharField(max_length=100)

class Spam(models.Model):
    class Meta:
        abstract = True
    eggs = models.CharField(max_length=100)

class User(AbstractUser, Foo, Spam):
    baz = models.CharField(max_length=100)
```

```
from django.contrib import admin
from mezzanine.core.admin import SitePermissionUserAdmin
from .models import User

SitePermissionUserAdmin.fieldsets[1][1]["fields"] += ("bar", "baz", "eggs")

class UserAdmin(SitePermissionUserAdmin):
    pass

admin.site.register(User, UserAdmin)
```

The noteworthy part being use of `SitePermissionUserAdmin` and manually extending its `fieldsets`.
