### ISSUE TITLE
Can't log in as staff user

### ISSUE THREAD

**Issue by She110ck** [stephenmcd/mezzanine#1707]
Without superuser permission, log in as staff user doesn't work.   

Group permissions also doesn't work. 

![screenshot from 2016-12-04 19-04-07](https://cloud.githubusercontent.com/assets/11708621/20867019/7cfde7ba-ba54-11e6-8d20-5c91788acca2.png)

**Comment by ryneeverett** [comment]
I suspect you just need to select the site (127.0.0.1:8000) in the Site Permissions section at the bottom of the page in your screenshot and save again. This could definitely be a more user-friendly UI.

**Comment by stephenmcd** [comment]
I wonder if we could override the template to add a JavaScript `confirm()` if the user being added/edited isn't superuser and has no sites selected, WDYT @ryneeverett?

**Comment by ryneeverett** [comment]
Alternatively, could we send a warning with the messages framework? Seems like it would be less annoying to people who know what they're doing.

**Comment by stephenmcd** [comment]
That's a better idea

**Comment by stephenmcd** [comment]
(btw I'm working on this right now)
