### ISSUE TITLE
BLOG_USE_FEATURED_IMAGE = true ; breaks "Add Blog post" admin interface

### ISSUE THREAD

**Issue by letiferus-angelus** [stephenmcd/mezzanine#1708]
Pretty simple issue. As soon as I set 
BLOG_USE_FEATURED_IMAGE = True
in settings.py I can no longer access the form to "Add Blog post" button in the /admin/blog/blogpost/ 
When I hit the button to "Add Blog post" from that location all I see is "Other posts" and "meta data" features with no ability to actually add a blog post.
Mez ver: 4.2.2

**Comment by stephenmcd** [comment]
Works for me:

![screen shot 2016-12-08 at 12 06 55 pm](https://cloud.githubusercontent.com/assets/116385/20993526/06bdbe34-bd3f-11e6-8cda-9ce2185f01bb.png)

Please re-open the issue if you can provide enough info to reproduce the problem.
