### ISSUE TITLE
django-contrib-comments' COMMENT_MAX_LENGTH setting does not work.

### ISSUE THREAD

**Issue by logileifs** [stephenmcd/mezzanine#1709]
I tried editing this line:
`COMMENT_MAX_LENGTH = getattr(settings, 'COMMENT_MAX_LENGTH', 3000)`
to this:
`COMMENT_MAX_LENGTH = getattr(settings, 'COMMENT_MAX_LENGTH', 6000)`

and changed the `max_length` of user_name to 100 but both fields remain with the same maximum size.

I tried migrating after the changes but no changes were detected.

What is the right approach to increase the maximum length of these fields ?

**Comment by ryneeverett** [comment]
Please direct questions to [the mailing list](http://groups.google.com/group/mezzanine-users/topics).

**Comment by ryneeverett** [comment]
I haven't tried to reproduce this, but it could be a bug if mezzanine is somehow preventing the django-contrib-comments setting from working.

**Comment by ryneeverett** [comment]
@logileifs Why are you setting `COMMENT_MAX_LENGTH = getattr(settings, 'COMMENT_MAX_LENGTH', 6000)` rather than `COMMENT_MAX_LENGTH = 6000`? Shouldn't you be setting it in your `settings.py`?

**Comment by stephenmcd** [comment]
I added `COMMENT_MAX_LENGTH = 6000` to settings.py and ran `makemigrations` which generated a new migration for the comments app.

As Ryne suggested, it looks like you're simply re-assigning whatever the existing value is, which would have no effect.
