### ISSUE TITLE
Is there a way to remove comments/ratings from everywhere? 

### ISSUE THREAD

**Issue by zefoo** [stephenmcd/mezzanine#1712]
I'm new to Mezzanine (and fairly new to Python). I'm looking to get away from Drupal and use something python-based. 

Is there a way to disable comments/ratings from mezzanine completely? eg. in templates and in admin panel? From my research, this is the only thing I've found: http://bitofpixels.com/blog/disabling-mezzanine-comments/ – I also found another article saying this is not supported (although it was from 4 years ago).

I'm wondering if that link is my best option at this time (although that still leaves me with comment links in admin panel). I'm still learning the ropes so I may be missing something obvious. Thank you.

**Comment by ryneeverett** [comment]
Please direct questions to [the mailing list](https://groups.google.com/forum/#!forum/mezzanine-users).
