### ISSUE TITLE
ThreadedComment.user_name exceeds its maximum length of 50 chars

### ISSUE THREAD

**Issue by Leo-G** [stephenmcd/mezzanine#1713]
Get a lot of such warnings while importing from wordpress any idea how i can resolve it?

**Comment by ryneeverett** [comment]
Seems like our importer should truncate names automatically, though a warning would likely be appropriate.

**Comment by Leo-G** [comment]
I am not sure if should truncate automatically but it gives an option to increase the char limit, but i have 100's of comments and I don't want to type in character limits for each n every one of them, I think there should be a way to automate this

**Comment by stephenmcd** [comment]
The `--noinput` option will automatically truncate any values that are too long.

Alternatively you could fork/modify the `django-contrib-comments` package to increase the field length.
