### ISSUE TITLE
Enhancement: introduce LOCAL_SETTINGS_MODULE variable

### ISSUE THREAD

**Issue by melvyn-sopacua** [stephenmcd/mezzanine#1717]
I'm currently working with the following patch to `PROJECT_APP_PATH/settings.py`:

```diff
-f = os.path.join(PROJECT_APP_PATH, "local_settings.py")
+local_module = os.getenv("LOCAL_SETTINGS_MODULE", "local_settings.py")
+f = os.path.join(PROJECT_APP_PATH, local_module)
+
 if os.path.exists(f):
     import sys
     import imp
-    module_name = "%s.local_settings" % PROJECT_APP
+    module_name = "{}.{}".format(PROJECT_APP, local_module[0:-3])
     module = imp.new_module(module_name)
     module.__file__ = f
     sys.modules[module_name] = module
```
The primary reason is to be able to quickly turn on/off `modeltranslation` for migrations.
I've done this by creating `PROJECT_APP_PATH/local_migration_settings.py` like so:
```python
from .local_settings import *

USE_MODELTRANSLATION = False
```
This works splendidly:
```console
env LOCAL_SETTINGS_MODULE=local_migration_settings.py python3 manage.py createdb         
Operations to perform:
  Apply all migrations: admin, auth, blog, conf, contenttypes, core, django_comments, forms, galleries, generic, pages, redirects, sessions, sites, twitter
Running migrations:
...
...
Hit enter to use the default (amnesia): example.com

Creating default site record: example.com ...
# ===> No prompt for translations
Installed 2 object(s) from 1 fixture(s)

Would you like to install some initial demo pages?
```
If there's any interest, I can make a PR it. If not, I'll happily keep it local.

**Comment by stephenmcd** [comment]
Don't think it's worth adding a setting for, thanks anyway.

**Comment by stephenmcd** [comment]
BTW you can probably achieve this already with almost the same approach via the `DJANGO_SETTINGS_MODULE` env var.

**Comment by ryneeverett** [comment]
I have no opinion on this issue and don't know much about modeltranslations, but I'm not sure your use case aligns with the intent of local settings:

> \# Allow any settings to be defined in local_settings.py which should be
> \# ignored in your version control system allowing for settings to be
> \# defined per machine.

It seems like your `local_migration_settings.py` is necessary for the development of your project and therefore you'd want it on every development machine and in version control.

Also, couldn't you achieve the exact same behaviour by setting the existing variable `DJANGO_SETTINGS_MODULE=/path/to/myproject/local_migration_settings.py` and changing it to:

```py
from .settings import *
from .local_settings import *

USE_MODELTRANSLATION = False
```
