### ISSUE TITLE
Blog categories cannot be deleted within Admin

### ISSUE THREAD

**Issue by petedermott** [stephenmcd/mezzanine#1724]
I have just noticed that once a blog category has being created it cannot be removed via the admin area. Whilst manually deleting the entry in the blog_blogcategory table will fix the issue it will not reassign the blogs new categories and is not particularly friendly from a none-technical user point of view.

**Comment by stephenmcd** [comment]
You can add `BlogCategoryAdmin` to `ADMIN_MENU_ORDER`, see: http://mezzanine.jupo.org/docs/admin-customization.html#navigation
