### ISSUE TITLE
filebrowser - Cannot add another image

### ISSUE THREAD

**Issue by etionsun** [stephenmcd/mezzanine#1726]
Steps:
1.Create new mezzanine project
2.Create DB
3. Login admin
4.Edit Gallery page
5.Upload images
6.Click add another image link

The new edit line:

```
<a style="padding:5px 16px;" href="javascript:FileBrowser.show('**id_images-__prefix__-file**', '/admin/media-library/browse/?pop=1&amp;dir=galleries&amp;type=Image');" class="fb_show">
    <img src="/static/filebrowser/img/filebrowser_icon_show.gif" alt="">
</a>
```

The first param is invalid for show function.

so the js error is : 
```
Uncaught TypeError: Cannot set property 'value' of null
    at FileSubmit (FB_FileBrowseField.js:16)
```

**Comment by nielsonsantana** [comment]
Having the same problem. 
Anyone knows the last version that worked(including grappelli-safe and filebrowser-safe)?
I have a production app and need add a new image on galery.

**Comment by ryneeverett** [comment]
As of [filebrowser-safe#93](https://github.com/stephenmcd/filebrowser-safe/pull/93), this should be fixed. At any rate the error line you reference no longer exists. For more detail see discussion in [grappelli-safe#79](https://github.com/stephenmcd/grappelli-safe/pull/79).

**Comment by nielsonsantana** [comment]
@ryneeverett, any idea about the release to fix it?
I still without solution for this problem.

**Comment by stephenmcd** [comment]
@nielsonsantana soon
