### ISSUE TITLE
"Link List" entry in TinyMCE Add/Edit Link popup is missing

### ISSUE THREAD

**Issue by molokov** [stephenmcd/mezzanine#1728]
When adding or editing a link on a page (either on Admin or Front end), the 'Link List' entry is not shown.

This is still the case with Mezzanine HEAD ( 0388f7c ) and a brand new empty project.

The definition of window.__link_list_url looks to be fine (it's pointing to /admin/displayable_links.js, which also loads the correct data), but for some reason the TinyMCE window isn't showing this.

Using Firefox's Javascript debugger, it appears that when tinymce_setup.js is being parsed (thus defining tinymce_setup.link_list), window.__link_list_url is not yet defined, but it becomes defined after this point.

Perhaps there is some sort of ordering error?

**Comment by stephenmcd** [comment]
You're right the ordering was incorrect, pushing a fix now. Thanks for the report.
