### ISSUE TITLE
Use flake8 instead of pyflakes and pep8

### ISSUE THREAD

**Issue by spookylukey** [stephenmcd/mezzanine#1736]
When trying to contribute, I struggled with unhelpful pep8/pyflakes issues on https://github.com/stephenmcd/mezzanine/pull/1734 and eventually found the workarounds to 'fix' the issue - https://github.com/stephenmcd/mezzanine/blob/c7bc3e74d8487c6b23417ac099a46aa5c486c369/mezzanine/utils/tests.py#L22

It seems like flake8 would be a much better option:

* It has a builtin, standard way of ignoring specific errors, for both PEP8 and its own, rather than requiring people to dig around and eventually find the custom workarounds like I did.
* It has a builtin way of ignoring errors on a specific line, or even just a [specific error on a specific line](http://flake8.readthedocs.io/en/latest/user/ignoring-errors.html#in-line-ignoring-errors), rather than having to blanket ignore a whole set of errors.
* It is configurable and extensible, and well documented.
* It has various very useful plugins. For example, I use [flake8-future-import](https://pypi.python.org/pypi/flake8-future-import) to help eliminate a whole set of unicode issues.
* In my experience it generally has better editor integration and better adoption in the community, making it easier for people to use it immediately, and obey it without having to run tests. Because it can be configured from a config file, warnings that appear inline in the editor are the same as required by the test suite, which is vital IMO.

**Comment by jerivas** [comment]
I've been using flake8 to lint Python directly on my text editor and find
it very useful. Seems like a good idea.

**Comment by stephenmcd** [comment]
Sounds good to me.

**Comment by jerivas** [comment]
As of https://github.com/stephenmcd/mezzanine/commit/82dd9f1d4752da402573adc37b53b2e8573fe76a we're now using black + pep8
