### ISSUE TITLE
Caching templates

### ISSUE THREAD

**Issue by andresmrm** [stephenmcd/mezzanine#1739]
Hi! Reading about Django optimizations I saw:
https://docs.djangoproject.com/en/1.10/ref/templates/api/#django.template.loaders.cached.Loader

I saw Mezzanine settings uses `"APP_DIRS": True` instead of `django.template.loaders.cached.Loader`.
Does this default config already caches templates?

**Comment by stephenmcd** [comment]
Please use the mailing list for questions.
