### ISSUE TITLE
project template for urls.py needs to define name "mezzanine"

### ISSUE THREAD

**Issue by mjpritchard** [stephenmcd/mezzanine#1740]
Commented-out examples in urls.py template currently leave "mezzanine" undefined.
Cause error if un-commented, for example to change to editable home page.
May have been missed in testing since they're commented out?

Example:
`line 56: # url("^$", mezzanine.pages.views.page, {"slug": "/"}, name="home"),`
If this is un-commented, results in error:
`url("^$", mezzanine.pages.views.page, {"slug": "/"}, name="home"),
NameError: name 'mezzanine' is not defined`

(and other instances).
Solved by 
`import mezzanine`
or 
`from mezzanine.pages.views import page`
and
`url("^$", page, {"slug": "/"}, name="home"),`

**Comment by stephenmcd** [comment]
The previous line in the comments instructs you to do the import.
