### ISSUE TITLE
Mezzanine failing because of bleach dependency

### ISSUE THREAD

**Issue by fdhenard** [stephenmcd/mezzanine#1744]
bleach was upgraded to 2.0 recently with apparently breaking changes.  Mezzanine's dependencies in setup.py specify bleach>=1.4.  I downgraded to >=1.4,<2.0, and I'm not getting the errors.

This problem occurs in Mezzanine 4.2.2

**Comment by jerivas** [comment]
Mezzanine 4.2.3 has just been released with the fix.

**Comment by fdhenard** [comment]
Nice.  Thanks!
