### ISSUE TITLE
Form field Help Text is too short

### ISSUE THREAD

**Issue by jerivas** [stephenmcd/mezzanine#1753]
Right now the form fields created with `mezzanine.forms` limit the `help_text` to just 100 characters (see [forms/models.py](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/forms/models.py#L68)). Form fields that require a disclaimer or lengthy explanation are being cut off in the help text, so my users have been working around it by putting all the text in the label (which has a limit of 200 and can be raised above that).

What do you think of making the `help_text` limit configurable?

**Comment by jerivas** [comment]
Actually, it might be better to convert the Label and Help Text into `TextField`, and enforce the length in the admin form. That way they are limitless in the DB and won't require migrations when the length settings are changed.

**Comment by jerivas** [comment]
Also, I volunteer to implement this, just want to get the thoughts from the rest of the team.

**Comment by stephenmcd** [comment]
TextField sounds good. Thanks Ed!
