### ISSUE TITLE
Problem saving costumized table and custom source code

### ISSUE THREAD

**Issue by slosimon** [stephenmcd/mezzanine#1761]
It simply doesn't want to save a table with background color and border color. When it is saved, it turns to white again. also <iframe> (Youtube embeded doesn't work (it disappears)). No solution has been found yet.

**Comment by jerivas** [comment]
Mezzanine uses Bleach to sanitize HTML from RichText fields. You can set 
the desired filtering level in the admin by going to Site > Settings and 
looking for "filter level" (see 
http://mezzanine.jupo.org/docs/configuration.html#richtext-filter-level). 
This can be configured to allow iframes, or to disable filtering at all.

If you don't want to disable filtering completely, you can specify which 
tags, attributes, and style should be allowed by providing white lists 
in your settings.py. See: 
http://mezzanine.jupo.org/docs/configuration.html#richtext-allowed-attributes

**Comment by slosimon** [comment]
Thanks!!

I cound't find that solution! It worked as it should have :)
