### ISSUE TITLE
Button to create new page

### ISSUE THREAD

**Issue by Dacastror** [stephenmcd/mezzanine#1762]
Hi, I'm new to Mezzanine and django, in this moment I'm trying to make a button in a page template, the idea is to allow the registered user to do two things:

- create a new daughter page of the current page
- add an access link to a list of links of the current page

I would like to make a popup appear that asks for the name and content of the new page, I do not know if what I need is very complex to do with mezzanine, I study the djangogirls tutorial (tutorial.djangogirls.org) and I reviewed the examples of the mezzanine documentation (mezzanine.jupo.org/docs/content-architecture.html), but I do not see how to do what I need, this is the link for my mezzanine project: github.com/Dacastror/inicio_mezzanine

in advance I appreciate the help.

-

**Comment by stephenmcd** [comment]
Can you post this to the mailing list instead? Thanks
