### ISSUE TITLE
Admin setting translatable filed not activate(code) value in django-admin

### ISSUE THREAD

**Issue by kmlebedev** [stephenmcd/mezzanine#1768]
Hi 
If USE_MODELTRANSLATION = True
Not work translation  translatable filed in django-admin Site settings

**Comment by stephenmcd** [comment]
Works fine for me using Django 1.11 and the development branch of this repo which a fix for modeltranslation was recently pushed to. I'd suggest giving that a try, and if you're still unable to get things working, please post to the mailing list, preferably with a lot more info than provided here.
