### ISSUE TITLE
Bleach 2.0 compatibility issue

### ISSUE THREAD

**Issue by jlmenut** [stephenmcd/mezzanine#1769]
Hello,

I just installed a fresh version of mezzanine (4.2.3) and it seems there is an incompatibility with the bleach version 2.0 which was installed along. I get the error:  

`ImportError: No module named base `

If I downgrade to 1.5 it works fine though

Best regards

**Comment by kenbolton** [comment]
This looks like a duplicate of #1741 and #1757. Are you using `mezzanine-pagedown`?

**Comment by jlmenut** [comment]
Not that I'm aware I just did a` pip install mezzanine`, and I had no previous install. There is nothing in `pip list `either

**Comment by stephenmcd** [comment]
See https://github.com/mozilla/bleach/issues/267
