### ISSUE TITLE
Admin sub-pages drop-down menu gone

### ISSUE THREAD

**Issue by wgoedeck** [stephenmcd/mezzanine#1770]
I have used Mezzanine quite a few times - works quite well! 

I have noticed a problem though, when I create a webpage. While the admin content/pages allows the addition of a page with a drop-down menu for choices, such as rich text page, form, link, etc., the sub-pages or child pages do not have a functional drop-down selection. 

I have not figured out why, although I sometimes can get this feature to return if I restart a project. Any suggestions?

Walter Goedecke
walter[@snowbears.org

**Comment by stephenmcd** [comment]
Works fine for me:

![screen shot 2017-06-14 at 3 12 50 pm](https://user-images.githubusercontent.com/116385/27116371-36bc3552-5114-11e7-8aae-b0a07550e864.png)

Please re-open if you think you can provide the necessary info to reproduce the problem. I'd also suggest posting your question to the mailing list.

**Comment by wgoedeck** [comment]
Hi Stephen, 

The problem of the sub-pages not having a drop-down selection still persists with me, even though it does not show up with your example. Would you please go to http://geos.webfactional.com/admin/pages/page/ - you can login with your first name, and I'll give you the password separately. The website is experimental, so don't worry about messing it up. 

You can see that the top "Add" selection allows Rich text page, Form, &c., but the sub pages "Add" selections on the Home, Quick Instructions, &c. pages do not have a drop-down selection. I have this problem often now, and a I can't troubleshoot it. Perhaps you can give me a suggestion or two.

Thanks very much,
Walter Goedecke

**Comment by wgoedeck** [comment]
Hi Stephen, 

The problem of the sub-pages not having a drop-down selection still persists with me, even though it does not show up with your example. Would you please go to http://geos.webfactional.com/admin/pages/page/ - you can login with your first name, and I'll give you the password separately. The website is experimental, so don't worry about messing it up. 

You can see that the top "Add" selection allows Rich text page, Form, &c., but the sub pages "Add" selections on the Home, Quick Instructions, &c. pages do not have a drop-down selection. I have this problem often now, and a I can't troubleshoot it. Perhaps you can give me a suggestion or two.

Thanks very much,
Walter Goedecke

**Comment by wgoedeck** [comment]
I did find the problem: the project/templates file was corrupted somehow. This is the directory that gets created by the collecttemplates command. 

Walter
