### ISSUE TITLE
Python 3.6.1 No matching distribution found for mezzanine

### ISSUE THREAD

**Issue by mactrash** [stephenmcd/mezzanine#1777]
Just download the python 3 and it is now 3.6.1

And try to pip install messznine, but it got a error No matching distribution found for mezzanine.

May I ask what is the best python version to use for mezzanine?

**Comment by jerivas** [comment]
I created a virtualenv with Python 3.6.1 and installed Mezzanine without issue. Is your version of pip up to date?

**Comment by jerivas** [comment]
Closing for now. Please re-open if you can provide more details.
