### ISSUE TITLE
User-defined grouping of the settings variables listing in the admin 

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [stephenmcd/mezzanine#1778]
Mezzanine allows settings variables to be edited in the Django admin interface.
In the admin form the variables are grouped by the substring of the variable name that precede the first underscore. E.g. MY_VARIABLE_1, MY_VARIABLE_2 will be grouped under a MY section.

It can be quite inconvenient when Django or custom settings variables are already defined and used by a project but needs to be exposed on the admin form. It is obviously possible to rename the variables so the ones which have related meaning have a common prefix. However this is quite a big constraint and may cause a lot of changes in the code.

It would be much more convenient instead to add a parameter to the config variables declared to Mezzanine to specify a group key. e.g.

```
register_setting(
    name="MY_VARIABLE_1",
    description="my first config variable",
    editable=True,
    default=0,
    group='group1',
)

register_setting_group('group1', 'My First Group')

```

It's just an illustration, membership to a group and the group label could obviously be declared using different constructs (e.g. dictionary of list: register_setting_groups({'group1': {label: 'My First Group', 'vars': ['MY_VARIABLE_1', 'MY_VARIABLE_2']}}) ).

**Comment by stephenmcd** [comment]
PR welcome - my only suggestion is to not bother with `register_setting_group`, the value passed to the `group` arg can just be the label.
