### ISSUE TITLE
Pagination not rendering (and possibly other inclusion tags)

### ISSUE THREAD

**Issue by jerivas** [stephenmcd/mezzanine#1780]
I'm trying out the master branch with Django 1.11 and Python 3.6.1, and noticed the pagination controls are not rendered. I managed to track it down to Mezzanine's version of [`inclusion_tag`](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/template/__init__.py#L104). The workaround is to not override this method so we just use Django's version, but we lose per-device templates.

I tried to further debug this but I feel lost in the guts of the template system 😅

**Comment by jerivas** [comment]
A bit out off topic, but this made me think we could shed a lot of code if we get rid of `mezzanine.mobile`.

**Comment by stephenmcd** [comment]
> A bit out off topic, but this made me think we could shed a lot of code if we get rid of mezzanine.mobile.

I was thinking the same thing :-)

**Comment by stephenmcd** [comment]
Actually I was thinking of getting rid of multi-device handling entirely, or would that be too much?

**Comment by jerivas** [comment]
I think I've used the device detection only once. I'm okay with axing it.

**Comment by stephenmcd** [comment]
Actually all the code I was thinking we'd be able to remove (basically everything that loads different templates based on the request) is required for host-specific themes as well. I think that's probably used more than device-specific templates, but the usage maybe very low too.

**Comment by stephenmcd** [comment]
Actually without host-specific themes, the whole multi-site support becomes very limited. Unless I'm missing something I think all the code supporting "different templates based on request" needs to stay.

**Comment by jerivas** [comment]
Oh, that's right, we definitely want to keep host themes.

**Comment by jerivas** [comment]
I'm wondering, now that Django has a reworked the template system, maybe we can create our own template engine and shim the host theme support there, instead of plugin into several places?

**Comment by stephenmcd** [comment]
Sure. I've no idea what that would look like, but if it means we can support everything in one place instead of many like you said, then I'm all for it.

**Comment by jerivas** [comment]
My idea is to create our own template loader that loads different templates depending on the request (where we can get the site and device info). Turns out this is a pretty old idea: http://opensource.washingtontimes.com/blog/2010/feb/17/loading-templates-based-request-headers-django/index.html

I'll hack something together now.

**Comment by stephenmcd** [comment]
Cool! Thanks Ed

**Comment by jerivas** [comment]
So, I discovered a few things:

- Host themes and per-device templates are implemented in separate middleware.
- Host themes can be easily replaced with a custom loader. It gets rid of the `TemplateForHostMiddleware` but requires a change in settings of existing projects. See [relevant commit](https://github.com/jerivas/mezzanine/commit/7cf2cc5202b5db1b0f8bde2af0f0ab8c14bb363e).
- Independent of that, we can completely remove per-device templates and `mezzanine-mobile` with almost no impact on anyone not using them. Existing projects will only need to remove `TemplateForDeviceMiddleware` from their settings. See [this commit](https://github.com/jerivas/mezzanine/commit/c3dffe83c79b41873310d8be8d647f775d7ef824).

Specifically, removing per-device templates will fix this issue, so I can go ahead and create a PR for that. Host themes can stay as middleware, but let me know your thoughts about converting it to a custom loader. The difference is that it's technically more "correct" to do it as a loader, and at the end of the day is less code than the middleware.

**Comment by jerivas** [comment]
Actually there's an advantage to using the loader approach for host themes: the host will be checked not only for the final template in `TemplateResponse`, but wherever a template is loaded (normal includes, template tags, etc).

**Comment by jerivas** [comment]
After using this for a few days I'm very happy with the loader approach for host themes because it lets me override any template, not just the final template rendered by a view. This makes it super easy to have a separate `base.html` for each site while they share all other templates, or to override specific includes (like using a different pagination template on a per-host basis).

I'm going to open two PRs to discuss these issues separately: one about the loader-based host themes, and another one removing the user-agent and device detection (that one will actually solve this bug).

**Comment by stephenmcd** [comment]
Sounds good!

**Comment by jerivas** [comment]
Remove device support: https://github.com/stephenmcd/mezzanine/pull/1783

**Comment by jerivas** [comment]
Host-detection via template loader: #1784

**Comment by wonderbeyond** [comment]
Cool.

**Comment by wonderbeyond** [comment]
So, in future release, we can provide a custom middleware for **host themes** or **device-specific-templates**?

```python
class MyThemeSelectionMiddleware(object):
    def process_view(self, request, view_func, view_args, view_kwargs):
        if request.user_agent in ['android', 'ios']:
            request.template_name = 'mobile'
        if request.host == 'dark.example.com':
            request.template_name = 'dark'

        return None
```

and then, mezzanine's own template loader will select the right template based on `request.template_name`?

**Comment by jerivas** [comment]
Host themes still work as before, so no need to change anything there. If you require device-specific templates, consider using a standalone package, like https://github.com/gregmuellegger/django-mobile
