### ISSUE TITLE
Image thumbnailing in the gallery admin

### ISSUE THREAD

**Issue by CheapSeth** [stephenmcd/mezzanine#1785]
The administration interface displays images at their full size, which is non-ergonomic on the average screen (see attached file).

![output](https://user-images.githubusercontent.com/2217036/28830503-2e2d6490-76d7-11e7-93ee-6d10ef29a484.png)

I can PR an easy fix (limiting the thumbnails to an arbitrary size for example) however I thought it might be better to ask if it was intentional and/or if this fix would be deemed acceptable.

**Comment by jerivas** [comment]
Hello! Mezzanine actually uses thumbnails in the gallery admin. This looks like Pillow (the imaging library) is having trouble generating the thumbnails.

An issue was reported recently regarding the use of Pillow >= 4.2.0. Can you check if installing Mezzanine from master helps? See: https://github.com/stephenmcd/mezzanine/issues/1781.

Alternatively, could you check if downgrading to Pillow 4.1.1 helps?

**Comment by CheapSeth** [comment]
Downgrading Pillow to 4.1.1 indeed helped, thank you!

Installing from master and using the latest Pillow version also seemed to solve the problem.

For the record, I am using Mezzanine 4.2.3 from pip.

**Comment by logileifs** [comment]
How about pinning the Pillow dependency properly to solve the issue instead of just closing the issue?
https://github.com/stephenmcd/mezzanine/blob/521a98c39bb6351c4b46067069f33caf95fe0a5e/setup.py#L63 this line should be `pillow==4.1.1`

**Comment by jerivas** [comment]
pip won't install Pillow 4.1.1 since it's not the latest version anymore. Specifying that requirement will leave new projects with an old version of Pillow.

**Comment by logileifs** [comment]
@jerivas you can pin the version of pillow in setup.py to the highest version known to work similarly as is done with [django](https://github.com/stephenmcd/mezzanine/blob/521a98c39bb6351c4b46067069f33caf95fe0a5e/setup.py#L54) and pip will install that version
