### ISSUE TITLE
Link's slug field is hidden in admin-change-view when linked to an internal URL which has an explicitly defined urlpattern

### ISSUE THREAD

**Issue by wonderbeyond** [stephenmcd/mezzanine#1789]
Environments

- Django==1.10.7
- git+https://github.com/stephenmcd/mezzanine.git@e0389b63cfbb5a03f33624e4179f3cce6a75ccae

---

url.py:
```python
    # ...
    url("^news/", include("news.urls")),
    # ...
```

news/urls.py
```python
urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', DetailView.as_view(model=Article), name='article-detail'),
    url(r'^$', ArticleList.as_view(), name='article-list')
]
```

Then I created a Link to the internal `article-list`:
![image](https://user-images.githubusercontent.com/228361/29406830-def716a0-8374-11e7-84c9-0489b9251e47.png)

Then it reveals in the navigation, and can lead me to `article-list` as expected.

However, when I change the Link in admin, the slug filed is just hidden:
![image](https://user-images.githubusercontent.com/228361/29407095-ca9d43b8-8375-11e7-95d3-ae8a44aecd72.png)

I've looked into the code, and found the stuff, but I dont know what's the real consideration.

https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/pages/admin.py#L78
https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/pages/models.py#L185

**Comment by stephenmcd** [comment]
Please don't open issues to ask questions - use the mailing list.

**Comment by wonderbeyond** [comment]
@stephenmcd I opened this issue because I thought it might be a logical error of making slug invisible and non-editable.
