### ISSUE TITLE
collecttemplates: more options for template hierarchies

### ISSUE THREAD

**Issue by melvyn-sopacua** [stephenmcd/mezzanine#1793]
Multi-level apps that use only a `templates` directory in the main app ([example](https://github.com/pennersr/django-allauth/tree/master/allauth/templates)) cannot be referenced conveniently. Fixable by adding a `--subdir` or `--template-root` option. Using this issue for consensus.

Use case for this:
I want all templates copied for 'allauth.socialaccount' app, which reside in `allauth/templates/socialaccount`. Could be done using:

     python manage.py collecttemplates --subdir socialaccount allauth

Which is a bit counter-intuitive. Better would be:

    python manage.py collecttemplates --template-root 'allauth.templates' socialaccount

In both cases though, you already need to know the structure, so you may as well copy by hand by the time you figure it out.

So, the most intuitive approach is:

    python manage.py collecttemplates socialaccount

At which point, mezzanine resolves app_label to import and module path. If no templates subdir, moves up the import path (`allauth`) and checks for `templates/socialaccount` subdirectory there. If not found we can give up and nobody would blame us.

A fourth and "looking forward" option is to actually use the AppConfig framework and check for a "get_template_root" callable, which would return the path to the template root for that specific app (even if a sub app).

**Comment by stephenmcd** [comment]
It's really only intended for the built-in apps which don't suffer from this problem.
