### ISSUE TITLE
Custom page_not_found view doesn't accept exception argument (new in Django 1.9)

### ISSUE THREAD

**Issue by eliasdorneles** [stephenmcd/mezzanine#1795]
Django 1.9 introduced the `exception` argument for the error404 handler: https://docs.djangoproject.com/en/1.9/ref/views/#http-not-found-view

The [current `page_not_found` handler only accepts request and template_name](https://github.com/stephenmcd/mezzanine/blob/8cf8d717de53095b41135c658733e2ab5f0ec71d/mezzanine/core/views.py#L199-L209).

**Comment by stephenmcd** [comment]
What problem does this cause?
