### ISSUE TITLE
Customizing search URL

### ISSUE THREAD

**Issue by simenheg** [stephenmcd/mezzanine#1797]
Hi, I’m wondering whether there is any smart way to customize the URL used for the built-in Mezzanine search view besides the methods mentioned below.

Say that you want to change the search URL from the default `search` to `my-search`. A first attempt might be:

```python
url("^my-search/$", search, name="search"),
url("^", include("mezzanine.urls")),
```

Now you get a search page at `my-search`, but the search view still redirects to Mezzanine’s `search` since that one is registered later.

This will fix it, but it doesn’t feel optimal:

```python
url("^(?!my-search/)", include("mezzanine.urls")),
url("^my-search/$", search, name="search"),
```

Another approach is to give `my-search` another name, copying `search_form.html` from Mezzanine and changing `{% url "search" %}` to use the new name. This works fine, but it feels a bit wasteful unless you’d like to customize the template some more, and it creates more work if you’d like to receive updates to `search_form.html` from future Mezzanine versions.

Could a cure for all of this be to add a setting for the search URL, defaulting to `search`?

**Comment by stephenmcd** [comment]
You should post this to the mailing list, thanks.
