### ISSUE TITLE
Mezzanine ignores the view, displays the template but does not pass the context.

### ISSUE THREAD

**Issue by rainell** [stephenmcd/mezzanine#1802]
Hello,
I created a view for my model, with the corresponding urls and template files. Then, in the admin panel, I have created a Rich text page, specifying the same URL (ingredients) defined in urlpatterns. Mezzanine ignores the view, displays the template but does not pass the context. How can I solve it?

These are the codes:

### models.py
    from django.db import models
    from mezzanine.pages.models import Page
    from django.utils.translation import ugettext_lazy as _

    class Ingredient(Page):
        name = models.CharField(max_length=60)
        information = models.TextField(null=True, blank=True, verbose_name=_("Description"))

### views.py
    from django.template.response import TemplateResponse
    from .models import Ingredient

    def ingredients(request):
        ingredients = Ingredient.objects.all().order_by('name')
        templates = ["pages/ingredients.html"]
        return TemplateResponse(request, templates, {'ingredients':ingredients})

### urls.py
    from django.conf.urls import url
    from .views import ingredients

    urlpatterns = [
        url("^$", ingredients, name="ingredients"),
    ]

**Comment by ryneeverett** [comment]
Please use [the mailing list](https://groups.google.com/forum/#!forum/mezzanine-users) for questions.
