### ISSUE TITLE
500 Error in Admin (admin/login) when CachedFilesMixin is used

### ISSUE THREAD

**Issue by awartani** [stephenmcd/mezzanine#1805]
```
class NonPackagingS3PipelineCachedStorage(
        NonPackagingMixin, PipelineMixin, CachedFilesMixin, S3BotoStorage):
    location = 'static'
```

```
STATICFILES_STORAGE = 'storage.NonPackagingS3PipelineCachedStorage'
```

with `DEBUG=True`

Will lead to a 500 error. 

Debugging it for a while, it turned out that the root cause of this
```
window.__admin_media_prefix__ = '{% static "admin" %}/';
```
https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/templates/admin/base_site.html#L21

because it tries to use Static engine to convert a directory to a file.

**Comment by stephenmcd** [comment]
As per #1806
