### ISSUE TITLE
External Links Break Upon Being Moved to a Child in the Pages Menu

### ISSUE THREAD

**Issue by GGerikP** [stephenmcd/mezzanine#1808]
Hi guys,

This is a pretty simple bug and the first I've submitted to you, so just let me know if I've missed anything.

I have run the tests and it passes.

My changes are here on the Master branch:
git@github.com:GGerikP/mezzanine.git

I am using:
$ mezzanine-project --version
1.10.5

$ python3 --version
Python 3.5.3

**Steps to Reproduce:**

GIVEN You have already created a standard mezzanine application with at least 1 one other page.

1) Create a "Link" Page in the Admin Screens via the Pages menu (mydomain.com/admin/pages/page)
1.1) Be sure the URL is an external link: (i.e. something like: https://www.google.com)

2) Via the Pages Menu again: Move the new Link page from being a sibling of any top level.
![child-link-url](https://user-images.githubusercontent.com/2165882/30998420-360690b8-a483-11e7-9817-cc77881eb8c0.png)

Expected Result:
External Links should not have paths appended to them.
The URL Link in the page should be: `https://www.google.com`

Actual Result:
Regardless of the type of URL given, the path will always include the parent path.
The URL Link is: `<parent-path>https://www.google.com`

**Comment by GGerikP** [comment]
This is easily fixed by:
updating mezzanine.pages.models.py

Update:
`177        if self_slug:`

To:
`        if self_slug and (self.content_model == "link" and (not self.slug.startswith("http"))):`

**Comment by stephenmcd** [comment]
Could you create a pull request with the fix? I think you only need to check for the link model, not the http prefix. I don't recall specifically, but off the top of my head I believe only external links are supported.

**Comment by jerivas** [comment]
Internal links are supported as well (I use them quite a bit to add menu 
entries for urls that have their own views).

**Comment by stephenmcd** [comment]
Thanks Ed, I stand corrected.

**Comment by GGerikP** [comment]
Sure thing guys.  Seems I ran my test against the wrong version of the code so when I did again there was a logical error I had to fix.  One way or another it's working now and verified here's a link to the pull request: https://github.com/stephenmcd/mezzanine/pull/1811

Additionally, here is the output of the latest test results.  I don't like that there are so many warnings, but that's all they seem to be.  Additionally, I had to make a fix in my django code (related to the "future" tag outlined in this bug but in the grappelli_safe/templates/registration/password_reset_email.html file: https://github.com/alsoicode/django-admin-sortable/issues/151) in order to get the tests to run.

[TEST-LOG-bugfix_1808_external_child_links.txt](https://github.com/stephenmcd/mezzanine/files/1354717/TEST-LOG-bugfix_1808_external_child_links.txt)

Cheers.

**Comment by stephenmcd** [comment]
#1811
