### ISSUE TITLE
In-line Editing: If editable text is white, it comes through the in-line editing form white as well, making the form appear empty

### ISSUE THREAD

**Issue by awright91** [stephenmcd/mezzanine#1814]
Hello!
I've only been playing around with Mezzanine for a few weeks(loving it so far), but have been working with Django for a while now. I really enjoy Mezzanine's in-line editing, but I found one issue. 

Scenario: Let's say you're building a landing page with a full-width image and you want the text overtop of the image to be editable. The image is pretty dark, so you want the text to be white, like in the image below:

![image](https://user-images.githubusercontent.com/20651992/31519880-f0971da0-af71-11e7-90cc-e89375b9b377.png)

When you click the Edit button, the form appears empty, but only because the text is white, as you can see in this image: 

![image](https://user-images.githubusercontent.com/20651992/31519980-48684414-af72-11e7-9915-30460b6185e9.png)

I found a very simple one-line CSS fix, so if you all don't mind, I'd love to submit a PR for this. 

I've been wanting to contribute to some open source projects and I think Mezzanine is really awesome, so I'd love for this to be my first open source contribution, if it's cool with you all. 

Let me know and I'll submit a PR!

**Comment by stephenmcd** [comment]
Please go for it. Note there's a CSS file specifically for this here:

https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/static/mezzanine/css/editable.css
