### ISSUE TITLE
mezzanine_api - Could not import 'rest_framework.filters.DjangoFilterBackend'

### ISSUE THREAD

**Issue by mike1573** [stephenmcd/mezzanine#1818]
Hi, I'm getting;

ImportError: Could not import 'rest_framework.filters.DjangoFilterBackend' for API setting 'DEFAULT_FILTER_BACKENDS'. AttributeError: 'module' object has no attribute 'DjangoFilterBackend'.

...after completing the installation re http://gcushen.github.io/mezzanine-api/

Appears DjangoFilterBackend is not longer supported in 'rest_framework' but is in 'rest_framework_filters'.
I've tried a number of options to reconfigure but cannot get it to work. How can I fix?

Mezzanine 4.2.3
Django 1.10.8
Python 2.7.6
SQLite 3.8.2

    INSTALLED_APPS = [
        'mezzanine_api',
    #  'rest_framework_filters',
        'rest_framework',
        'rest_framework_swagger',
        'oauth2_provider',

Thanks

**Comment by stephenmcd** [comment]
Please file this against that project.

**Comment by mike1573** [comment]
ok will do...

**Comment by jakubjanuzik** [comment]
Hey @mike1573 

Try another version of DRF. For example `pip install djangorestframework==3.5.0`. 

Worked for me,
Best, Jacob.
