### ISSUE TITLE
Case insensitive username login

### ISSUE THREAD

**Issue by cjh79** [stephenmcd/mezzanine#1821]
Is there is a reason `mezzanine.core.auth_backends.MezzanineBackend` doesn't support case-insensitive usernames for logging in? `mezzanine.accounts.forms.ProfileForm` enforces case-insensitive username uniqueness when registering, so it seems like it would be natural to allow them for logging in. It feels like a bug that it doesn't.

This seems like it would be a very simple change, I would be happy to put together a PR.

**Comment by stephenmcd** [comment]
I don't think it's a bug, but can you post this to the mailing list instead? Thanks
