### ISSUE TITLE
mezzanine.utils.render django 1.11 incompatibiliy

### ISSUE THREAD

**Issue by Eladio** [stephenmcd/mezzanine#1824]
Dear Developers,

I think due to this Backwards incompatible change in Django 1.11:

https://docs.djangoproject.com/en/1.11/releases/1.11/#django-template-backends-django-template-render-prohibits-non-dict-context

The mezzanine.utils.views.render function fails with 
TypeError: context must be a dict rather than RequestContext.

There may be other functions using RequestContexts...

Regards,
Előd

**Comment by jerivas** [comment]
Hi Előd.

Mezzanine is already compatible with Django 1.11 in the master branch. Please install from git if you need to work with Django 1.11. See https://github.com/stephenmcd/mezzanine/issues/1749.

**Comment by Eladio** [comment]
Hi jerivas,

I have downloaded the master repo from github. You have the same issue:
https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/utils/views.py#L180

Regards,
Előd

**Comment by jerivas** [comment]
You are correct, my mistake.

Upon further review, it looks like mezzanine.utils.views.render is 
deprecated, and it's not being used anywhere in the codebase. It's 
purpose was to tie in with the device detection framework, and we've 
removed that from the master branch.

You should change your code to use TemplateResponse or 
django.shortcuts.render (which should be a drop-in replacement).
