### ISSUE TITLE
User set with staff status cannot access admin page

### ISSUE THREAD

**Issue by mike1573** [stephenmcd/mezzanine#1826]
Hi,
   I've set up a new user with Staff status (Designates whether the user can log into this admin site) option checked, but I'm getting "You don't have permission to access the admin for this site." when attempt to login to the admin site. How do I resolve?

Mezzanine 4.2.3
Django 1.10.8
Python 2.7.6
SQLite 3.8.2

Thanks,
Michael

**Comment by jerivas** [comment]
There's a Site Permission field at the bottom of each user's admin page.
Make sure this user has been added to the site you're having trouble with.

**Comment by mike1573** [comment]
Hi, its set to 127.0.0.1:8000 for admin (which can access admin) and it is set to the same also for my new user's account that gets "You don't have permission...".

**Comment by mike1573** [comment]
As a test I also gave it all user permissions but still no luck.

**Comment by mike1573** [comment]
....I works if I give it superuser (which I don't want the user to have).

**Comment by stephenmcd** [comment]
You're definitely hitting the issue Ed described. Make sure that the host/port for the site record matches the actual host/port being used to access the site. If you're using a web server like Nginx or Apache you may have host headers misconfigured which would also cause this. If you still can't resolve this, please post to the mailing list where others might be able to help you.

**Comment by mike1573** [comment]
Ah, read the mailing-list... there is a difference between the site being there and it actually being selected... clicked on it, saved and it working now. Thanks guys.
