### ISSUE TITLE
Modeltranslation + inheriting from Mezzanine Page model breaks on deploy

### ISSUE THREAD

**Issue by denning** [stephenmcd/mezzanine#1829]
Not sure if this is an issue with Django or Mezzanine or more of problem with how I build my projects (most likely the third possibility.) Regardless, I wanted to post this in case it saves someone else some time.

If I'm recalling this correctly, when using modeltranslation Django/Mezzanine will create new migrations in some Mezzanine apps (i.e. Pages). If creating new models which inherit from mezzanine.pages.models.Page, then the migration file for the new model will refer to a migration file for Page which only exists locally. So, deployment will always break in this scenario.

**Workaround:** copy the Page migration file directly from local server's virtual environment to remote server.

(Others can probably find a much better solution, but that was the best I could come up with.)

----
Mezzanine 4.2.3 -> 1d976e5ebae37fd718f60c938164c2a532aad0da
Django==1.10.7
django-modeltranslation==0.12.1

**Comment by jerivas** [comment]
Thanks! For others looking for answers, this is also discussed in the docs: http://mezzanine.jupo.org/docs/multi-lingual-sites.html#translation-fields-and-migrations
