### ISSUE TITLE
Upgrade jQuery 

### ISSUE THREAD

**Issue by w194** [stephenmcd/mezzanine#1833]
That's probably low priority for a CMS that uses jQuery only for admin actions.

jQuery Versions Vulnerable to Selector XSS with class Attribute ('. XSS_VECTOR')

https://domstorm.skepticfx.com/modules?id=529bbe6e125fac0000000003

**Comment by stephenmcd** [comment]
I tried to upgrade to jQuery 1.9.1 which also requires a newer version of jQuery UI (1.9.1 is what I also used for that) - everything seems to work apart from front-end editing which I failed to resolve, so anyone looking to address this should look there next.

**Comment by jerivas** [comment]
As of f0a8d8bbdc5ed728123f3b10ae8caae362b9c018 we are now using jQuery 3.4
