### ISSUE TITLE
Mezzanine assumes QUERY_STRING is always present in META

### ISSUE THREAD

**Issue by AlexProfi** [stephenmcd/mezzanine#1834]
In the [`{% translate_url %}` tag](https://github.com/stephenmcd/mezzanine/blob/521a98c39bb6351c4b46067069f33caf95fe0a5e/mezzanine/core/templatetags/mezzanine_tags.py#L724) Mezzanine assumes `QUERY_STRING` is always in `request.META`. This is incorrect, the key might not exist in all WSGI environments.

**Comment by AlexProfi** [comment]
Hello I describe problem here
https://github.com/jonashaag/bjoern/issues/118
I think it is need to use request['context'].META.get('QUERY_STRING')
to decide this problem

**Comment by jerivas** [comment]
I know nothing about WSGI, but the maintainer of the `bjoern` server says [this is a bug](https://github.com/jonashaag/bjoern/issues/118#issuecomment-352583010). @AlexProfi would you be interested in contributing the PR?

**Comment by stephenmcd** [comment]
3bff36cd66e997f175ef5778d366207be8dd5357
