### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

### ISSUE THREAD

**Issue by peterchen16** [stephenmcd/mezzanine#1837]
my secret key is already in local_settings.py, but I still get this error:

django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

I am using mezz 4.2.3

**Comment by ryneeverett** [comment]
Please direct questions to [the mailing list](http://groups.google.com/group/mezzanine-users/topics). You'll want to include details such as how you bootstrapped your project, set up your environment, invoked a server, etc.
