### ISSUE TITLE
Upgrading from 1.2.4 to actual 4.2.3

### ISSUE THREAD

**Issue by Ovsyanka** [stephenmcd/mezzanine#1840]
Hello!

I have the old mezzanine project. It's version is 1.2.4. Now I want to upgrade it to actual mezzanine version 4.2.3.

I tried to create new mezzanine project, copy there the sqlite3 database from the old instance and apply migrations. But it was not worked out because initial migrations was skipped, but actually they was changed at least in commit ebbe66f15b1370b024da1c09f184771ccf62d3d9. So my admin panel crushed with error `no such column: generic_threadedcomment.rating_count`.

Is there any convinient way to do such upgrade? Maybe I did something wrong?

That is what I did breafly:

```
python3 -m venv venv
. venv/bin/activate
pip install mezzanine
mezzanine-project test
cd test
cp <oldBasePath> ./dev.db
python manage.py migrate --fake-initial
```

**Comment by stephenmcd** [comment]
Please use the mailing list.

**Comment by Ovsyanka** [comment]
I am sorry. Didn't noticed that in https://github.com/stephenmcd/mezzanine#support. I wroted the question there.
