### ISSUE TITLE
Form field order button not working

### ISSUE THREAD

**Issue by Kianoosh76** [stephenmcd/mezzanine#1841]
Hi
The up/down arrow in the Order column of form fields in the admin interface is not functioning at all!
Every time I have to inspect and change the order values manually
![screen shot 2018-01-26 at 12 27 40 pm](https://user-images.githubusercontent.com/13102646/35432353-05f3cd8a-0295-11e8-80a6-95dd2c5dae70.jpg)

**Comment by jerivas** [comment]
Hello!

- What version of Python/Django/Mezzanine are you using?

- Are you clicking on the arrows, or dragging them?

**Comment by Kianoosh76** [comment]
I'm using python 3.6, django 1.11 and the latest commit of Mezzanine!
Neither clicking nor dragging the arrows will work.

**Comment by jerivas** [comment]
I just started a fresh project and you're correct. I'll look into it in 
a bit.

**Comment by jerivas** [comment]
In an unexpected twist: it was me who introduced this bug when I created a Form class for the Field model a few months ago [inheriting from the wrong class](https://github.com/stephenmcd/mezzanine/commit/4c8b4d75da7281ba65f5f1b9d30b2b4e2a25d483#diff-a8a0f1545156e67e9ff54ce5e2171f6aR53). The required JS files for re-ordering were not being loaded, now it's fixed. Thanks for the report!
