### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by ant6** [stephenmcd/mezzanine#1842]
Hi!

I'm just wondering, when will be the next tagged release? 😕 Commits after 4.2.3 introduced some important changes like Django 1.11 compatibility. Plus - pulling specific version from pypi is, I think, clearer solution than git checkout on commit from repo. And to some people mezzanine may appear dead because of nearly a year without any releases. Are there particular reasons for this, that I'm missing? 😞

**Comment by afs2015** [comment]
@ant6 

If you need to use Django 1.11 you can update your requirements.txt file to remove Mezzanine,  include this
`# Temporary Mezzanine for Django 1.11
git+https://github.com/stephenmcd/mezzanine.git@3bff36cd66e997f175ef5778d366207be8dd5357` and uninstall Mezzanine from your local environment before you install from requirements.txt.

You can see this comment https://github.com/stephenmcd/mezzanine/issues/1749#issuecomment-334009914 for more details on your question.

**Comment by afs2015** [comment]
@ant6, you liked [the comment](https://github.com/stephenmcd/mezzanine/issues/1749#issuecomment-334009914) which wrote

> With that said, please refrain from asking when there will be a new release or if there are any updates. The only update would be that the release has been made. When that happens, this issue will get closed off. If it's still open, that means there hasn't been a release yet. It will happen when I can find the time, which is something that I cannot predict. This is all relatively trivial given the fact you can use Mezzanine with the latest Django version right now.
