### ISSUE TITLE
Keywords aren't saved in the admin w/Django >= 1.11

### ISSUE THREAD

**Issue by orutherfurd** [stephenmcd/mezzanine#1844]
`KeywordsWidget.format_output()` is no longer called, due to widget rendering changes, so the javascript isn't properly hooked-up, and keywords don't get saved.

**Comment by crazyscot** [comment]
From the Django 1.11 changelog:
"The **Widget.format_output()** method is removed. Use a custom widget template instead."

**Comment by MelvinDRM** [comment]
Hello. Is there any proven solution to this issue?

**Comment by crazyscot** [comment]
The fix works for me.
