### ISSUE TITLE
[Possible Improvement] Check for SSL in sitemap

### ISSUE THREAD

**Issue by MelvinDRM** [stephenmcd/mezzanine#1850]
Hello Stephen and Mezzanine community,

It's a pleasure to greet you again.

I was reading about the Mezzanine sitemap and its code, and I ended up in Django's docs. There is an attribute called protocol which you can set to indicate if it uses http or https in the generation of the sitemap.

Currently, as far as I've checked, Mezzanine doesn't set in any way that attribute. If you set SSL_ENABLED as True so you can tell Mezzanine that you're using a secured protocol, the class DisplayableSitemap should check for it, with something like this (the code I edited for my project is mezzanine/core/sitemaps.py):

```
class DisplayableSitemap(Sitemap):
    """
    Sitemap class for Django's sitemaps framework that returns
    all published items for models that subclass ``Displayable``.
    """

    # Check if SSL is enabled so we force the sitemap to show URLs with HTTPS
    if settings.SSL_ENABLED:
        protocol = 'https'
    else:
        protocol = None

    def items(self):
        """
        Return all published items for models that subclass
        ``Displayable``, excluding those that point to external sites.
        """
        return list(Displayable.objects.url_map(in_sitemap=True).values())

    def lastmod(self, obj):
        if blog_installed and isinstance(obj, BlogPost):
            return obj.updated or obj.publish_date

    def get_urls(self, **kwargs):
        """
        Ensure the correct host by injecting the current site. Also, we set the
        correct protocol in case SSL_ENABLED is set to True
        """
        kwargs["site"] = Site.objects.get(id=current_site_id())
        kwargs["protocol"] = self.protocol
        return super(DisplayableSitemap, self).get_urls(**kwargs)
```

According to the docs (https://docs.djangoproject.com/en/1.11/_modules/django/contrib/sitemaps/), if protocol is None it goes straight to http, but if it is not None (the other option, according to https://docs.djangoproject.com/en/1.11/ref/contrib/sitemaps/#django.contrib.sitemaps.Sitemap.protocol is https), it goes to self.protocol, which means https can come into play in the URLs definition of the sitemap.

It's a small thing, but I believe it's a good thing to add because I think it helps with SEO.

What do you think?

Regards,

Melvin

**Comment by kenbolton** [comment]
Hi Melvin,

Looking at two mezzanine sites' sitemap.xml files:

- http://mezzanine.jupo.org/sitemap.xml
- https://bldg92.org/sitemap.xml

It seems the protocol is honored without any extra work on the part of the developer. You don't even need to set `SSL_ENABLED = True`.

**Comment by stephenmcd** [comment]
I can confirm on the demo site linked above, which has a self-signed cert and can be accessed over HTTPS also - the sitemap uses whichever protocol is being used to access it.
