### ISSUE TITLE
Newly created mezzanine project failes "python manage.py test"

### ISSUE THREAD

**Issue by johnfwhitmore** [stephenmcd/mezzanine#1860]
I have reviewed the contributing guidelines, I have discussed this issue, on both the IRC Channel and the users mailing list, pretty much with myself. Perhaps I should not be using pip to install mezzanine and this actually works in later code?

$ mkdir project
$ cd project
$ pipenv install mezzanine
$ pipenv shell
$ mezzanine-project project
$ cd project
$ python manage.py test

======================================================================
ERROR: project.project (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: project.project
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
ModuleNotFoundError: No module named 'project.project'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

**Comment by stephenmcd** [comment]
Works for me.

``` ~/dev  mkdir project
 ~/dev  cd project
 ~/dev/project  mezzanine-project project
 ~/dev/project  cd project
 ~/dev/project/project  ./manage.py test ..
Creating test database for alias 'default'...
System check identified no issues (0 silenced).

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Destroying test database for alias 'default'...```

**Comment by jerivas** [comment]
I'm able to reproduce the issue in Python 3.6, but not 2.7.

**Comment by jerivas** [comment]
I found a [similar issue on StackOverflow](https://stackoverflow.com/a/22096628/1330003). The work around seems to be to delete the top-level `__init__.py` on the Mezzanine project. However, I'm not sure if this will have any other effects.

Another solution is to point the test runner directly at the tests for a particular app.

```
$ django-admin startapp myapp
$ python manage.py test myapp.tests
```

**Comment by stephenmcd** [comment]
I traced the origin of that __init__.py and it's required internally for generating docs - but I tested a new project without it against Python 2.7 and 3.6 and everything seems to work fine locally without it, so I've made the mezzanine-project command remove it for new projects. 

It may have some side effect with a deployed project and the bundled fabfile, but I think that would be a separate issue and the file doesn't belong in new projects, so we can deal with that separately if it's a problem.

**Comment by johnfwhitmore** [comment]
Thank you for looking at that. I was trying to find the source of the problem but never got close. I never thought of the Python version as the documentation indicated that it was supported on both Python 2 and 3.
