### ISSUE TITLE
Enforce uniqueness of user email address via /admin/auth/user/x/ form

### ISSUE THREAD

**Issue by jogwen** [stephenmcd/mezzanine#1868]
I have a Mezzanine project with ACCOUNTS_NO_USERNAME=True so that users sign up and log in using an email address and password, never their username. This was working great, and all front-end forms (sign-up and profile update) enforce uniqueness of the email address across the User table. 

However, two days ago, an user of the /admin/ screens edited an user's email address to match that of another user (long story, but it was a reasonable mistake to make as both accounts did in fact represent one real-world person). When the user in question next attempted to log in they got an error response and we got an error email showing, as one would expect, "MultipleObjectsReturned: get() returned more than one User -- it returned 2!".

Users of /admin/ shouldn't have to bear the burden of maintaining the integrity of the email address field when it is needed to uniquely identify an user object.

**Comment by jerivas** [comment]
I agree. Would you like to set up a PR to contribute this change?

**Comment by jogwen** [comment]
Many thanks @stephenmcd!
