### ISSUE TITLE
Email report of 500 error at /accounts/login/ shows the entered password in plain text

### ISSUE THREAD

**Issue by jogwen** [stephenmcd/mezzanine#1869]
Happened as a result of situation described in [the separate Issue report 1868](https://github.com/stephenmcd/mezzanine/issues/1868). After the full traceback, the email showed the following (note the password value entered by the user - shown in **plain text**): 

> Request repr(): 
> <WSGIRequest
> path:/accounts/login/,
> GET:<QueryDict: {u'next': [u'/contact-us/']}>,
> POST:<QueryDict: {u'username': [u'g.smith@example.com'], u'referrer': [u'https://example.com/contact-us/'], u'csrfmiddlewaretoken': [u'ejnpimakedhajhdlcegeplioahd'], u'password': [u'orangesAnd5Lemons']}>,

[Django's version of the view that covers this](https://github.com/django/django/blob/1.8.7/django/contrib/auth/views.py#L32) is protected by the sensitive_post_parameters decorator, so that the values of POST parameters never appear in the emailed error report.

**Comment by jerivas** [comment]
So is it a matter of just decorating the view?

**Comment by jogwen** [comment]
I think so yes, but the slightly trickier bit might be figuring out which methods to decorate and for each one whether to protect only some variables (in which case supply their names as arguments to the decorator) or all the variables (supply no arguments to decorator). Try grepping the django code for sensitive_post_parameters and sensitive_variables to see how they do it there, and then figure out which of those methods have been 'replaced' in Mezzanine.

**Comment by jerivas** [comment]
Looks like we just need to decorate `login`, `signup`, and `profile_update` on the [account views](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/accounts/views.py). The sensitive fields are `password` on [LoginForm](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/accounts/forms.py#L47) and `password1`, `password2` on [ProfileForm](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/accounts/forms.py#L79-L82).

Would you like to contribute a PR?

**Comment by dojutsu-user** [comment]
@jerivas If it is just decorating the views, I would like to do this so as to get started with this project.

**Comment by jerivas** [comment]
That’s the impression I got from reading the documentation. Please go ahead and submit a PR :)
