### ISSUE TITLE
Persistent Cross-site Scripting in Mezzanine 4.3.1

### ISSUE THREAD

**Issue by security-provensec** [stephenmcd/mezzanine#1872]
Affected software: Mezzanine 4.3.1

Type of vulnerability: Persistent Cross-site Scripting

URL: http://mezzanine.jupo.org/

Discovered by: Provensec LLC

Website: https://www.provensec.com

Author: Subodh Kumar

Vulnerability Description: Cross-Site Scripting (XSS) attacks are a type of injection, in which malicious scripts are injected into otherwise benign and trusted websites. XSS attacks occur when an attacker uses a web application to send malicious code, generally in the form of a browser side script, to a different end user. Flaws that allow these attacks to succeed are quite widespread and occur anywhere a web application uses input from a user within the output it generates without validating or encoding it.

Steps to reproduce vulnerability: -

1) Login the admin account.
2) Locate URL: http://127.0.0.1:8000/admin/blog/blogpost/add/
3) Click on "Add another blog Category", a new window will be open.
![image1](https://user-images.githubusercontent.com/41563984/44204801-d31bf000-a171-11e8-97c6-e7140ab7be2c.PNG)

4) Put XSS payload "><svg/onload=alert(2)> in the "title" field.
![image2](https://user-images.githubusercontent.com/41563984/44204812-df07b200-a171-11e8-9544-9f8bb6accdc3.png)

5) Now, save the post and click on View (XSS payload gets executed).
![image3](https://user-images.githubusercontent.com/41563984/44204825-ec24a100-a171-11e8-9703-a957fa71546d.PNG)

Vulnerable URL:
http://127.0.0.1:8000/admin/blog/blogcategory/add/?_to_field=id&_popup=1

Vulnerable parameter:
Input field name: -     title (type - text)

**Comment by security-provensec** [comment]
Hi Team,

Any updates regarding the patch.

**Comment by stephenmcd** [comment]
The issue is resolved in https://github.com/stephenmcd/grappelli-safe/commit/a0abcad74ce5f5dc252d399761aaf67e1c99410f which is a dependency of Mezzanine and a new version of that has been released.
