### ISSUE TITLE
ValueError: astimezone() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by niol** [stephenmcd/mezzanine#1874]
Hi,

Just upgraded my small blog to 4.3.1 and I get:

```
File "/usr/lib/python3/dist-packages/mezzanine/blog/templatetags/blog_tags.py" in <listcomp>
  25.     dates = [d.astimezone(tz) for d in dates]

Exception Type: ValueError at /blog/
Exception Value: astimezone() cannot be applied to a naive datetime
```

This seems to be related to https://github.com/stephenmcd/mezzanine/commit/e17b4e0096cee2e43f63aefde56f819f17e154aa

**Comment by niol** [comment]
Switching to ```USE_TZ = True``` works around the problem.

**Comment by stephenmcd** [comment]
Thanks for posting the solution.
