### ISSUE TITLE
TinyMCE error 500 on displayable links that prevents from creating links

### ISSUE THREAD

**Issue by MelvinDRM** [stephenmcd/mezzanine#1875]
Hello people,

I'm having an issue with TinyMCE that I can't create links inside the editor. Whenever I attempt to create a link, it throws an Error 500 in console.

I have looked around in Google and found this two links:

https://github.com/stephenmcd/mezzanine/issues/1365
https://stackoverflow.com/questions/2492452/problem-with-insert-update-links-with-tinymce

I used both suggestions but it doesn't work on production, only in localhost.

The project runs Mezzanine 4.2.3, uses Django 1.11 and has HTTPS.

Any suggestions?

Thanks in advance.

Melvin

PD: Posted this on the Mezzanine Google Group

**Comment by stephenmcd** [comment]
This is already reported in #1634
