### ISSUE TITLE
Can't display blog content fully

### ISSUE THREAD

**Issue by haoglehaogle** [stephenmcd/mezzanine#1891]
Can only display blog the first line content, can't display entire blog content.
Cause this issue is that 'Enter' key to create new line,  it will don't displayed . that content will be displayed if 'Shift + enter' key to create new line .

**Comment by stephenmcd** [comment]
That's how short descriptions are generated - if you want the post listing to display entire blog posts, you can modify it here: https://github.com/stephenmcd/mezzanine/blob/6cdd31d5ddc8abc7da6df4140878820a28ec8174/mezzanine/blog/templates/blog/blog_post_list.html#L112

BTW if you have any other questions like this, please use the mailing list.
