### ISSUE TITLE
Unforunate filebrowser class naming causes adblocker to break the gallery.

### ISSUE THREAD

**Issue by fake-name** [stephenmcd/mezzanine#1900]
Basically, a bunch of the `td` tags in the filebrowser have the class `fb_icon`. 

Unfortunately, `fb_icon` is also widely used as the class name for creepy facef\*ck tracking widgets, and therefore is fairly broadly blocked by adblockers. 

The end result of this is the filebrowser winds up being very broken if you have adblock enabled:

![image](https://user-images.githubusercontent.com/1401239/47958304-0d817600-df86-11e8-8b51-f542f0d44005.png)

It'd probably be best to not use a class name that coincides with widely blocked classes. I presume `fb_icon` means "file browser icon", but still. Maybe use the full name (`filebrowser_icon`)?

Worse, because the way at least uBlock origin blocks these (with `!important display: none`), it doesn't show as the adblocker blocking anything, because it's not a request, or any of the sort of things adblockers normally instrument. Therefore figuring it's a adblocker issue is basically guesswork. The adblocker can happily report "no blocked requests", and still cause the failure.

**Comment by stephenmcd** [comment]
https://github.com/stephenmcd/filebrowser-safe/issues/122

**Comment by fake-name** [comment]
Ah, cool.

**Comment by fake-name** [comment]
It's also probably worth noting that this was the underlying cause behind https://github.com/stephenmcd/mezzanine/issues/1567, though there wasn't enough info there to go anywhere.
