### ISSUE TITLE
No way to add multiple images to gallery.

### ISSUE THREAD

**Issue by fake-name** [stephenmcd/mezzanine#1901]
Through the file manager, I created a folder, and uploaded a number of photos to said folder.

Now, I'm trying to create a gallery of those photos, but I can't seem to find any way to add *all* the photos in a directory to a gallery page. Is this not possible?

How are you supposed to manage large galleries?

**Comment by stephenmcd** [comment]
Galleries have a zip file upload option.

Please use the mailing list for further questions.

**Comment by fake-name** [comment]
If the zip is sufficently large, it times out. In this case, I have a ~201 MB zip, and it fails to upload.
