### ISSUE TITLE
Slow Search in Mezzanine CMS

### ISSUE THREAD

**Issue by shangzhikeji** [stephenmcd/mezzanine#1902]
Slow Search in Mezzanine CMS. I use Mezzanine CMS. I find it too slow when searching for something. The size of blog_blogpost is about 60,000 records.
The example site is [www.chinalaw.vip](http://www.chinalaw.vip).

Please help!

**Comment by stephenmcd** [comment]
Can you try the mailing list? Thanks!

**Comment by shangzhikeji** [comment]
Slow Search in Mezzanine CMS. I use Mezzanine CMS. I find it too slow when
searching for something. The size of blog_blogpost is about 60,000 records.

The example site is www.chinalaw.vip

Please help!
[image: 1.png]
[image: 2.png]

Stephen McDonald <notifications@github.com> 于2018年11月12日周一 上午11:46写道：
