### ISSUE TITLE
Django 2.1.4 - No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by j1v3** [stephenmcd/mezzanine#1907]
Hi,

With Django 2.1.4, we had this issue when executing :  python manage.py createdb --noinput

~~~~
  File "/home/j1v3/www/venv/lib/python3.6/site-packages/filebrowser_safe/views.py", line 14, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
~~~~

I tried to solve it by replacing 'django.core.urlresolvers' occurrence by 'django.urls' in accordance with this post on [StackOverflow](https://stackoverflow.com/questions/43139081/importerror-no-module-named-django-core-urlresolvers) but finaly i got this issue :

~~~~
  File "/home/j1v3/www/venv/lib/python3.6/site-packages/Mezzanine-4.3.1-py3.6.egg/mezzanine/core/templatetags/mezzanine_tags.py", line 21, in <module>
    from django.template.base import (TOKEN_BLOCK, TOKEN_COMMENT,
ImportError: cannot import name 'TOKEN_BLOCK'
~~~~

So I think this is a compatibility issue with this version of Django but my Python skills are not enough to handle the issue by myself...

**Comment by blacklin** [comment]
Now mezzanine only support Django version 1.8 to 1.11, you should uninstall high version and reinstall 1.8

**Comment by petedermott** [comment]
You certainly shouldn't be using 1.8 as support [ended for it back in 2018](https://www.djangoproject.com/download/) 1.11 is the current LTS version and will be supported through to April 2020, you can install it manually with `pip install django==1.11.20`

**Comment by Allan-Nava** [comment]
Is possibile to upgrade the dependecy of mezzanine with 2.2? https://docs.djangoproject.com/en/2.2/releases/2.2/

**Comment by petedermott** [comment]
2.x django compatibility is something that is being worked on (albeit very slowly) you should check #1928 for updates and progress.

**Comment by jerivas** [comment]
Mezzanine 5.0 RC1 now supports Django 2+
