### ISSUE TITLE
{% nevercache %} template tags are corrupt when both compression and caching are used

### ISSUE THREAD

**Issue by petedermott** [stephenmcd/mezzanine#1909]
When both Mezzanine's `mezzanine.core.middleware.UpdateCacheMiddleware` /     `mezzanine.core.middleware.FetchFromCacheMiddleware` and Djangos own `django.middleware.gzip.GZipMiddleware` are enabled and `DEBUG = False` parts of a template can become corrupt and unreadable. 

This is mostly apparent in templates using the `{% nevercache %}` template tag but I have also had times when an entire template has become corrupt.

Minimal working example: https://github.com/petedermott/mezzanine-cache-compression-bug

**Comment by blackboxoperations** [comment]
Given the complexity of middleware behavior, and understanding that requests are piped through each middleware class top to bottom while responses are pushed back through the same middleware classes in reverse order (https://docs.djangoproject.com/en/2.1/topics/cache/), I personally stopped using the Mezzanine specific nevercache template tag, and go with the @never_cache view decorator for views that contain forms. 

I don't think there's a way around the underlying nature of the forward to backward, backward to forward execution logic of the middleware classes, so while the nevercache template tag was neat for a spell, it's now a pain in the ass to try and get it to work. 

I don't think there's any real benefit to it anymore - @never_cache decorator does the job, and I doubt anyone's going to lose sleep over not getting that last 0.001% optimization and saving those precious few KB per year. 

If you found another way, I'd be very curious to know - of all the things I like about Django, the middleware implementation has never and will never be one of them.

**Comment by jerivas** [comment]
I think the previous comment contains a reasonable work around for those that require compression and caching middleware.
