### ISSUE TITLE
Thumbnail creation causing memory/timeout errors on Heroku with S3 storage of media

### ISSUE THREAD

**Issue by grwhumphries** [stephenmcd/mezzanine#1911]
Heya,  

I don't know if there's been a good solution proposed for this, but right now it seems that if you're deploying to Heroku and using Amazon S3 to serve media files (i.e. for the gallery), the 'on the fly' thumbnail creation leads to some serious memory problems, and timeouts. So if it takes 1 - 2 seconds per image, with a timeout on Heroku of 30 seconds, you're basically limited to only 10 / 12 images in your media library.  

Has there been a way developed to fix this that isn't just a workaround?

**Comment by stephenmcd** [comment]
Could you post this to the mailing list? Thanks
