### ISSUE TITLE
Post views count 

### ISSUE THREAD

**Issue by saileshkush95** [stephenmcd/mezzanine#1914]
I'm new to mezzanine, Actually I want to count post. Is there any easiest way to achieve this features and I also want to change mezzanine title in the dashboard and I also want to change default  comment form. I try to change  default template but, by default it is rendering Django form. Please help me to achieve this features..

**Comment by jerivas** [comment]
Hi, please use our mailing list for support requests https://groups.google.com/forum/#!forum/mezzanine-users
