### ISSUE TITLE
class 'theme.admin.PortfolioItemAdmin'>: (admin.E012) There are duplicate field(s) in 'fieldsets[0][1]

### ISSUE THREAD

**Issue by abuzabdi** [stephenmcd/mezzanine#1919]
**Hello!**

I've purchased Theme = Singularity and I got following error:

```
(env) [nap@centosweb singularity]$ python manage.py createdb
SystemCheckError: System check identified some issues:

ERRORS:
<class 'theme.admin.PortfolioItemAdmin'>: (admin.E012) There are duplicate field(s) in 'fieldsets[0][1]'.

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS.
```

which i fixed using this remedy:
https://github.com/stephenmcd/mezzanine/issues/1364

Now I'm getting:

```
(env) [nap@centosweb singularity]$ python manage.py createdb
SystemCheckError: System check identified some issues:

ERRORS:
<class 'theme.admin.PortfolioItemAdmin'>: (admin.E012) There are duplicate field(s) in 'fieldsets[0][1]'.
(env) [nap@centosweb singularity]$
```

Please have a look on this issue.

BR
Napoleon

**Comment by joshcartme** [comment]
I've looked into this and as far as I can tell it has to do with `ContentTypedAdmine` specifically these two lines, https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/admin.py#L300.

```
fields = (self.model._meta.get_fields() +
               self.model._meta.many_to_many)
```

I think in the past `self.model._meta.get_fields()` did not include m2m fields, but it does now so the admin class is ending up with duplicate fields in the fieldsets.

I think a fix for recent versions of Django would be to not add `self.model._meta.many_to_many`.  For now I've come up with the following workaround which can be added to an admin class that inherits from `ContentTypedAdmin` and has m2m fields:

```
    def __init__(self, *args, **kwargs):
        super(PortfolioItemAdmin, self).__init__(*args, **kwargs)
        # copy the fieldsets
        to_prune = deepcopy(self.fieldsets[0][1]['fields'])
        # make it a dict and back to list to remove duplicates
        self.fieldsets[0][1]['fields'] = list(dict.fromkeys(to_prune))
```

**Comment by RandomJo** [comment]
I'm noticing this as well on my project from one class that inherits PageAdmin but oddly only the one. I've noticed that if I remove _meta_title, the error goes away. Also if I manually specify the field sets and flip the order of the fieldsets, it goes away. It's also fine if I just manually move _meta_title to be listed second within its respective tuple. It's truly odd.

**Option A**
```
fieldsets = (
        ('Meta data', {'fields': [
           '_meta_title', 'slug', ('description', 'gen_description'),
           'keywords',
           'in_sitemap'], 'classes': ('collapse-closed',)
        }),
        (None, {'fields': [
            'title', 'status', ('publish_date', 'expiry_date'), 'in_menus',
            'login_required']
        }),
)
```

**Option B**
```
fieldsets = (
        (None, {'fields': [
            'title', 'status', ('publish_date', 'expiry_date'), 'in_menus',
            'login_required']
        }),
        ('Meta data', {'fields': [
           'slug', '_meta_title',  ('description', 'gen_description'),
           'keywords',
           'in_sitemap'], 'classes': ('collapse-closed',)
        }),
)
```

**Comment by jerivas** [comment]
Could you verify if this is still an issue with Mezzanine 5.0 RC1? Thanks!
