### ISSUE TITLE
blog.BlogCategory.None

### ISSUE THREAD

**Issue by saileshkush95** [stephenmcd/mezzanine#1926]
I want to display blog Post category name in this way in templates
{{ blog_post.categories }}
but is display blog.BlogCategory.None instead of category name

**Comment by christianwgd** [comment]
{{ blog_post.categories.all }} should do the trick. Have a look at blog/templates/blog/blog_post_list.html line 89 ff.

For further questions like this lets move to https://groups.google.com/forum/#!forum/mezzanine-users.
