### ISSUE TITLE
Is there a way to change content author

### ISSUE THREAD

**Issue by macguru2000** [stephenmcd/mezzanine#1927]
I am no Mezzanine expert, but have enjoyed using the project for almost 6 months now. I am confused why there is no "change author" feature, especially for the blog. We have the need for a super admin or editor role to be able to change the author of a particular blog post from time to time. Is this something that can easily be added to Mezzanine? A special addition to my theme's admin.py file perhaps?

In my postgres database it looks like user_id is just a simple foreign key that could easily be updated at any time. Am I missing something? Is there a reason the foreign key is treated as a "static" one time edit? Maybe there is a Django Setting? Some other way to turn this feature on?

Thanks so much for any help you can offer me. Appreciated.

**Comment by christianwgd** [comment]
You can simply override the admin of your blog: In the admin.py of your app include the following code:

```
from mezzanine.blog.admin import BlogPostAdmin
from mezzanine.blog.models import BlogPost
# add the user to the admins fieldset
blog_post_fieldsets = deepcopy(BlogPostAdmin.fieldsets)
blog_post_fieldsets[0][1]["fields"] += ("user",)

class MyBlogPostAdmin(BlogPostAdmin):
    fieldsets = blog_post_fieldsets

admin.site.unregister(BlogPost)
admin.site.register(BlogPost, MyBlogPostAdmin)
```

**Comment by christianwgd** [comment]
And btw. the more suitable place for questions like this would be https://groups.google.com/forum/#!forum/mezzanine-users. If you have further problems with this solution, let's move over there.

**Comment by jerivas** [comment]
Thanks for your help Christian!
