### ISSUE TITLE
Mezzanine works on unsupported version of Django

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [stephenmcd/mezzanine#1928]
Hi,

I notice that setup.py states that Django 2.0 is currently the highest version supported by Mezzanine. However that version of Django is no longer receives extended support (https://www.djangoproject.com/download/).

https://github.com/stephenmcd/mezzanine/blob/master/setup.py#L54

Your automated tests show that it can work on Django 2.1 though. When are you planning to release a version compatible with Django 2.1+? I'm particularly interested in Django 2.2 support as it's an LTS. What's your schedule?

**Comment by geoffroy-noel-ddh** [comment]
I wrote a message about this on the Google Group message board but it never became public...

Basically I need to upgrade several legacy website based on Mezzanine in the coming months. After that we are planning to make only minor updates of the stack and minor maintenance work but no upgrade for a few years. Ideally we'd put the app on Django 2.2 Long Term Support and be good for the next three years.

Is this project still being maintained and is there any roadmap for a Django 2.2-compatible release? If not how far is the development branch from being compatible with 2.2? I could consider contributing pull requests but I need an idea of how much work is left (is it a matter of days, weeks?) to get there.

Without clearer information my only remaining option is to migrate all my content to another Django CMS. I wish I could avoid that as it would be a lot of work and a shame as our users really likes Mezzanine and it has been the best suited CMS for our web app.

**Comment by petedermott** [comment]
I did some work on this on my own [mezzanine fork](https://github.com/fermorltd/mezzanine/tree/2.2-compat) (and [cartridge fork](https://github.com/fermorltd/cartridge/tree/2.2-compat) but haven't really had the time to finish what I started with it.

There are certainly some issues still with it (some JS stuff if I remember correctly) but it might give someone at least a starting point to see what else needs to be done.

**Comment by geoffroy-noel-ddh** [comment]
Hi @petedermott thanks for sharing that. That's really useful and I might start from that. I see that some of your changes have already been pulled into the main repo.

**Comment by molokov** [comment]
See also this thread on the mailing list: https://groups.google.com/d/topic/mezzanine-users/zOO9K5_9PMo/discussion

**Comment by christianwgd** [comment]
Hi, also working on that. I've made a pull request for two changes that were also in Peters fork, but made it a non breaking change for django 1.11. So not everybody has to analyze and change the same things again.

Maybe somone can do a short review on the chages. 

There's more to come, i.e. a change in filebrowser_safe where the widget.render signature changed (Support for Widget.render() methods without the renderer argument is removed in django 2.1).

I'm not sure, if anybody is more confident with Peters keyword_fields change (https://github.com/fermorltd/mezzanine/commit/f6da0a2219fa4d1b7bce4cac4e47d864dab08844). Maybe Peter can put that in pull request.

**Comment by christianwgd** [comment]
There are some minor css issues in the grappelli app:
- the horizontal filter widget css makes the widget too small
- there's no css for the new autocomplete widgets (select2)

**Comment by petedermott** [comment]
Another issue I've spotted with my current branch is that [sortable inlines](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/static/mezzanine/js/admin/dynamic_inline.js#L44) don't currently work due to an issue flagged as `TypeError: $(...).sortable is not a function` in the console.

The jQuery UI file seems to be loading but a check for it with `console.log($.ui ? $.ui.version || "pre 1.6" : 'jQuery-UI not detected');` in the dyanmic_inlnes.js file says that it isn't.

I _think_ this is because newer versions of Django includes jQuery 3.3.1 whilst older versions used jQuery 2.2.3 but I'm not 100% sure.

**Comment by cjh79** [comment]
Hi all, I am looking for 2.2 support as well. I am happy to jump in and help here as I have some time, but I don't want to duplicate work... it sounds like there are a few different forks floating around with 2.2 changes in progress, that haven't been pulled yet?

**Comment by petedermott** [comment]
Hi! Feel free to take my fork and make modifications to get it into a usable state. As mentioned the issue with the inlines was what was stopping me going any further with it.

**Comment by petedermott** [comment]
[Django 3.0 is also now available](https://www.djangoproject.com/weblog/2019/dec/02/django-3-released/) so I guess any work that is done going forward should also really try to take this into account.

**Comment by frankier** [comment]
I also would like to help finish off people's forks, although it's a little bit hard to know which I should start from. I suspect @stephenmcd is probably too busy with his work at Google to maintain this package any more. Probably the nicest solution would be to see if we could get @stephenmcd to move the project (and associated projects such as grapelli-safe, filebrowser-safe, cartridge) to one of https://jazzband.co/ or https://www.codeshelter.co/ ?

**Comment by matsaman** [comment]
This works for me (with python-3.6.9 / sqlite-3.30.1 / django-2.2.8)...

```bash
venv=".venv"
virtualenv "$venv"
source "$venv"/bin/activate
pip install \
	git+https://github.com/stephenmcd/filebrowser-safe \
	git+https://github.com/stephenmcd/mezzanine@refs/pull/1934/head \
	django==2.2.*
perl -pi -e \
	's/([ ]+"django\.contrib\.)(contenttypes)(",\n)/\1\2\3\1messages\3/','s/(MEDIA_URL = )STATIC_URL \+ ("media\/")/\1\2/' \
	"$(find "$venv" -ipath '*mezzanine*' -iname 'settings.py')"
mezzanine-project foo
python ./foo/manage.py createdb
python ./foo/manage.py runserver
```

...so pull request https://github.com/stephenmcd/mezzanine/pull/1934 might be a good start.

(Apologies if anybody else has a further along branch or pull request.)

Should probably also change #1749 to aim for Django 2.2 instead of 2.0.

**Comment by petedermott** [comment]
I've started a discussion regarding a possible migration to jazzband / code shelter over on the [mailing list](https://groups.google.com/forum/#!topic/mezzanine-users/u7bfCjftJCI) if people want to contribute.

**Comment by wimfeijen** [comment]
Thanks Peter! We would all greatly benefit from having a single place for development for this project. So I will add that we would like to help maintain Mezzanine

**Comment by codecowboy** [comment]
Hi. I am interested in any progress on this? I am planning on starting a Django based project and am keen to make use of Mezzanine for related sites. If there is a working, or almost working version of Mezzanine on Django2.2 then I would like to be kept in the loop so am subscribing to this issue.

**Comment by jerivas** [comment]
There are pull request open and currently being evaluated for Django 2.2 compatibility for mezzanine, filebrowser-safe and grappelli-safe. See  #1956

**Comment by jerivas** [comment]
#1956 has been merged!

**Comment by pymen** [comment]
**mezzanine with Django 2.2 support (until release v.5 will be ready)**

you can use the following line in your requirements

`-e git+git://github.com/stephenmcd/mezzanine.git@9768b46f8377796d5d51d74db54589c9d3669a47#egg=Mezzanine  # feat: Add Django 2.2 compatability (#1956)`

or for pip
` pip install -e git+git://github.com/stephenmcd/mezzanine.git@9768b46f8377796d5d51d74db54589c9d3669a47#egg=Mezzanine`

**Comment by jerivas** [comment]
You can also install the alpha from pip: `pip install Mezzanine==5.0.0a1`

**Comment by berluskuni** [comment]
Hello, tell me how to install mezzanine with Django 3,1 support?
Best regards, Sergei

**Comment by jerivas** [comment]
Hi! Mezzanine only works with Django 2.2. Contributions are welcome to add support for 3.0+

**Comment by Guitlle** [comment]
This messed up my dev sqlite database. Would this ruin my production mysql databse? How would I migrate a production site to upgrade from Mezzanine + Django 1.11 to Django 2.2?
