### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by semirci** [stephenmcd/mezzanine#1930]
Hello there,
It saddens me that Django does not support post 1.8 versions. :(

**Comment by geoffroy-noel-ddh** [comment]
Mezzanine supports Django 1.11 which will receive long term support until April 2020. 

At the moment Mezzanine is not compatible with any supported Django 2.x version though (master branch on github can run on Django 2.0.x but support for that has ended three months ago).

**Comment by eht16** [comment]
See also #1934 and #1928.

**Comment by jerivas** [comment]
Support for Django 2.2 has been added on #1956
