### ISSUE TITLE
Customize user profile

### ISSUE THREAD

**Issue by grwhumphries** [stephenmcd/mezzanine#1932]
Some issues implementing a custom user profile.  Following documentation with this structure in my code: 

```
# In myapp/models.py

from django.db import models

class MyProfile(models.Model):
    user = models.OneToOneField("auth.User")
    date_of_birth = models.DateField(null=True)
    bio = models.TextField()

```
I am getting an error:

AttributeError: 'str' object has no attribute '_default_manager'

Reading up suggests that the issue is the use of "auth.User" in quotes. When this is commented out, the problem goes away (except then I can't link to the user profile). 

Shouldn't there be an import here to get to the auth.User model?

**Comment by andrewt82** [comment]
this project is death...
use another cms

**Comment by grwhumphries** [comment]
Any suggestions for a CMS that is similar to Mezzanine? I really enjoy how simple the login/auth options generally are. I find things like django-cms to be over-engineered

**Comment by molokov** [comment]
Questions like this should be sent to the mailing list - not raised as issues. https://groups.google.com/forum/#!forum/mezzanine-users

In any case, you're right about the quotes not being needed. What you should do is:
```
from django.db import models
from django.contrib.auth.models import User

class MyProfile(models.Model):
    user = models.OneToOneField(User)
    date_of_birth = models.DateField(null=True)
    bio = models.TextField()
```

**Comment by grwhumphries** [comment]
Thanks @molokov  -> I wasn't aware of the Google group.

**Comment by andrewt82** [comment]
> Any suggestions for a CMS that is similar to Mezzanine? I really enjoy how simple the login/auth options generally are. I find things like django-cms to be over-engineered

i try use wagtail cms instead mezzanine
