### ISSUE TITLE
mercurial conflict in first deployment

### ISSUE THREAD

**Issue by denis54** [stephenmcd/mezzanine#1939]
Hello all,
I had trouble deploying mezzanine under a raspberry pi home server.
my mezzanine is used under python3 virtual env.
When using the automatic deploy tool, I have error message when the auto deploy tool try to download and install mercurial.
this is a part of the error message :
[192.168.1.65] out:     Python 3.7 detected.
[192.168.1.65] out:     
[192.168.1.65] out:     Mercurial currently has beta support for Python 3 and use of Python 2.7 is
[192.168.1.65] out:     recommended for the best experience.

Looking a little, it's look like mercurial is not really used in deployment... I excluded it 
I changed this line in fabfile.py like that :+1: # Install Python requirements
    sudo("pip install -U pip virtualenv virtualenvwrapper") # mercurial")

all work now.

I hope it can help
regards

**Comment by jerivas** [comment]
Unfortunately I'm unable to support mercurial or fabric deployments at the moment.
