### ISSUE TITLE
Incorrect String Value when installing Demo pages

### ISSUE THREAD

**Issue by addohm** [stephenmcd/mezzanine#1941]
When installing the demo pages the following error occurs:

> django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xCC\\x81vila...' for column 'file' at row 1")

Django 1.11.23 
Python 3.7
MySQL 5.7.27

For the time being, this can be fixed by setting your database character set to utf8mb4 after creating the database:
`ALTER DATABASE yourDBname CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;`

**Comment by jerivas** [comment]
You can set the encoding in `settings.DATABASES` as well:

```python
DATABASES = {
    "default": {
        ...
        "OPTIONS": {'charset': 'utf8mb4'},
    }
}
```

That works well with Mezzanine 5.0 RC1, Django 3.2 and MySQL 5.7.
