### ISSUE TITLE
On fresh install, URL namespace warnings occur

### ISSUE THREAD

**Issue by addohm** [stephenmcd/mezzanine#1942]
On a fresh install, running the local django development server shows the following:
> ?: (urls.W005) URL namespace 'djdt' isn't unique. You may not be able to reverse all URLs in this namespace

**Comment by jerivas** [comment]
Thanks. I'm unable to reproduce on a blank installation of Mezzanine 5.0 RC1. Could you verify again and share details of your setup? (Python version, Mezzanine version, installed packages, etc)
