### ISSUE TITLE
Maintaining a fork

### ISSUE THREAD

**Issue by khadegd** [stephenmcd/mezzanine#1944]
Hi fellow mezzanine users,

I am maintaining a fork of mezzanine [https://github.com/khadegd/august](https://github.com/khadegd/august). I could really use a bit of help from experienced `Mezzanine / Django` developers.

Use `pipenv install -e "git+https://github.com/khadegd/august.git#egg=Mezzanine" `. Warning! It's not production ready.

Targetting -
1. Python 3.7.*
2. Django LTS 2.2.* 
3. Bootstrap 4.3.*

**Comment by geoffroy-noel-ddh** [comment]
Hi, you might be interested in this ticket: #1928 where other contributors have started discussing their attempts at meeting Django 2.2 compatibility.

**Comment by ryneeverett** [comment]
Mezzanine does go through periods of inactivity from the core team but I don't see any need for a rebranding fork. Pull requests are welcome.
