### ISSUE TITLE
Problem editing Subsite

### ISSUE THREAD

**Issue by Sirman13** [stephenmcd/mezzanine#1945]
Hi, I forgive for my bad English, I have a problem with mezzanine cms, it allows me to edit the main page (exallievidonbosco.it) but not the subsites created, for example, potenza.exallievidonbosco.it. It tells me the following error message: Sorry, an error occurred.

Any problems with permits? I made the mark of the subsite, just created, and the problem always reappears, where can I find the logs?
thanks in advance, Andrea
![Errore](https://user-images.githubusercontent.com/42942739/64771055-a261e200-d54e-11e9-800a-43ff37fab9bd.JPG)

**Comment by jerivas** [comment]
Thanks, could you provide more information on how to reproduce the issue? Your server should have a log with details about the view that caused the error.
