### ISSUE TITLE
Fabric < 2.0 requirement creates Python 2.7 dependency

### ISSUE THREAD

**Issue by jmorsecode** [stephenmcd/mezzanine#1957]
Current packaged fabfile.py needs to be upgraded for use with Fabric 2+.
Accepting Fabric is not a _hard_ requirement for deployment and that this topic already appears in various threads already, I still believe it deserves an open issue. 
Fabric 1.x is not compatible with Python 3 and Python 2 is now officially EOL. 
Considering the sensitive nature of the calls that Fabric is making (handling privileged remote execution, git access, etc.) it would seem this should be a priority.

**Comment by jerivas** [comment]
Hi J.M.

I agree, specially since Mezzanine's next version will only work with Django 2.2+ and Python 3. We'd need to rewrite the fabfile to work with Fabric 2 or use another solution.

In the meantime, I have deployed several Python 3 sites with the existing fabfile by using [Fabric3](https://pypi.org/project/Fabric3/) (last version I used was Fabric3==1.13.1.post1). It has the same API as Fabric 1.X but works with Python 3.

**Comment by jmorsecode** [comment]
> Hi J.M.
> ...
> In the meantime, I have deployed several Python 3 sites with the existing fabfile by using [Fabric3](https://pypi.org/project/Fabric3/) (last version I used was Fabric3==1.13.1.post1). It has the same API as Fabric 1.X but works with Python 3.
@jerivas  Thanks for that! I have seen that in various threads and videos but actually thought it was a typo since the latest official is v2. That being said, after looking at that repo, it's certainly not being maintained anymore. My point above regarding the handling of sensitive files and privileged access would still apply.

**Comment by frankier** [comment]
https://github.com/ploxiln/fab-classic is maintained

**Comment by jmorsecode** [comment]
Just wanted to update. I'm about 90% done with writing a near feature parity fabfile with Fabric 2.6 and Python 3.6.  Without pulling in more dependencies it may lose some minor features but if my potential PR is accepted as a new baseline I'm sure someone with more skill could potentially replace those if they are deemed important enough.

**Comment by jmorsecode** [comment]
PR incoming later next week. Have been able to terraform destroy, apply to rebuild a fresh Ubuntu 20.04 linode, `fab secure`, and finally `fab all` several times over now.   Just need to polish it up and squash some commits. Fair warning there was some ugly workarounds.
