### ISSUE TITLE
When I logout, No Blog Post and Pages are showing on the home page

### ISSUE THREAD

**Issue by amannguptaggg** [stephenmcd/mezzanine#1964]
I have changes the default page setting to blog only URL.
Now After post publish when I logout, all the pages I created and blog post are gone.

When I login again all the content are showing again.

Someone help what's the problem.

**Comment by kenbolton** [comment]
Sounds like the "status" is set to draft and not published.

**Comment by amannguptaggg** [comment]
no... status is published.
and for page unchecked for login required to see page

**Comment by amannguptaggg** [comment]
I reinstalled Mezzanine from scratch and got error
`return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: Problem installing fixtures: no such table: pages_page__old`

**Comment by jerivas** [comment]
Hi @amannguptaggg, could you verify if the issue persist in mezzanine 5.0.0rc1? You can install it with `pip install mezzanine==5.0.0rc1`. If it does, please provide the exact steps to reproduce the issue on a blank Mezzanine installation. Thanks!
