### ISSUE TITLE
how to configure multiple sites with ssl certificate?

### ISSUE THREAD

**Issue by zzm88** [stephenmcd/mezzanine#1981]
I just simply modify the conf file of Nginx by adding server tags and reload Nginx. 
It works but when I add a new site I have to do the configuration work by hand again, since the fab deploy command will override the Nginx conf.

Is there a better way to set the servers information somewhere in setting files so that fabric can handle it by "fab deploy" command? It seems there is not much further information in mezzanine doc.

**Comment by jerivas** [comment]
Hi @zzm88,

We use Github to track bug reports. For support questions you might prefer to post on the mailing list to reach a wider audience: https://groups.google.com/g/mezzanine-users
