### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by jp-larose** [stephenmcd/mezzanine#1991]
Came here to see if work on this project had stopped.  Looks like it's alive and well.

This installation section of the overview page on the website (http://mezzanine.jupo.org/docs/overview.html#installation) shows a few things that made me wonder:

- Supported Python versions: 2.7 to 3.6 (Current release is 3.9)
- Supported Django versions: 1.8 to 1.11 (Current release is 3.2)

The change log also has not been updated since 2018.

I'm not sure if I'm looking at the most recent version of the documentation page, but it's where Google took me.

**Comment by jerivas** [comment]
Thanks for the report. Fixed in 36b2f4b8c32d9fd858f4daaf71fb7406984b1172.
