### ISSUE TITLE
How to serve different home page for different domains?

### ISSUE THREAD

**Issue by zzm88** [stephenmcd/mezzanine#1993]
I have three sites host on the mezzanine project. It goes well except that three domains goes to the same home.html template, which it's not what I want. What I need is routing requests to its own home template.
a.com -> home-a.html
b.com -> home-b.html
c.com -> home-c.html

**Comment by rapto** [comment]
You may try making home page a special page (see comments in your main urls.py) or using themes by site:
http://mezzanine.jupo.org/docs/multi-tenancy.html

**Comment by jerivas** [comment]
Please use the mailing list for general help requests: https://groups.google.com/g/mezzanine-users
