### ISSUE TITLE
"View on site" links don't respect dev server port

### ISSUE THREAD

**Issue by ccurvey** [stephenmcd/mezzanine#2043]
### Is there an existing issue for this?

- [X] I have searched the existing Issues

### Current Behavior

if you start mezzanine with the django dev server on a non-standard port (e.g. 5000), then the "view on page" links within the admin don't work.  (The redirects seem to send you to port 8000)

### Expected Behavior

pages should be shown on the production site

### Steps To Reproduce

1. start mezzanine with `python manage.py runserver 0.0.0.0:5000`
2. Edit a page in the admin
3. Click on the "view on site" button in the upper right

You will get a 404

### Environment

```markdown
* Mezzanine 6.0.0
* Django 4.0.5
* Python 3.10.4
* SQLite 3.37.2
* Linux 5.15.0-40-generic

(distro is Ubuntu 2022.04)
```

**Comment by jerivas** [comment]
The links are generated according to your Site records, not the port on which Django is listening. You'll need to update the domain and port in the "Sites" section of the admin sidebar.
