### ISSUE TITLE
[REQUEST] <title>Link Not Working

### ISSUE THREAD

**Issue by AyeshaIrshad1337** [stephenmcd/mezzanine#2053]
### Is there an existing request for this?

- [x] I have searched the existing Issues

### Current problem or need

The Link you provided is not working please check

### Desired solution

Link should be working for the perview

**Comment by henri-hulski** [comment]
Can you explain the problem a bit more?

**Comment by AyeshaIrshad1337** [comment]
yeah sure this link: http://mezzanine.jupo.org/ is not working

**Comment by kenbolton** [comment]
@AyeshaIrshad1337 Do you mean in the `README.rst` lines 152-158 and some assorted after those? The URLs redirect to the README of the appropriate repository on github.
