### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'frozenset' and 'list'

### ISSUE THREAD

**Issue by tombakas** [stephenmcd/mezzanine#2056]
[Version 6.0.0 of mozilla/bleach converts `ALLOWED_PROTOCOLS` to a frozen set](https://github.com/mozilla/bleach/commit/29231a10eb983e25b59c8edc5b6abcb12dbaaabe). Therefore, [the concatenation of `ALLOWED_PROTOCOLS` with `["tel"]`](https://github.com/stephenmcd/mezzanine/blob/c55bea257827bc708b8adfe7bdd0f3d7f8db82cd/mezzanine/utils/html.py#L113) causes a TypeError.

This can either be fixed by pinning the version to <6.0.0 or converting `ALLOWED_PROTOCOLS` to a list. Any preference? I can create a PR for this.

**Comment by tombakas** [comment]
Just realized this was already filed.

**Comment by molokov** [comment]
See #2054
