### ISSUE TITLE
manage.py createdb fails with "Unknown command: 'createdb'"

### ISSUE THREAD

**Issue by gthb** [stephenmcd/mezzanine#293]
I tried to go through the install steps, and this one fails:

```
$ python ./manage.py createdb
Unknown command: 'createdb'
Type 'manage.py help' for usage.
```

That was after `pip install` from PyPi, but the same happens after `python setup.py install` from git master.

`python manage.py` yields the following available subcommands:

```
[django]
    cleanup
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    reset
    runfcgi
    runserver
    shell
    sql
    sqlall
    sqlclear
    sqlcustom
    sqlflush
    sqlindexes
    sqlinitialdata
    sqlreset
    sqlsequencereset
    startapp
    startproject
    syncdb
    test
    testserver
    validate
```

Django version (installed by the `pip install`) is:

```
VERSION = (1, 4, 0, 'final', 0)
```

Python version is 2.7.3, in a virtualenv just created by virtualenvwrapper 1.6.4 on Mac OS X 10.7.4.

**Comment by tomkcook** [comment]
Ah, that's what it is.  I haven't really figured out what SECRET_KEY and NEVERCACHE_KEY are.

**Comment by orotau** [comment]
This was helpful for me
https://groups.google.com/forum/#!topic/mezzanine-users/M83HkEaq3rY

**Comment by stephenmcd** [comment]
`SECREY_KEY` is a Django setting, check its docs.

I've just documented `NEVERCACHE_KEY` - that'll show up in the next release:

https://github.com/stephenmcd/mezzanine/commit/a7101b8d29c8aeaddd35dbb14c3e3597f076dcb6
