### ISSUE TITLE
Feature Request: Version Control for Pages & Blog Posts

### ISSUE THREAD

**Issue by amites** [stephenmcd/mezzanine#297]
One of the few caveats I find in Mezzanine is the lack of version control for page revisions. Curious if this is on a roadmap anywhere?

I've started experimenting with merging mezzanine with https://github.com/etianen/django-reversion/ - happy to share results if interested

**Comment by nhoffman** [comment]
Hi, I'm curious if this feature has been added or is still being considered - more specifically, the ability to view or restore specific revisions of a page, and the ability to view difference between two arbitrary revisions. Thanks!

**Comment by vwbusguy** [comment]
nhoffman, There's already a "History" tab for pages/blog posts that track the type of changes.  That seems like a logical starting place for it.

**Comment by FeralBytes** [comment]
This feature definitely seems incomplete, just listing the arbitrary database fields that were changed, and not the actual string result of the change, is not really version control IMO. Thank you for the awesome CMS though.
