### ISSUE TITLE
Custom page content not appearing

### ISSUE THREAD

**Issue by jbittel** [stephenmcd/mezzanine#331]
I've been working on a new Mezzanine template and I've run into a problem with content not displaying on custom pages. I have a fairly typical setup (initially copied and then modified from the core Mezzanine templates) with a base.html to define site-wide layout and pages/page.html that extends base.html for page display. In base.html I have a 'main' block where all site content appears (per the core template examples):

```
<div id="main">
    <div class="container_12">
        <div class="grid_12 title clear2">
            <h1>{% block title %}{% endblock title %}</h1>
        </div>
        {% block main %}{% endblock main %}
    </div>
</div>
```

Up to this point, everything works completely as expected. However, for certain pages I need to use the custom page templates described [here](http://mezzanine.jupo.org/docs/content-architecture.html#page-templates). When I create a custom page with a name matching the page slug, no content at all appears in the main block (the editing features also do not appear). I've tried extending both base.html and pages/page.html, with the same result. I know it's using the correct template file because I can manually insert content on the custom page as follows:

```
{% block main %}Testing custom.html{% endblock main %}
```

That correctly displays the static text on the custom page, but none of the page content as created in the admin interface. I've tried simply copying my pages/page.html to pages/custom.html, but I get the exact same behavior. The template works as expected for pages.html, but as soon as custom.html is used, no content appears. I've tried using both the current release from PyPI as well as the latest code here on GitHub, but both versions demonstrate the same behavior.

Is this a bug, or am I missing something simple here? I've done quite a bit of research on this problem but I cannot seem to find much documentation on this feature outside of the [Page Templates](http://mezzanine.jupo.org/docs/content-architecture.html#page-templates) paragraph and I haven't been able to locate an existing Mezzanine theme that demonstrates custom pages in action.

Any help would be appreciated!

**Comment by wimfeijen** [comment]
Hi Stephen and jbittel,

Thanks for bringing this up. An additional question: {% block main%} in page.html automatically rescales images using mezzanine's thumbnails. {{ page.richtextpage.content|safe }}
 does not do that. Do you know of an easy solution to accomplish that resizing, for example by adding another filter?

Wim
