### ISSUE TITLE
Don't require mezzanine to be installed to use fabric scripts

### ISSUE THREAD

**Issue by lorin** [stephenmcd/mezzanine#336]
If mezzanine isn't installed, trying to run the fabric script fails, even if hosts are defined in settings.py

```
$ fab all
"Aborting, no hosts defined."
```

The problem is that settings.py file has the following lines at the end:

```
from mezzanine.utils.conf import set_dynamic_settings
set_dynamic_settings(globals())
```

The Fabric script fails to import mezzanine.utils.conf (it works if those lines are commented out). 

Even if you install mezzanine in a virtualenv, fabric scripts will fail if you've installed fabric at the system-level but not inside the virtualenv. 

Would be nice if the fabric scripts still worked even if mezzanine wasn't installed.

**Comment by uberdave** [comment]
I have mezzanine installed an I am getting this error.

**Comment by stephenmcd** [comment]
@uberdave that indicates some problem importing your project's settings module - go ahead and edit the fabfile to work out what the problem is.
