### ISSUE TITLE
Feature request: Replace TinyMCE with Redactor

### ISSUE THREAD

**Issue by jerivas** [stephenmcd/mezzanine#425]
I just stumbled with [Redactor](http://redactorjs.com/), and it seems to beat all other WYSIWYG editors. Take a look at it. There are only two potential issues, but they seem easily resolvable.
1. It requires a license, but it seems like $99 will make it apt for use in Mezzanine, forever, for everyone. Take a look at the [FAQ](http://redactorjs.com/download/). Let's have 99 Mezzanine developers donate one buck to finance this :)
2. It is not integrated with FileBrowser. However, it is [open to any kind of server side logic](http://redactorjs.com/docs/files/) in any programming language, so it should not be hard to hack into that. [Vanilla Django implementation](https://github.com/mazelife/django-redactor), [Tutorial](http://paltman.com/2012/08/15/how-to-setup-upload-handler-for-redactor/).

And those are the cons. On the pros, we have:
1. Complete [documentation](http://redactorjs.com/docs/)
2. Looks beautiful
3. I see great potential in the "Air mode" for inline editing
4. Supports drag and drop file upload
5. Supports auto save
6. Smaller than TinyMCE

**Comment by ytjohn** [comment]
For those that found this like I did, looking to find a better editor within mezzanine, there is now a djang-redactor plugin, which might be modifiable to work with mezzanine, if it doesn't work righ toff the bat. 
https://bitbucket.org/semente/django-redator
