### ISSUE TITLE
filebrowser_safe does not work with Amazon S3 (and presumably other services of the same kind)

### ISSUE THREAD

**Issue by jonatansberg** [stephenmcd/mezzanine#530]
Trying to open the Media Library fails with the following exception when assets are hosted externally (in this case using django-storages on S3): 

```
Stacktrace (most recent call last):
  File "mezzanine/pages/middleware.py", line 45, in process_view
    return view_func(request, *view_args, **view_kwargs)
  File "filebrowser_safe/views.py", line 76, in browse
    raise ImproperlyConfigured, _("Error finding Upload-Folder. Maybe it does not exist?")
```

**This is a major issue when running Mezzanine on a PaaS like Heroku where persistent file system access is limited or completely unavailable.**

The issue has already been discussed throughly here: 
https://groups.google.com/d/topic/mezzanine-users/kjsAw6WFqMY/discussion
and here: https://github.com/sehmaschine/django-filebrowser/issues/40

There is already a fix in the upstream version of django-filwbrowser, although some other minor issues with thumbnail generation still remain.

If the fix cannot easily be incorporated in the existing fork, maybe it's time to consider abandoning the *_safe-forks and use the newer versions of grappelli and filebrowser instead. Doing so would have the added benefit of 
- Not having to maintain these packages separately and instead focus on the core of Mezzanine, 
- Maybe fix some existing issues (I'm thinking #62)
- Gaining access to the progress and other improvements made since forking. [Grappelli](http://www.grappelliproject.com/) is looking really good now...

Keep up the good work!

**Comment by nym** [comment]
Is there a fork of django-storages that works for people? django-storages-redux has the entrylast_modified-is-none fix, but has other problems (specifically it can't find the media/uploads directory, which for the record is public).

**Comment by martyzz1** [comment]
I have this working now with custom subdomain bucket names deployed to Heroku

the key to fixing the thumbnail issue was setting this

AWS_PRELOAD_METADATA = True

**Comment by martyzz1** [comment]
I'm also using 

BeautifulSoup==3.2.1
beautifulsoup4==4.1.3
bleach==1.4.1
boto==2.38.0
dj-database-url==0.3.0
Django==1.6.10
django-appconf==1.0.1
django-compressor==1.4
django-storages==1.1.8
feedparser==5.1.3
filebrowser-safe==0.4.0
future==0.9.0
grappelli-safe==0.3.13
gunicorn==19.4.5
html5lib==0.999
httplib2==0.9
Mezzanine==3.1.10
oauthlib==0.7.2
Pillow==2.7.0
psycopg2==2.6
python-instagram==1.3.0
pytz==2014.10
requests==2.5.3
requests-oauthlib==0.4.2
simplejson==3.6.5
six==1.9.0
South==1.0.2
tweepy==3.3.0
tzlocal==1.0
whitenoise==2.0.6
