### ISSUE TITLE
Fabfile should detect unique settings across multiple projects

### ISSUE THREAD

**Issue by stephenmcd** [stephenmcd/mezzanine#547]
fabfile currently ensures that `FABRIC["PROJECT_NAME"]` doesn't exist on the server.

It should also ensure that there aren't existing projects deployed with the same values for `FABRIC["GUNICORN_PORT"]` and `FABRIC["LIVE_HOSTNAME"]`

**Comment by jerivas** [comment]
Closing due to the removal of fabric deployments in Mezzanine 5.
