### ISSUE TITLE
UnicodeEncodeError for page with unicode slug

### ISSUE THREAD

**Issue by dfalk** [stephenmcd/mezzanine#616]
I have the page with unicode slug.
It throws error, when try to load templates:

UnicodeEncodeError at /Ñ‚ÐµÑÑ‚Ñ‚/
'ascii' codec can't encode characters in position 60-64: ordinal not in range(128)

/python2.6/site-packages/django/template/loaders/filesystem.py in load_template_source:
    file = open(filepath)

vars:
    template_name   = 'pages/\xd1\x82\xd0\xb5\xd1\x81\xd1\x82\xd1\x82.html'
    filepath    = u'/home/hosting_dfalk/projects/perunspace/app/templates/pages/\u0442\u0435\u0441\u0442\u0442.html'

Even if file doesn't exist.

**Comment by brejoc** [comment]
I've had the same error and adding `environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8,LC_LANG=en_US.UTF-8` to the `supervisord.conf` in the section `[supervisord]` solved the problem.
