### ISSUE TITLE
TinyMCE 4

### ISSUE THREAD

**Issue by ghost** [stephenmcd/mezzanine#705]
TinyMCE 4 was released at 13 june 2013.

It's a project to switch to it or to choice between version 3 and 4 (on settings.py for example)?

**Comment by AlexHill** [comment]
I'll put aside some time to merge TinyMezzCE over the weekend. Could make another good addition for the next release, if there's time.

**Comment by orotau** [comment]
yep, I agree Alex, I am happy to test this when it is merged.
I have one simple pull request 
https://github.com/AlexHill/tinymezzce4/pull/6

cheers
g

**Comment by stephenmcd** [comment]
@AlexHill any idea what's left to be done here? If you're pressed for time maybe just some notes and someone else on the team can look at it? Looks like it will resolve an actual issue mentioned above.

**Comment by stephenmcd** [comment]
BTW I've also added all tinymce translation files, and integrated that with whatever UI language is selecting for the admin on Django's side.

https://github.com/stephenmcd/grappelli-safe/commit/a64d3420fb9ca1f4bde950ae87df85a2e3e732a2
https://github.com/stephenmcd/mezzanine/commit/2130cfd8af46bc128bc7b4e3a35d322ff997ba79

Not sure if that will cause any issues upgrading, but something worth noting.

**Comment by jerivas** [comment]
The only thing that IMO would need to be changed in Alex's current 
implementation is the fact that TinyMCE is being pulled from a CDN, and 
I think we should include it in the project (as it is currently).

I don't know if the default plugins enabled in tinymce_setup.js are 
worth any discussion. Personally I like to keep them to a bare minimum, 
but historically Mezzanine has had them all enabled by default.

**Comment by DasAllFolks** [comment]
One quick heads-up on this merge:  the `TinyMceWidget` bundled with @AlexHill's [tinymezzce4](https://github.com/AlexHill/tinymezzce4) doesn't quite yet achieve functional parity with the `TinyMceWidget` currently bundled with Mezzanine, as it's missing a couple of buttons like "Insert special character," "Edit source code," etc.

It's a pretty easy fix, though (see my pull request [here](https://github.com/AlexHill/tinymezzce4/pull/7/files), as well as @orotau's fix [here](https://github.com/AlexHill/tinymezzce4/pull/6)...although I'm not quite sure I can advocate that latter approach given the bugs it introduces as explained [here](https://github.com/AlexHill/tinymezzce4/issues/5)).

**Comment by AlexHill** [comment]
Hey all, sorry for the delay. I don't think there are any issues in merging this other than, as mentioned in this thread, ensuring that the default configuration makes everything available that's available in the current default TinyMCE setup.

**Comment by nym** [comment]
Would love to use TinyMCE 4... my designers and copywriters keep pushing us to switch to Wordpress.

**Comment by stephenmcd** [comment]
@AlexHill cool - are you able to bundle your repo into a PR, I guess against grappelli-safe (and anything supporting in Mezzanine if needed).

**Comment by stephenmcd** [comment]
Been testing this out, found a few issues:

- Fullscreen doesn't work (after adding it back to the toolbar)
- Inserted images aren't getting converted to thumbnails when rendered on the site, at a glance it looks like this is due to extraneous parent path prefixes (eg too may "../../")
- The "external_link_list_url" key in the old tiny_mce_setup.js doesn't seem to work when re-added. It provided a list of pages to link to when using the link too.

**Comment by stephenmcd** [comment]
Disregard my feedback, I've resolved those issues :-)

**Comment by AlexHill** [comment]
Thanks so much Steve. Sorry this has gone so long, I've just had no time lately. Great stuff.

**Comment by stephenmcd** [comment]
No worries mate, I saw you have a talk coming up so I figured you were flat out. Good luck!

**Comment by gradel** [comment]
Hi there, not sure its a bug, but I don't get the left-down-arrow on file selection dialog, which indicates
that I can choose to insert the image. Tested with Chrome and FF, local debugging and live production.

**Comment by jerivas** [comment]
Are you using the development version of file-browser and grappelli?

**Comment by gradel** [comment]
Yes, master branch, latest commits included.

**Comment by gradel** [comment]
The "pop" parameter here changed from 2 to 5: https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/static/mezzanine/js/tinymce_setup.js#L45
As stated in the comment query.pop should be 2 for tinymce:
https://github.com/stephenmcd/filebrowser-safe/blob/master/filebrowser_safe/templates/filebrowser/include/filelisting.html#L27
The value 5 is not targeted here, hence no "icon_select" gif is displayed.
Changing pop back to 2 doesn't work either, then clicking the file selection button causes a request to non existing grappelli/tinymce/jscripts/tiny_mce/tiny_mce_popup.js.

**Comment by yltang52** [comment]
Just installed the latest development version of Mezzanine. In TinyMCE, the check button of the uploaded image is not clickable. Please help.

**Comment by nym** [comment]
WOW, thank you so much for moving on this @stephenmcd. Will start testing it soon.

**Comment by yltang52** [comment]
Another BIG thing is: http://stackoverflow.com/questions/31020785/tinymce-how-to-center-an-image

I tried 'verify_html = false', 'valid_styles = display', etc. in TinyMCE.initially. None of them worked.

**Comment by jerivas** [comment]
I just click on the image, and then click on the "align center" button. 
Same to align to the left or right.

**Comment by yltang52** [comment]
Yes, and then when you save it, the 'display: block;' style will be removed.

**Comment by henri-hulski** [comment]
The solution for centering text and images is to add `display` and `text-align` to `RICHTEXT_ALLOWED_STYLES` in your `settings.py`.
``` python
RICHTEXT_ALLOWED_STYLES = (
    "margin-top",
    "margin-bottom",
    "margin-left",
    "margin-right",
    "float",
    "vertical-align",
    "border",
    "margin",
    "text-align",
    "display",
)
```
I think they should go into the Mezzanine `defaults.py` as they are used by the buttons of tinymce.

Any thoughts on this?

**Comment by ryneeverett** [comment]
@henri-hulski `text-align` was added in #1374 but there hasn't been a release since it was merged. Which button needs `display`?

**Comment by henri-hulski** [comment]
The center button for images uses display: block. 
Am 25.10.2015 22:03 schrieb ryneeverett <notifications@github.com>:@henri-hulski text-align was added in #1374 but there hasn't been a release since it was merged. Which button needs display?
