### ISSUE TITLE
Mobile site has issues in Mezzanine 1.4.16

### ISSUE THREAD

**Issue by senex** [stephenmcd/mezzanine#803]
There are some issues with the mobile site that I see so far that are also on the demo site:
1) Home button on the top doesn't work (just waits forever)
2) There is a reference to the following images, but they are not included with the mezzanine distribution:
    \* static/css/images/icons-36-white.png
    \* static/css/images/ajax-loader.png
    \* static/css/images/icon-search-black.png

**Comment by stephenmcd** [comment]
Closing since `mezzanine.mobile` was removed.
