### ISSUE TITLE
pages/templatetags/pages_tags.py fails when there is no user

### ISSUE THREAD

**Issue by RichGibson** [stephenmcd/mezzanine#960]
Running mezzanine under Apache I get "AttributeError: 'WSGIRequest' object has no attribute 'user'" the first two times I try to go to a page, the third time it works.

It initially failed in pages_tags.py 
line 48: except KeyError
Whcih doesn't catch AttributeError.

I can get past this error when I change the line to:
except (KeyError, AttributeError):

(but that moves the problem to templatetags/mezzanine_tags.py which also wants a user :-/)

**Comment by DatCGI2net** [comment]
Hi,
Stephen is right. There is nothing to do with those codes. The errors should be caused by the changes of your  database and the old compiled files(.pyc) that I got this morning. So, just remove the .pyc files and go with new database OR switch back to old one.
